---
title: "Sampling distribution"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```

__Sampling distribution__

The sampling distribution of a statistic is the distribution of a sample statistic computed on many different samples of the same size from the same population.

A sampling distribution shows how the statistic varies from sample to sample due to sampling variation.



__Centre and shape of a sampling distribution__

- _Centre_: If samples are randomly selected, the sampling distribution will be centred around the population parameter. _(No bias)_

- _Shape_: For most of the statistics we consider, if the sample size is large enough, the sampling distribution will follow a normal distribution, i.e. it is symmetric and bell-shaped. _(Central Limit Theorem)_


Clearly, we can compute sampling distributions for other statistics too: the proportion, the standard deviation, ...

This requires the following steps:

- Obtaining multiple samples, all of the same size, from the same population;

- For each sample, calculate the value of the statistic;

- Plot the distribution of the computed statistics. 


