---
title: "FAQs"
theme: zephyr
callout-appearance: simple
callout-icon: false
format:
  html:
    embed-resources: true
---

<!-- ::: {.callout-tip collapse="true"} -->
<!-- ## Title -->

<!-- Text -->
<!-- ::: -->


# R and RStudio

::: {.callout-tip collapse="true"}
## How do I register for RStudio server online?

__STEP 1.__ Try these steps first to register for RStudio server online:

- Log in to EASE <https://www.ease.ed.ac.uk/> using your university UUN and password.
- Set your RStudio password here <https://rstudio.ppls.ed.ac.uk/setpass.php> and press enter, the username will be the same as your UUN (make sure you type your UUN correctly).
- You can then access the server from <https://rstudio.ppls.ed.ac.uk> using your university UUN and the password you set above in (2). To access it in future, just use this link.


__STEP 2.__ If step 1 didn't work, please complete [this form](https://forms.office.com/Pages/ResponsePage.aspx?id=sAafLmkWiUWHiRCgaTTcYTstBwJEBklLhOSskzRST95UMTFKQlo5NkdOS0RNRTVXQjZLWloyU1RPQS4u) and wait for an email from us. Please note that this can take up to 3 working days. One you receive an email from us, please follow the following instructions:

- Set your RStudio password here <https://rstudio.ppls.ed.ac.uk/setpass.php> and press enter, the username will be the same as your UUN (make sure you type your UUN correctly).
- Access the server from <https://rstudio.ppls.ed.ac.uk> using your university UUN and the password you just set above. To access it in future, just use this link.
:::

::: {.callout-tip collapse="true"}
## I am registered for RStudio server online, how do I access it?

-   Log in to [EASE](https://www.ease.ed.ac.uk/) using your university UUN and password.

-   Access the server from <https://rstudio.ppls.ed.ac.uk> using your university UUN and the RStudio password.

-   If you have forgotten your RStudio password, you can reset it following the next FAQ instructions.
:::

::: {.callout-tip collapse="true"}
## How do I change my RStudio server password?

-   Set your RStudio password at <https://rstudio.ppls.ed.ac.uk/setpass.php>

    -   The username will be the same as your UUN (make sure you type your UUN correctly).

-   Access the server from <https://rstudio.ppls.ed.ac.uk> using your university UUN and the password you just set above.
:::


# General

::: {.callout-tip collapse="true"}
## Where do I start?

-   Navigate to the course Learn page

-   Read the contents of the 'Course Information' folder

-   Read the 'Assessment' -\> 'Assessment information' page.

-   Next, move on to contents of the 'Course materials: Semester 1' folder.
:::


::: {.callout-tip collapse="true"}
## Where do I find office hours information?

-   Navigate to the course Learn page

-   Click 'Course information'

-   Click 'Course contacts and office hours'

-   Office hours information is displayed next to the instructor's name.
:::

::: {.callout-tip collapse="true"}
## Where do I find information about the course assessments?

-   Navigate to the course Learn page

-   Click 'Assessment'

-   Click 'Assessment and feedback information'
:::

::: {.callout-tip collapse="true"}
## Is lab attendance graded?

Lab attendance is not graded. In the past years, however, students who failed the assessed report tended to not attend the labs and we found a positive association between attending the labs and the grade received in the report.
:::

::: {.callout-tip collapse="true"}
## Can I change the day and/or time of my lab?

After Week 3 of semester 1 it is **not** possible to change lab day/time.

Before the end of Week 3, please submit a __Group Change Request__ form a the following link to request a change: <https://www.ed.ac.uk/timetabling-examinations/timetabling/personalised-timetables>

The university timetabling unit will process it after a few working days.
:::

::: {.callout-tip collapse="true"}
## What are formative assessments?

Formative means practice, so formative assessments do not affect your course grade. They are meant to prepare you for summative (graded) assessments that will contribute towards your final course grade. 

Formative assessments give you the opportunity to 'learn by doing'. You should not be afraid to submit what you have done, as you will receive feedback on how to improve.
:::

::: {.callout-tip collapse="true"}
## How do I apply for extensions or special circumstances?

These are handled by a separated office of the University. Please follow the steps detailed in [this website](https://www.ed.ac.uk/student-administration/extensions-special-circumstances).

Note that in this course extensions are not allowed for weekly quizzes and the group reports. See the 'Assessement information' page on Learn for more information.
:::

::: {.callout-tip collapse="true"}
## Where can I get help and support?

The following is a list of sources of help and support:

-   **Labs**. Attend the labs to get help and support from tutors on the content of the lab exercises, R and RStudio, as well as lecture contents.

-   **Office Hours**. Attend office hours to receive one-to-one help on the course materials.

-   **Discussion Forum**. Search on the Piazza Discussion Forum, in case another student had the same question and it was already answered. You can also ask a new question on the Discussion Forum if no one has already asked the same question. Your student peers or instructors will be able to provide an answer to your question.

-   **Teaching organisation**. The [teaching organisation](mailto:ppls.psych@ed.ac.uk) can advise you on administrative inquiries about your course. This includes issues with submission of assessments, extensions, special circumstances, or exams.

-   **Student Adviser**. Your student adviser (you can find their name on MyEd or Euclid) is your first point of contact for generic help and support on matters that are not directly related to your course materials or organisation. They are able to also refer you to wider University services, such as the Wellbeing adviser, see below.

-   **Wellbeing adviser**. The [Wellbeing adviser](https://www.ed.ac.uk/student-wellbeing-service) can provide you with advice on wellbeing-related issues and recommend other specialist services, such as the Student Counselling Service or the Disability and Learning Support Service, who may be able to help you. You can be referred to the Wellbeing adviser by your Student adviser, or you can self-refer at the link above.

- **Cohort lead**. Your cohort lead (name on Euclid) can support you with academic-related questions, reference letters, and general advice on how to make the most of your time at university.

:::


# Learn

::: {.callout-tip collapse="true"}
## Where can I find my quiz grades on LEARN?

-   Go to the course LEARN page

-   On the top menu bar, click 'Gradebook'

-   Click on the relevant quiz name from the list of all quizzes
:::

::: {.callout-tip collapse="true"}
## Where can I find the solutions and feedback for the quizzes?

The quiz solutions and feedback are **not** immediately available after your submission, only your grade is. The solutions and feedback are available on Sunday after 5pm.

-   Go to the LEARN page of your course

-   On the top menu bar, click 'Gradebook'

-   Click on the name of the quiz for which you would like to see the question by question feedback.

-   Click on 'View Submission'
:::

::: {.callout-tip collapse="true"}
## How do I access the Piazza Discussion Forum?

-   Go to the course Learn page

-   Click Piazza Discussion Forum.
:::

