<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR1 - Confidence intervals</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="assets/styles.css">
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR1</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-lab-materials" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Lab Materials</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-lab-materials">
<li class="dropdown-header"><b>Block 1: Exploratory data analysis</b></li>
        <li>
    <a class="dropdown-item" href="./1_01_design_and_data.html" rel="" target="">
 <span class="dropdown-text">S1-W1: Research design &amp; data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_categorical_data.html" rel="" target="">
 <span class="dropdown-text">S1-W2: Categorical data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_numeric_data.html" rel="" target="">
 <span class="dropdown-text">S1-W3: Numeric data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_04_relationships.html" rel="" target="">
 <span class="dropdown-text">S1-W4: Relationships</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_05_formative_report_a.html" rel="" target="">
 <span class="dropdown-text">S1-W5: Formative Report A</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header"><b>Block 2: Probability</b></li>
        <li>
    <a class="dropdown-item" href="./1_07_prob_theory.html" rel="" target="">
 <span class="dropdown-text">S1-W7: Probability Theory</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_08_prob_rules.html" rel="" target="">
 <span class="dropdown-text">S1-W8: Probability Rules</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_09_discrete_dist.html" rel="" target="">
 <span class="dropdown-text">S1-W9: Discrete Random Variables</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_10_cont_dist.html" rel="" target="">
 <span class="dropdown-text">S1-W10: Continuous Random Variables</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_11_sampling.html" rel="" target="">
 <span class="dropdown-text">S1-W11: Formative Report B</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header"><b>Block 3: Inference</b></li>
        <li>
    <a class="dropdown-item" href="./2_01_confint.html" rel="" target="">
 <span class="dropdown-text">S2-W1: Confidence intervals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_02_ht_pvalues.html" rel="" target="">
 <span class="dropdown-text">S2-W2: HT (p-values)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./2_03_ht_critvalues.html" rel="" target="">
 <span class="dropdown-text">S2-W3: HT (critical values)</span></a>
  </li>  
    </ul>
</li>
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-readings" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Readings</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-readings">
<li class="dropdown-header"><b>Block 1: Exploratory data analysis</b></li>
        <li>
    <a class="dropdown-item" href="./rd1_01.html" rel="" target="">
 <span class="dropdown-text">S1-W1: Getting started with R and RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_02.html" rel="" target="">
 <span class="dropdown-text">S1-W2: Categorical data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_03.html" rel="" target="">
 <span class="dropdown-text">S1-W3: Numeric data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_04.html" rel="" target="">
 <span class="dropdown-text">S1-W4: Relationships</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_05.html" rel="" target="">
 <span class="dropdown-text">S1-W5: Functions</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header"><b>Block 2: Probability</b></li>
        <li>
    <a class="dropdown-item" href="./rd1_07.html" rel="" target="">
 <span class="dropdown-text">S1-W7: Probability 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_08.html" rel="" target="">
 <span class="dropdown-text">S1-W8: Probability 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_09.html" rel="" target="">
 <span class="dropdown-text">S1-W9: Discrete random variables</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_10.html" rel="" target="">
 <span class="dropdown-text">S1-W10: Continuous random variables</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_11.html" rel="" target="">
 <span class="dropdown-text">S1-W11: Sampling</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header"><b>Block 3: Inference</b></li>
        <li>
    <a class="dropdown-item" href="./rd2_01.html" rel="" target="">
 <span class="dropdown-text">S2-W1: Confidence intervals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd2_02.html" rel="" target="">
 <span class="dropdown-text">S2-W2: HT (p-values)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd2_03.html" rel="" target="">
 <span class="dropdown-text">S2-W3: HT (critical values)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd2_04.html" rel="" target="">
 <span class="dropdown-text">S2-W4: Connecting HT and CIs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd2_05.html" rel="" target="">
 <span class="dropdown-text">S2-W5: Errors, Power, Effect size, Assumptions</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
<div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#a.-population-data-available-unlikely" id="toc-a.-population-data-available-unlikely" class="nav-link" data-scroll-target="#a.-population-data-available-unlikely">A. Population data available (unlikely)</a></li>
  <li><a href="#na.-population-data-not-available-more-common" id="toc-na.-population-data-not-available-more-common" class="nav-link" data-scroll-target="#na.-population-data-not-available-more-common">NA. Population data NOT available (more common)</a></li>
  <li>
<a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"><span class="header-section-number">2</span> Confidence intervals</a>
  <ul class="collapse">
<li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example"><span class="header-section-number">2.1</span> Example</a></li>
  <li><a href="#interpreting-a-confidence-interval" id="toc-interpreting-a-confidence-interval" class="nav-link" data-scroll-target="#interpreting-a-confidence-interval"><span class="header-section-number">2.2</span> Interpreting a confidence interval?</a></li>
  </ul>
</li>
  <li><a href="#glossary" id="toc-glossary" class="nav-link" data-scroll-target="#glossary"><span class="header-section-number">3</span> Glossary</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Confidence intervals</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="introduction" class="level2" data-number="1"><h2 data-number="1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">1</span> Introduction</h2>
<p>Without loss of generality, we will consider the sample mean as the statistic of interest and we will consider two scenarios:</p>
<ul>
<li>Entire population data available (unlikely);<br>
</li>
<li>Entire population data are NOT available (more common).</li>
</ul>
<p>For both scenarios, we will investigate the following question:</p>
<blockquote class="blockquote">
<p>What was the average yearly salary of a National Football League (NFL) player in 2019?</p>
</blockquote>
<p>This question is about the mean salary of all NFL players in 2019, which is denoted <span class="math inline">\(\mu\)</span> and is a population parameter.</p>
</section><section id="a.-population-data-available-unlikely" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="a.-population-data-available-unlikely">A. Population data available (unlikely)</h2>
<p>If we have data on the entire population of NFL players and we are interested in a parameter such as the population mean salary, we can simply compute the mean on the available population data. There would be no uncertainty and nothing to estimate: we have the entire population data, so we can easily compute the mean salary, and we would know what the actual parameter value is.</p>
<p>In this scenario, we would have a file containing the yearly salaries (in millions of dollars) for all players being paid in 2019 by a National Football League (NFL) team. This entire dataset represents the entire population of all National Football League players in that year.</p>
<p>The data on the entire population:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">nfl_pop</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/NFLContracts2019.csv"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">nfl_pop</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  Player             Position Team     TotalMoney YearlySalary
  &lt;chr&gt;              &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt;        &lt;dbl&gt;
1 Russell Wilson     QB       Seahawks        140         35  
2 Ben Roethlisberger QB       Steelers         68         34  
3 Aaron Rodgers      QB       Packers         134         33.5
4 Jared Goff         QB       Rams            134         33.5
5 Carson Wentz       QB       Eagles          128         32  
6 Matt Ryan          QB       Falcons         150         30  </code></pre>
</div>
</div>
<p>The population mean salary:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mu</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">nfl_pop</span><span class="op">$</span><span class="va">YearlySalary</span><span class="op">)</span></span>
<span><span class="va">mu</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.033404</code></pre>
</div>
</div>
<p>Say we wanted to check whether 1 million was a plausible average yearly salary for a NFL player in 2019. The answer is no, it isn’t. We know the actual average salary which is 3.03 million of dollars, and this is different from 1 million.</p>
</section><section id="na.-population-data-not-available-more-common" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="na.-population-data-not-available-more-common">NA. Population data NOT available (more common)</h2>
<p>Now suppose we didn’t know anything from the previous section.</p>
<p>In most research, the data for the entire population is not available as we cannot afford to collect data on the entire population. As a consequence, we cannot compute the population parameter <span class="math inline">\(\mu\)</span>, which is <strong>unknown</strong>, and we must rely on random <strong>sampling</strong> to estimate it. It is good practice to use a sample size as large as we can afford in order to obtain good precision.</p>
<p>Let’s pretend for now that we don’t have the entire NFL population data, and are only able to collect data for 50 players. Fortunately someone else did it for us: they chose 50 players at random and interviewed them to find out their salary. The sample data are:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nfl_sample</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/NFLSample2019.csv"</span><span class="op">)</span></span>
<span><span class="va">nfl_sample</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 5
   Player          Position Team       TotalMoney YearlySalary
   &lt;chr&gt;           &lt;chr&gt;    &lt;chr&gt;           &lt;dbl&gt;        &lt;dbl&gt;
 1 Najee Goode     43OLB    Jaguars         0.805        0.805
 2 Jack Crawford   43DT     Falcons         9.9          2.48 
 3 Tra Carson      RB       Lions           1.23         0.615
 4 Jordan Richards S        Ravens          0.805        0.805
 5 Desmond Trufant CB       Falcons        68.8         13.8  
 6 Alex Anzalone   43OLB    Saints          3.47         0.866
 7 Trey Burton     TE       Bears          32            8    
 8 Josh Martin     43DE     Saints          0.805        0.805
 9 Lavonte David   ILB      Buccaneers     50.2         10.0  
10 Maliek Collins  43DT     Cowboys         3.55         0.888
# ℹ 40 more rows</code></pre>
</div>
</div>
<p>We estimate the <strong>unknown</strong> population mean salary (what we are interested in) with the sample mean salary <span class="math inline">\(\bar x\)</span>, which we can compute from the obtained sample. The sample mean salary represents our “best guess” of the population mean salary.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">xbar</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">nfl_sample</span><span class="op">$</span><span class="va">YearlySalary</span><span class="op">)</span></span>
<span><span class="va">xbar</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.35882</code></pre>
</div>
</div>
<p>The average salary in the sample of 50 NFL players is 3.36 million dollars.</p>
<p>Without knowledge of the full data, we would say that we estimate the average salary of an NFL player in the year 2019 to be 3.36 million dollars.</p>
<p>However, we know that if we had collected a different sample, the sample mean would be a different number from 3.36 as it varies from sample to sample.</p>
<p>We do not want to report a single number as the estimate, as we know that our estimate will almost certainly differ from the true value of the population parameter. We probably want to be cautious and report a <strong>range of plausible values</strong> for the parameter, known as <strong>confidence interval (CI)</strong>, which is more likely to capture the true value of the parameter. See the following image for a summary of the idea:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="https://d33wubrfki0l68.cloudfront.net/45f6d2e16255dbcb42de86336e1e49ef732aa5da/8bcd0/images/shutterstock/point_estimate_vs_conf_int.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Source: moderndive.com</figcaption></figure>
</div>
</div>
</div>
<p><br></p>
<p>To get the range of plausible values, we will use the fact that in a Normal distribution 95% of the values are roughly between the mean - 2 SD and the mean + 2 SD.</p>
<p>We know that the sample mean follows a normal distribution, and we also know that the standard deviation of the sampling distribution of the mean is also known as the <strong>standard error</strong> (SE).</p>
<p>However, we cannot obtain the standard error of the mean as we do not have the data on the entire population. If we used the formula for the standard error, we would need to know the population standard deviation <span class="math inline">\(\sigma\)</span> (which we don’t):</p>
<p><span class="math display">\[
SE = \frac{\sigma}{\sqrt{n}}
\quad \text{where}
\quad \sigma = \text{pop. standard deviation}
\]</span></p>
<p>This week we will learn how to estimate the standard error of a statistic when we only have one sample.</p>
</section><section id="confidence-intervals" class="level2" data-number="2"><h2 data-number="2" class="anchored" data-anchor-id="confidence-intervals">
<span class="header-section-number">2</span> Confidence intervals</h2>
<p>This section investigates how to obtain the standard error and construct a confidence interval when only one sample is available.</p>
<p>Let <span class="math inline">\(\mu\)</span> be the population mean and <span class="math inline">\(\sigma\)</span> the population standard deviation. In <a href="1_11_sampling.html">Week 11 of semester 1</a> you saw that</p>
<ol type="1">
<li>the sample mean <span class="math inline">\(\bar X\)</span> follows a normal distribution;</li>
<li>its average <span class="math inline">\(\mu_{\overline X}\)</span> is equal to the unknown population mean <span class="math inline">\(\mu\)</span>;</li>
<li>its standard deviation is equal to <span class="math inline">\(\sigma_{\overline X} = SE = \sigma / \sqrt{n}\)</span>, also known as the standard error of the mean.</li>
</ol>
<p><span class="math display">\[
\bar X \sim N(\mu_{\overline{X}}, \sigma_{\overline{X}}) \quad \text{where}
\quad \begin{cases}
\mu_{\overline{X}} = \mu \\
\sigma_{\overline{X}} = SE = \frac{\sigma}{\sqrt{n}}
\end{cases}
\]</span></p>
<p>Property 1 tells us that if we computed the sample mean on many samples from the population and created a histogram, this would be bell-shaped like a Normal distribution. So, <strong>the sampling distribution of the mean is a Normal distribution.</strong></p>
<p>Property 2 tells us that the sampling distribution of the mean is centred at the unknown population mean <span class="math inline">\(\mu\)</span>. So, on average our sample means are close to the true but unknown population mean.</p>
<p>Property 3 tells us that the spread (standard deviation) of the sampling distribution is <span class="math inline">\(\sigma_{\overline X} = \sigma / \sqrt{n}\)</span>. The larger the sample size, the smaller the standard error, and the more precise the estimate is.</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Finding the central 95% probability</strong></p>
<p>Recall this image for a generic <span class="math inline">\(X \sim N(\mu, \sigma)\)</span> distribution:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/prob/normal_rule.png" class="img-fluid figure-img" style="width:85.0%"></p>
</figure>
</div>
</div>
</div>
<p>The middle 95% probability lies between the values <span class="math inline">\(x = \mu - 2 \sigma\)</span> and <span class="math inline">\(x = \mu + 2 \sigma\)</span>.</p>
<p>To be more precise, the values between which lies the central 95% probability are those quantiles cutting 0.025 probability to the left and 0.025 probability to the right (= 0.975 to the left).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">0.975</span><span class="op">)</span><span class="op">)</span>   <span class="co"># note that: 0.975 - 0.025 = 0.95</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.959964  1.959964</code></pre>
</div>
</div>
<p>Meaning that 95% of the values in a normal distribution are between</p>
<p><span class="math display">\[
[\mu - 1.96 \cdot \sigma, \
\mu + 1.96 \cdot \sigma]
\]</span></p>
</div>
</div>
</div>
<p>If we replace <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> with <span class="math inline">\(\mu_{\overline X}\)</span> and <span class="math inline">\(\sigma_{\overline X}\)</span> in the interval above, we obtain the corresponding 95% confidence interval for the sample mean <span class="math inline">\(\bar X \sim N(\mu_{\overline X}, \sigma_{\overline X})\)</span>.</p>
<p>That is, roughly 95% of the values are between</p>
<p><span class="math display">\[
[\mu_{\overline X} - 1.96 \cdot \sigma_{\overline X},\
\mu_{\overline X} + 1.96 \cdot \sigma_{\overline X}]
\]</span></p>
<p>Substituting the formula for the <span class="math inline">\(SE = \sigma_{\overline X} = \sigma / \sqrt{n}\)</span>, we know that 95% of the values are roughly between:</p>
<p><span class="math display">\[
\left[
\mu - 1.96 \cdot \frac{\sigma}{\sqrt n},\  
\mu + 1.96 \cdot \frac{\sigma}{\sqrt n}
\right]
\]</span></p>
<p>The formula above is the 95% confidence interval for the population mean.</p>
<p><br></p>
<p>There is one problem though… The confidence interval depends on <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>, the population mean salary and population standard deviation.</p>
<p>When we don’t have the entire population data and we can only afford ONE sample, we do not have <span class="math inline">\(\mu\)</span> and we also do not have <span class="math inline">\(\sigma\)</span>. We estimated <span class="math inline">\(\mu\)</span> with the sample mean <span class="math inline">\(\bar x\)</span>, and we must also estimate <span class="math inline">\(\sigma\)</span> with the sample standard deviation <span class="math inline">\(s\)</span>.</p>
<p>The standard error becomes:</p>
<p><span class="math display">\[
SE = \frac{s}{\sqrt n} \qquad \text{where } s = \text{sample standard deviation}
\]</span></p>
<p>and the confidence interval for the population mean becomes:</p>
<p><span class="math display">\[
\left[
\bar x - 1.96 \cdot \frac{s}{\sqrt n},\  
\bar x + 1.96 \cdot \frac{s}{\sqrt n}
\right]
\]</span></p>
<div class="callout callout-style-simple callout-warning">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>However, that formula is not quite right!</strong> We estimated the unknown <span class="math inline">\(\sigma\)</span> with the sample standard deviation <span class="math inline">\(s\)</span>. This brings an extra element of uncertainty.</p>
<p>Because we are unsure about the actual value of the population standard deviation, the resulting distribution is no longer Normal, but a distribution that is more “uncertain” and places higher probability in the tails of the distribution, meaning that we have a wider range of values that we can observe (hence higher uncertainty).</p>
<p>When the population standard deviation is unknown, the sample mean follows a <strong>t-distribution.</strong></p>
</div>
</div>
</div>
<p>The t-distribution depends on a number called the <strong>degrees of freedom</strong> (DF) of the distribution, which is related to the sample size. The degrees of freedom is equal to the sample size - 1: <span class="math display">\[
df = n - 1
\]</span> Because of this, we refer to the distribution of the sample mean as the <span class="math inline">\(t(n-1)\)</span> distribution, and we write the degrees of freedom within parentheses.</p>
<p>t-distributions with smaller degrees of freedom (corresponding to smaller samples) put more probability on the tails of the distribution, meaning more uncertainty. As the degree of freedom increases, the t-distribution is indistinguishable from the Normal distribution, and this happens approximately with df <span class="math inline">\(\geq\)</span> 30.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="rd2_01_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>Because the distribution has changed, we need to find the new values in between which lies 95% of the probability. These are no longer -1.96 and 1.96 and will vary with the distribution.</p>
<p>Consider a sample of size <span class="math inline">\(n = 10\)</span>. The corresponding df = 10 - 1 = 9. The values in between which lies the middle 0.95 probability are:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># quantiles of a t-distribution with 9 df</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">0.975</span><span class="op">)</span>, df <span class="op">=</span> <span class="fl">9</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.262157  2.262157</code></pre>
</div>
</div>
<p>These two values have, respectively, a probability of 0.025 to the left and 0.025 to the right.</p>
<p>Hence, for a t(9) distribution, 95% of the values are between:</p>
<p><span class="math display">\[
\left[
\bar x - 2.26 \cdot \frac{s}{\sqrt n}
,\  
\bar x + 2.26 \cdot \frac{s}{\sqrt n}
\right]
\]</span></p>
<p>In general, we denote the two quantiles of the t-distribution as <span class="math inline">\(-t^*\)</span> and <span class="math inline">\(+t^*\)</span>, so the interval is written in general as:</p>
<p><span class="math display">\[
\left[
\bar x - t^* \cdot \frac{s}{\sqrt n}
,\  
\bar x + t^* \cdot \frac{s}{\sqrt n}
\right]
\]</span></p>
<section id="example" class="level3" data-number="2.1"><h3 data-number="2.1" class="anchored" data-anchor-id="example">
<span class="header-section-number">2.1</span> Example</h3>
<p>Consider again the sample of 50 NFL players. We want to report not only an estimate for the mean salary, but also a range of plausible values.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nfl_sample</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 50 × 5
   Player          Position Team       TotalMoney YearlySalary
   &lt;chr&gt;           &lt;chr&gt;    &lt;chr&gt;           &lt;dbl&gt;        &lt;dbl&gt;
 1 Najee Goode     43OLB    Jaguars         0.805        0.805
 2 Jack Crawford   43DT     Falcons         9.9          2.48 
 3 Tra Carson      RB       Lions           1.23         0.615
 4 Jordan Richards S        Ravens          0.805        0.805
 5 Desmond Trufant CB       Falcons        68.8         13.8  
 6 Alex Anzalone   43OLB    Saints          3.47         0.866
 7 Trey Burton     TE       Bears          32            8    
 8 Josh Martin     43DE     Saints          0.805        0.805
 9 Lavonte David   ILB      Buccaneers     50.2         10.0  
10 Maliek Collins  43DT     Cowboys         3.55         0.888
# ℹ 40 more rows</code></pre>
</div>
</div>
<p>We need a few elements according to our discussion above:</p>
<ul>
<li>
<span class="math inline">\(\bar{x}\)</span>, the sample mean which we already computed before</li>
<li>
<span class="math inline">\(s\)</span>, the sample standard deviation</li>
<li>
<span class="math inline">\(n\)</span>, the sample size</li>
<li>the new multipliers to the SD based on the <span class="math inline">\(t(n-1)\)</span> distribution</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">xbar</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.35882</code></pre>
</div>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">s</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">nfl_sample</span><span class="op">$</span><span class="va">YearlySalary</span><span class="op">)</span></span>
<span><span class="va">s</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.311738</code></pre>
</div>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">nfl_sample</span><span class="op">)</span></span>
<span><span class="va">n</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50</code></pre>
</div>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">qt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.025</span>, <span class="fl">0.975</span><span class="op">)</span>, df <span class="op">=</span> <span class="va">n</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.009575  2.009575</code></pre>
</div>
</div>
<p>The formula to use:</p>
<p><span class="math display">\[
\left[
\bar x - 2.01 \cdot \frac{s}{\sqrt n}
,\  
\bar x + 2.01 \cdot \frac{s}{\sqrt n}
\right]
\]</span></p>
<p>In R:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">xbar</span> <span class="op">-</span> <span class="fl">2.01</span> <span class="op">*</span> <span class="op">(</span><span class="va">s</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.133179</code></pre>
</div>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">xbar</span> <span class="op">+</span> <span class="fl">2.01</span> <span class="op">*</span> <span class="op">(</span><span class="va">s</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.584461</code></pre>
</div>
</div>
<p>The 95% confidence interval is then [2.13, 4.58] million dollars. We would write this up as:</p>
<div class="callout callout-style-simple callout-tip">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>We are 95% confident that the average salary of a NFL player in 2019 is between 2.13 and 4.58 million dollars.</p>
</div>
</div>
</div>
</section><section id="interpreting-a-confidence-interval" class="level3" data-number="2.2"><h3 data-number="2.2" class="anchored" data-anchor-id="interpreting-a-confidence-interval">
<span class="header-section-number">2.2</span> Interpreting a confidence interval?</h3>
<p>If we were to do this whole process over and over again:</p>
<ul>
<li>take a random sample of size <span class="math inline">\(n\)</span>;</li>
<li>construct a 95% confidence interval.</li>
</ul>
<p>then about 95% of the confidence intervals we created would contain the population mean. In turn, this also means that 5% of those intervals will not.</p>
<p>So if we did this 100 times, we would expect about five of our 95% confidence intervals to not contain the true population mean.</p>
<p>And if we had been constructing 80% confidence intervals instead, we would expect roughly 80 of them to contain the population mean.</p>
<div class="callout callout-style-simple callout-warning">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>When we have constructed a single interval, we do not say that the interval contains the population mean with probability of 95%, as this is wrong. We can only say that we are 95% confident it contains the population mean.</p>
<p>We speak about probability when we refer to a collection of confidence intervals. For example, if we have constructed one hundred 95% confidence intervals, then there is a probability of 0.95 that they (collectively) will contain the population parameter.</p>
<p>On the contrary, when we refer to just <strong>one</strong> confidence interval, we speak about <strong>confidence</strong>.</p>
</div>
</div>
</div>
</section></section><section id="glossary" class="level2" data-number="3"><h2 data-number="3" class="anchored" data-anchor-id="glossary">
<span class="header-section-number">3</span> Glossary</h2>
<ul>
<li>
<em>Population.</em> The entire collection of units of interest.</li>
<li>
<em>Sample.</em> A subset of the entire population.</li>
<li>
<em>Parameter.</em> A fixed but typically unknown quantity describing the population.</li>
<li>
<em>Statistic.</em> A quantity computed on a sample.</li>
<li>
<em>Sampling distribution.</em> The distribution of the values that a statistic takes on different samples of the same size and from the same population.</li>
<li>
<em>Standard error.</em> The standard error of a statistic is the standard deviation of the sampling distribution of the statistic.</li>
<li>
<em>Confidence interval (CI).</em> A range of plausible values around an estimate (e.g., a sample statistic), taking into account uncertainty in the statistic (e.g., sampling variability)</li>
<li>
<em>Confidence level.</em> The percentage of confidence intervals which will contain the true population parameter <strong>in the long run</strong> (i.e., if you sampled the population and constructed confidence intervals many times over). The proportion of all samples whose intervals contain the true parameter.</li>
</ul>


</section><a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2019-2024 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>