<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Types of relationships (functions) | Data Analysis for Psychology in R 1</title>
  <meta name="description" content="This book contains the lab materials for DAPR-1 at UoE." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Types of relationships (functions) | Data Analysis for Psychology in R 1" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book contains the lab materials for DAPR-1 at UoE." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Types of relationships (functions) | Data Analysis for Psychology in R 1" />
  
  <meta name="twitter:description" content="This book contains the lab materials for DAPR-1 at UoE." />
  

<meta name="author" content="Department of Psychology, The University of Edinburgh" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap-relationships.html"/>
<link rel="next" href="chap-probability-theory.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><div style="margin-top:-13px; font-size: 25px; color: #0F4C81;"><left><b>DAPR1</b></left></div></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course overview</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-description"><i class="fa fa-check"></i>Course description</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#team"><i class="fa fa-check"></i>Team</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#schedule"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#textbook"><i class="fa fa-check"></i>Textbook</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html"><i class="fa fa-check"></i>Intro to R, Rstudio, and data in R</a><ul>
<li class="chapter" data-level="0.1" data-path="chap-intro.html"><a href="chap-intro.html#introducing-r-and-rstudio"><i class="fa fa-check"></i><b>0.1</b> Introducing R and Rstudio</a><ul>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#installing"><i class="fa fa-check"></i>Installing</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#first-look-at-rstudio"><i class="fa fa-check"></i>First look at Rstudio</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#r-as-a-calculator"><i class="fa fa-check"></i>R as a calculator</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#r-as-a-calculator-with-a-memory"><i class="fa fa-check"></i>R as a calculator with a memory</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#rscripts-and-rmarkdown"><i class="fa fa-check"></i>Rscripts and Rmarkdown</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#recap"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
<li class="chapter" data-level="0.2" data-path="chap-intro.html"><a href="chap-intro.html#take-a-breather"><i class="fa fa-check"></i><b>0.2</b> Take a breather</a></li>
<li class="chapter" data-level="0.3" data-path="chap-intro.html"><a href="chap-intro.html#starting-a-new-.rmd-document"><i class="fa fa-check"></i><b>0.3</b> Starting a new .Rmd document</a><ul>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#using-an-r-package"><i class="fa fa-check"></i>Using an R package</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#writing"><i class="fa fa-check"></i>Writing</a></li>
</ul></li>
<li class="chapter" data-level="0.4" data-path="chap-intro.html"><a href="chap-intro.html#data-in-r"><i class="fa fa-check"></i><b>0.4</b> Data in R</a><ul>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#storing-data-in-r-sequences-vectors-of-values"><i class="fa fa-check"></i>Storing data in R: Sequences (“Vectors”) of values</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#reading-data-into-r"><i class="fa fa-check"></i>Reading data into R</a></li>
</ul></li>
<li class="chapter" data-level="0.5" data-path="chap-intro.html"><a href="chap-intro.html#compiling-a-.rmd-document"><i class="fa fa-check"></i><b>0.5</b> Compiling a .Rmd document</a></li>
<li class="chapter" data-level="0.6" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>0.6</b> Glossary</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="chap-data-types.html"><a href="chap-data-types.html"><i class="fa fa-check"></i><b>1</b> Types of data</a><ul>
<li class="chapter" data-level="1.1" data-path="chap-data-types.html"><a href="chap-data-types.html#accessing-subsections-of-data"><i class="fa fa-check"></i><b>1.1</b> Accessing subsections of data</a><ul>
<li class="chapter" data-level="" data-path="chap-data-types.html"><a href="chap-data-types.html#accessing-by-a-condition"><i class="fa fa-check"></i>Accessing by a condition</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="chap-data-types.html"><a href="chap-data-types.html#editing-subsections-of-data"><i class="fa fa-check"></i><b>1.2</b> Editing subsections of data</a><ul>
<li class="chapter" data-level="" data-path="chap-data-types.html"><a href="chap-data-types.html#changing-specific-entries"><i class="fa fa-check"></i>Changing specific entries</a></li>
<li class="chapter" data-level="" data-path="chap-data-types.html"><a href="chap-data-types.html#changing-entries-by-a-condition"><i class="fa fa-check"></i>Changing entries by a condition</a></li>
<li class="chapter" data-level="" data-path="chap-data-types.html"><a href="chap-data-types.html#changing-a-variable"><i class="fa fa-check"></i>Changing a variable</a></li>
<li class="chapter" data-level="" data-path="chap-data-types.html"><a href="chap-data-types.html#removing-rows-or-columns"><i class="fa fa-check"></i>Removing rows or columns</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="chap-data-types.html"><a href="chap-data-types.html#different-types-of-data"><i class="fa fa-check"></i><b>1.3</b> Different types of data</a></li>
<li class="chapter" data-level="1.4" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>1.4</b> Glossary</a></li>
<li class="chapter" data-level="1.5" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>1.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-categorical.html"><a href="chap-categorical.html"><i class="fa fa-check"></i><b>2</b> Handling categorical data</a><ul>
<li class="chapter" data-level="2.1" data-path="chap-categorical.html"><a href="chap-categorical.html#data-exploration"><i class="fa fa-check"></i><b>2.1</b> Data Exploration</a></li>
<li class="chapter" data-level="2.2" data-path="chap-categorical.html"><a href="chap-categorical.html#unordered-categorical-nominal-data"><i class="fa fa-check"></i><b>2.2</b> Unordered Categorical (Nominal) Data</a><ul>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#frequency-table"><i class="fa fa-check"></i>Frequency table</a></li>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#central-tendency"><i class="fa fa-check"></i>Central tendency</a></li>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#relative-frequencies"><i class="fa fa-check"></i>Relative frequencies</a></li>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#visualising"><i class="fa fa-check"></i>Visualising</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="chap-categorical.html"><a href="chap-categorical.html#ordered-categorical-ordinal-data"><i class="fa fa-check"></i><b>2.3</b> Ordered Categorical (Ordinal) Data</a><ul>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#frequency-table-1"><i class="fa fa-check"></i>Frequency table</a></li>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#central-tendency-1"><i class="fa fa-check"></i>Central tendency</a></li>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#cumulative-percentages-quartiles"><i class="fa fa-check"></i>Cumulative percentages, Quartiles</a></li>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#visualising-1"><i class="fa fa-check"></i>Visualising</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>2.4</b> Glossary</a></li>
<li class="chapter" data-level="2.5" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>2.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-numeric.html"><a href="chap-numeric.html"><i class="fa fa-check"></i><b>3</b> Handling numeric data</a><ul>
<li class="chapter" data-level="3.1" data-path="chap-categorical.html"><a href="chap-categorical.html#central-tendency"><i class="fa fa-check"></i><b>3.1</b> Central tendency</a><ul>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#mode-and-median-revisited"><i class="fa fa-check"></i>Mode and median revisited</a></li>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#mean"><i class="fa fa-check"></i>Mean</a></li>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#summarising-variables"><i class="fa fa-check"></i>Summarising variables</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="chap-numeric.html"><a href="chap-numeric.html#spread"><i class="fa fa-check"></i><b>3.2</b> Spread</a><ul>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#interquartile-range"><i class="fa fa-check"></i>Interquartile range</a></li>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#variance"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#standard-deviation"><i class="fa fa-check"></i>Standard deviation</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="chap-categorical.html"><a href="chap-categorical.html#visualising"><i class="fa fa-check"></i><b>3.3</b> Visualising</a><ul>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#boxplots"><i class="fa fa-check"></i>Boxplots</a></li>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#histograms"><i class="fa fa-check"></i>Histograms</a></li>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#density-curves"><i class="fa fa-check"></i>Density curves</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="chap-numeric.html"><a href="chap-numeric.html#skew"><i class="fa fa-check"></i><b>3.4</b> Skew</a></li>
<li class="chapter" data-level="3.5" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>3.5</b> Glossary</a></li>
<li class="chapter" data-level="3.6" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>3.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-relationships.html"><a href="chap-relationships.html"><i class="fa fa-check"></i><b>4</b> Visualising and describing relationships</a><ul>
<li class="chapter" data-level="4.1" data-path="chap-relationships.html"><a href="chap-relationships.html#outcome-vs-explanatory"><i class="fa fa-check"></i><b>4.1</b> Outcome vs Explanatory</a></li>
<li class="chapter" data-level="4.2" data-path="chap-relationships.html"><a href="chap-relationships.html#numeric-and-categorical"><i class="fa fa-check"></i><b>4.2</b> Numeric and Categorical</a><ul>
<li class="chapter" data-level="" data-path="chap-relationships.html"><a href="chap-relationships.html#visualising---colours"><i class="fa fa-check"></i>Visualising - Colours</a></li>
<li class="chapter" data-level="" data-path="chap-relationships.html"><a href="chap-relationships.html#visualising---facets"><i class="fa fa-check"></i>Visualising - Facets</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="chap-relationships.html"><a href="chap-relationships.html#numeric-and-numeric"><i class="fa fa-check"></i><b>4.3</b> Numeric and Numeric</a><ul>
<li class="chapter" data-level="" data-path="chap-relationships.html"><a href="chap-relationships.html#covariance"><i class="fa fa-check"></i>Covariance</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>4.4</b> Glossary</a></li>
<li class="chapter" data-level="4.5" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-functions.html"><a href="chap-functions.html"><i class="fa fa-check"></i><b>5</b> Types of relationships (functions)</a><ul>
<li class="chapter" data-level="5.1" data-path="chap-functions.html"><a href="chap-functions.html#functions"><i class="fa fa-check"></i><b>5.1</b> Functions</a><ul>
<li class="chapter" data-level="" data-path="chap-functions.html"><a href="chap-functions.html#linear-functions"><i class="fa fa-check"></i>Linear functions</a></li>
<li class="chapter" data-level="" data-path="chap-functions.html"><a href="chap-functions.html#non-linear-functions"><i class="fa fa-check"></i>Non-linear functions</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="chap-functions.html"><a href="chap-functions.html#transformations"><i class="fa fa-check"></i><b>5.2</b> Transformations</a></li>
<li class="chapter" data-level="5.3" data-path="chap-functions.html"><a href="chap-functions.html#centering-and-standardisation"><i class="fa fa-check"></i><b>5.3</b> Centering and Standardisation</a></li>
<li class="chapter" data-level="5.4" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>5.4</b> Glossary</a></li>
<li class="chapter" data-level="5.5" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>5.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html"><i class="fa fa-check"></i><b>6</b> Basics of probability theory</a><ul>
<li class="chapter" data-level="" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#where-are-we-going-to"><i class="fa fa-check"></i>Where are we going to?</a></li>
<li class="chapter" data-level="6.1" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section"><i class="fa fa-check"></i><b>6.1</b> Section</a></li>
<li class="chapter" data-level="6.2" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section-1"><i class="fa fa-check"></i><b>6.2</b> Section</a></li>
<li class="chapter" data-level="6.3" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>6.3</b> Glossary</a></li>
<li class="chapter" data-level="6.4" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>6.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-probability-rules.html"><a href="chap-probability-rules.html"><i class="fa fa-check"></i><b>7</b> Probability rules</a><ul>
<li class="chapter" data-level="7.1" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section"><i class="fa fa-check"></i><b>7.1</b> Section</a></li>
<li class="chapter" data-level="7.2" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section-1"><i class="fa fa-check"></i><b>7.2</b> Section</a></li>
<li class="chapter" data-level="7.3" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>7.3</b> Glossary</a></li>
<li class="chapter" data-level="7.4" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>7.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap-discrete-distributions.html"><a href="chap-discrete-distributions.html"><i class="fa fa-check"></i><b>8</b> Random variables &amp; distributions (discrete)</a><ul>
<li class="chapter" data-level="8.1" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section"><i class="fa fa-check"></i><b>8.1</b> Section</a></li>
<li class="chapter" data-level="8.2" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section-1"><i class="fa fa-check"></i><b>8.2</b> Section</a></li>
<li class="chapter" data-level="8.3" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>8.3</b> Glossary</a></li>
<li class="chapter" data-level="8.4" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>8.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap-continuous-distributions.html"><a href="chap-continuous-distributions.html"><i class="fa fa-check"></i><b>9</b> Random variables and distributions (continuous)</a><ul>
<li class="chapter" data-level="9.1" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section"><i class="fa fa-check"></i><b>9.1</b> Section</a></li>
<li class="chapter" data-level="9.2" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section-1"><i class="fa fa-check"></i><b>9.2</b> Section</a></li>
<li class="chapter" data-level="9.3" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>9.3</b> Glossary</a></li>
<li class="chapter" data-level="9.4" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>9.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap-sampling.html"><a href="chap-sampling.html"><i class="fa fa-check"></i><b>10</b> Sampling variability and sampling distributions</a><ul>
<li class="chapter" data-level="10.1" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section"><i class="fa fa-check"></i><b>10.1</b> Section</a></li>
<li class="chapter" data-level="10.2" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section-1"><i class="fa fa-check"></i><b>10.2</b> Section</a></li>
<li class="chapter" data-level="10.3" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>10.3</b> Glossary</a></li>
<li class="chapter" data-level="10.4" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>10.4</b> Exercises</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://www.handbooks.psy.ed.ac.uk/psychology-1a-and-1b/dapr1" target="blank">Psychology Handbooks</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis for Psychology in R 1</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap-functions" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Types of relationships (functions)</h1>
<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ul>
<li>LO1: Understand the basic principles of functions.</li>
<li>LO2: Understand concept of data transformations.</li>
<li>LO3: Understand the calculation of z-scores.</li>
</ul>
</div>
<div id="functions" class="section level2">
<h2><span class="header-section-number">5.1</span> Functions</h2>
<p>You have seen by now how to visualise the distribution of a variable, and how to visualise a relationship between two variables. Relationships between two variables can look very different, and can follow different patterns. These patterns can be expressed mathematically in the form of <strong>functions.</strong></p>
<div class="yellow">
<p><strong>Functions</strong></p>
<p>A function is a mapping between two sets of numbers (<span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>) - associating every element of <span class="math inline">\(x\)</span> with an element in <span class="math inline">\(y\)</span>.<br />
We often denote functions using the letter <span class="math inline">\(f\)</span>, in that we state that <span class="math inline">\(y = f(x)\)</span> (“y equals f of x”).</p>
<p>For example, there is a mapping between these two sets:</p>
<p><span class="math display">\[x=\begin{bmatrix} 1 \\ 2 \\ 3 \\ 4 \\ 5 \\ 6 \\ 7 \\ 8 \\ \end{bmatrix}, \qquad
y=\begin{bmatrix} 3 \\ 4 \\ 5 \\ 6 \\ 7 \\ 8 \\ 9 \\ 10 \\ \end{bmatrix}\]</span></p>
<p>And we can write this mapping as:<br />
<span class="math display">\[f(x) = x + 2\]</span></p>
<p>And we could visualise this relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>:
<img src="labs_files/figure-html/unnamed-chunk-197-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="linear-functions" class="section level3 unnumbered">
<h3>Linear functions</h3>
<p>In statistics, we often attempt to summarise the pattern that is present in the data using <em>linear functions</em>.</p>
<p>Imagine that we plant 10 trees, and measure their heights each year for 10 years. We could visualise this data (the relationship between <em>time</em> and <em>tree height</em>) on a scatterplot (we have added some lines to the plot to show which tree is which):<br />
<br>
<img src="labs_files/figure-html/unnamed-chunk-198-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We might sensibly choose to describe this pattern as a line:
<br>
<img src="labs_files/figure-html/unnamed-chunk-199-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>And in order to describe a line like this, we require two things:</p>
<ol style="list-style-type: decimal">
<li>The starting point (i.e., where it crosses the y-axis)</li>
<li>The amount it goes up every year.</li>
</ol>
<p>When we planted the trees (at year 0), they were on average about 5cm tall. So this is where our line starts.<br />
For every year, the trees grew by about 10cm on average. So we can now describe tree height <em>as a function of</em> time:<br />
<span class="math display">\[\textrm{Tree height} = 5 + (10 \times \textrm{Years})\]</span></p>
<p>We can write this in terms of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(y = f(x)\)</span>         “<span class="math inline">\(y\)</span> is some function <span class="math inline">\(f\)</span> of <span class="math inline">\(x\)</span>”</li>
<li><span class="math inline">\(f(x) = 5 + 10x\)</span>         “the function <span class="math inline">\(f\)</span> maps each value <span class="math inline">\(x_i\)</span> to <span class="math inline">\(5 + (10 \times x_i)\)</span>”</li>
</ol>
</div>
<div id="non-linear-functions" class="section level3 unnumbered">
<h3>Non-linear functions</h3>
Functions don’t have to be linear. Often, we might want to describe relationships which appear to be more complex than a straight line.<br />
For example, it is often suggested that for difficult tasks, <em>some</em> amount of stress may <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1906714/">improve performance</a> (but not too little or too much). We might think of the relationship between performance and stress as a curve (Figure <a href="chap-functions.html#fig:ydodson">5.1</a>).
<br>
<div class="figure" style="text-align: center"><span id="fig:ydodson"></span>
<img src="labs_files/figure-html/ydodson-1.png" alt="Yerkes Dodson Law" width="672" />
<p class="caption">
Figure 5.1: Yerkes Dodson Law
</p>
</div>
<p><br>
One way to describe curves is to use polynomials (<span class="math inline">\(x^2\)</span>, <span class="math inline">\(x^3\)</span>, etc.).<br />
For example, in the following two sets, <span class="math inline">\(y\)</span> can be described as <span class="math inline">\(f(x)\)</span> where <span class="math inline">\(f(x)=x^2\)</span>:</p>
<p><span class="math display">\[x=\begin{bmatrix} -5 \\ -4 \\ -3 \\ -2 \\ -1 \\ 0 \\ 1 \\ 2 \\ 3 \\ 4 \\ 5 \end{bmatrix}, \qquad
y=\begin{bmatrix} 25 \\ 16 \\ 9 \\ 4 \\ 1 \\ 0 \\ 1 \\ 4 \\ 9 \\ 16 \\ 25 \end{bmatrix}\]</span></p>
<p>and when we plot each value of <span class="math inline">\(x\)</span> against the corresponding value of <span class="math inline">\(y\)</span>:
<img src="labs_files/figure-html/unnamed-chunk-200-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="optional-begin">
Optional - the code to create the above plot<span id="opt-start-158" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-158&#39;, &#39;opt-start-158&#39;)"></span>
</div>
<div id="opt-body-158" class="optional-body" style="display: none;">
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="chap-functions.html#cb291-1"></a><span class="co"># the tibble() function can be used to create a dataframe</span></span>
<span id="cb291-2"><a href="chap-functions.html#cb291-2"></a><span class="co"># here, we create one with two variables, x and y.</span></span>
<span id="cb291-3"><a href="chap-functions.html#cb291-3"></a><span class="co"># x is the sequence from -5 to 5,</span></span>
<span id="cb291-4"><a href="chap-functions.html#cb291-4"></a><span class="co"># y is equal to x squared. </span></span>
<span id="cb291-5"><a href="chap-functions.html#cb291-5"></a><span class="co"># we save this data as &quot;poly&quot;</span></span>
<span id="cb291-6"><a href="chap-functions.html#cb291-6"></a>poly &lt;-<span class="st"> </span></span>
<span id="cb291-7"><a href="chap-functions.html#cb291-7"></a><span class="st">    </span><span class="kw">tibble</span>(</span>
<span id="cb291-8"><a href="chap-functions.html#cb291-8"></a>        <span class="dt">x =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">5</span>,<span class="op">-</span><span class="dv">4</span>,<span class="op">-</span><span class="dv">3</span>,<span class="op">-</span><span class="dv">2</span>,<span class="op">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>),</span>
<span id="cb291-9"><a href="chap-functions.html#cb291-9"></a>        <span class="dt">y =</span> x<span class="op">^</span><span class="dv">2</span></span>
<span id="cb291-10"><a href="chap-functions.html#cb291-10"></a>    )</span>
<span id="cb291-11"><a href="chap-functions.html#cb291-11"></a><span class="co"># create a plot with &quot;poly&quot;, with variable &quot;x&quot; on the x-axis,</span></span>
<span id="cb291-12"><a href="chap-functions.html#cb291-12"></a><span class="co"># and variable &quot;y&quot; on the y-axis. Add geom_points for each entry</span></span>
<span id="cb291-13"><a href="chap-functions.html#cb291-13"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> poly, <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb291-14"><a href="chap-functions.html#cb291-14"></a><span class="st">    </span><span class="kw">geom_point</span>()</span></code></pre></div>
</div>
<p class="optional-end">
</p>
</div>
</div>
<div id="transformations" class="section level2">
<h2><span class="header-section-number">5.2</span> Transformations</h2>
<p>We have seen previously how we might change all the values in a variable, for instance if we want to turn heights from centimetres to metres:</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="chap-functions.html#cb292-1"></a><span class="co"># read in the starwars dataset and assign it the name &quot;starwars2&quot;</span></span>
<span id="cb292-2"><a href="chap-functions.html#cb292-2"></a>starwars2 &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://uoepsy.github.io/data/dapr1/starwars2.csv&quot;</span>)</span>
<span id="cb292-3"><a href="chap-functions.html#cb292-3"></a></span>
<span id="cb292-4"><a href="chap-functions.html#cb292-4"></a><span class="co"># take the starwars2 dataframe %&gt;%</span></span>
<span id="cb292-5"><a href="chap-functions.html#cb292-5"></a><span class="co"># mutate it such that there is a new variable called &quot;height_m&quot;,</span></span>
<span id="cb292-6"><a href="chap-functions.html#cb292-6"></a><span class="co"># the values of which are equal to the &quot;height&quot; variable divided by 100.</span></span>
<span id="cb292-7"><a href="chap-functions.html#cb292-7"></a><span class="co"># then, select only the &quot;height&quot; and &quot;height_m&quot; columns (this is just </span></span>
<span id="cb292-8"><a href="chap-functions.html#cb292-8"></a><span class="co"># to make it easier to see without all the other variables)</span></span>
<span id="cb292-9"><a href="chap-functions.html#cb292-9"></a>starwars2 <span class="op">%&gt;%</span></span>
<span id="cb292-10"><a href="chap-functions.html#cb292-10"></a><span class="st">    </span><span class="kw">mutate</span>(</span>
<span id="cb292-11"><a href="chap-functions.html#cb292-11"></a>        <span class="dt">height_m =</span> height<span class="op">/</span><span class="dv">100</span></span>
<span id="cb292-12"><a href="chap-functions.html#cb292-12"></a>    ) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb292-13"><a href="chap-functions.html#cb292-13"></a><span class="st">    </span><span class="kw">select</span>(height, height_m)</span></code></pre></div>
<pre><code>## # A tibble: 75 x 2
##    height height_m
##     &lt;dbl&gt;    &lt;dbl&gt;
##  1    172     1.72
##  2    167     1.67
##  3     96     0.96
##  4    202     2.02
##  5    150     1.5 
##  6    178     1.78
##  7    165     1.65
##  8     97     0.97
##  9    183     1.83
## 10    182     1.82
## # … with 65 more rows</code></pre>
<p>What we have done here, can be described as a <strong>transformation</strong>, in that we have applied a mathematical <strong>function</strong> to the values in the <em>height</em> variable.</p>
<div class="yellow">
<p><strong>Transformation</strong></p>
<p>Data transformation is when we apply a deterministic function to map each value of a variable to a transformed value.<br />
We transform for various reasons. For instance, we can use it to change the units we are interpreting (e.g., <em>cm</em> to <em>m</em>), or to change the shape of a distribution (e.g., make it less skewed).</p>
</div>
<p>We could even plot the heights in cm and heights in m against one another (note what units are on each axis):
<img src="labs_files/figure-html/unnamed-chunk-203-1.png" width="672" style="display: block; margin: auto;" />
<br>
The relationship between a variable and a transformed variable need be linear, for example, log transformation:
<br>
<img src="labs_files/figure-html/unnamed-chunk-204-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="optional-begin">
Optional: Logarithms and Natural Logarithms<span id="opt-start-159" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-159&#39;, &#39;opt-start-159&#39;)"></span>
</div>
<div id="opt-body-159" class="optional-body" style="display: none;">
<div class="yellow">
<p><strong>Logarithm</strong></p>
<p>A <strong>logarithm</strong> (log) is the power to which a number must be raised in order to get some other number.<br />
Take as examples <span class="math inline">\(10^2\)</span> and <span class="math inline">\(10^3\)</span>:</p>
<p><span class="math display">\[
10^2 = 100 \qquad \Longleftrightarrow \qquad Log_{10} (100) = 2 \\
10^3 = 1000 \qquad \Longleftrightarrow \qquad Log_{10} (1000) = 3 \\
\]</span></p>
<p>We refer to <span class="math inline">\(Log_{10}\)</span> as “Log base 10”.</p>
</div>
<hr />
<div class="yellow">
<p><strong>Natural log</strong></p>
<p>A special case of the logarithm is referred to as the <strong>natural logarithm</strong>, and is denoted by <span class="math inline">\(ln\)</span> or <span class="math inline">\(log_e\)</span>, where <span class="math inline">\(e = 2.718281828459...\)</span></p>
<p><span class="math inline">\(e\)</span> is a special number for which <span class="math inline">\(log_e(e) = 1\)</span>.</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="chap-functions.html#cb294-1"></a><span class="co"># Natural logarithm of e is 1:</span></span>
<span id="cb294-2"><a href="chap-functions.html#cb294-2"></a><span class="kw">log</span>(<span class="fl">2.718281828459</span>, <span class="dt">base =</span> <span class="fl">2.718281828459</span>)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
</div>
</div>
<p class="optional-end">
</p>
</div>
<div id="centering-and-standardisation" class="section level2">
<h2><span class="header-section-number">5.3</span> Centering and Standardisation</h2>
<p>Recall our dataset from Chapter <a href="chap-numeric.html#chap-numeric">3</a>, in which we had data on 120 participants’ IQ scores (measured on the Wechsler Adult Intelligence Scale, WAIS), their ages, and their scores on 2 other tests. We know how to calculate the mean and standard deviation of the IQ scores:</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="chap-functions.html#cb296-1"></a><span class="co"># read in the data</span></span>
<span id="cb296-2"><a href="chap-functions.html#cb296-2"></a>wechsler &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://uoepsy.github.io/data/dapr1/wechsler.csv&quot;</span>)</span>
<span id="cb296-3"><a href="chap-functions.html#cb296-3"></a></span>
<span id="cb296-4"><a href="chap-functions.html#cb296-4"></a><span class="co"># calculate the mean and sd of IQs</span></span>
<span id="cb296-5"><a href="chap-functions.html#cb296-5"></a>wechsler <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb296-6"><a href="chap-functions.html#cb296-6"></a><span class="st">  </span><span class="kw">summarise</span>(</span>
<span id="cb296-7"><a href="chap-functions.html#cb296-7"></a>    <span class="dt">mean_iq =</span> <span class="kw">mean</span>(iq),</span>
<span id="cb296-8"><a href="chap-functions.html#cb296-8"></a>    <span class="dt">sd_iq =</span> <span class="kw">sd</span>(iq)</span>
<span id="cb296-9"><a href="chap-functions.html#cb296-9"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   mean_iq sd_iq
##     &lt;dbl&gt; &lt;dbl&gt;
## 1    99.3  15.4</code></pre>
<p>Two very useful transformations we can apply to a variable are <strong>centering</strong> and <strong>standardisation</strong>.</p>
<ol style="list-style-type: decimal">
<li><strong>Centering</strong> A transformation which re-expresses each value as the distance from a given number (e.g., the mean).<br />
</li>
<li><strong>Standardising</strong> A transformation which re-expresses each value as the distance from the mean <em>in units of standard deviations.</em></li>
</ol>
<div class="yellow">
<p><strong>Mean-centering</strong></p>
<p>To <strong>Mean-center</strong> a variable, we simply subtract the mean from each value, <span class="math inline">\(x_i - \bar{x}\)</span>:
<span class="math display">\[
\textrm{raw IQ} = \begin{bmatrix} 71 \\ 103 \\ 74 \\ 108 \\ 118 \\ 129 \\ ... \end{bmatrix}, \qquad
\textrm{mean centered IQ} = \begin{bmatrix} 71-99.3 \\ 103-99.3 \\ 74-99.3 \\ 108-99.3 \\ 118-99.3 \\ 129-99.3 \\ ... \end{bmatrix} = \begin{bmatrix} -28.3 \\ 3.7 \\ -25.3 \\ 8.7 \\ 18.7 \\ 29.7 \\ ... \end{bmatrix}
\]</span></p>
</div>
<p>To mean-center in R, we can simply add a new variable using <code>mutate()</code> and subtract the mean IQ from the IQ variable:</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="chap-functions.html#cb298-1"></a><span class="co"># Take the &quot;wechsler&quot; dataframe, and mutate it,</span></span>
<span id="cb298-2"><a href="chap-functions.html#cb298-2"></a><span class="co"># such that there is a variable called &quot;iq_meancenter&quot; for which</span></span>
<span id="cb298-3"><a href="chap-functions.html#cb298-3"></a><span class="co"># the entries are equal to the &quot;iq&quot; variable entries minus the </span></span>
<span id="cb298-4"><a href="chap-functions.html#cb298-4"></a><span class="co"># mean of the &quot;iq&quot; variable</span></span>
<span id="cb298-5"><a href="chap-functions.html#cb298-5"></a>wechsler <span class="op">%&gt;%</span></span>
<span id="cb298-6"><a href="chap-functions.html#cb298-6"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb298-7"><a href="chap-functions.html#cb298-7"></a>    <span class="dt">iq_meancenter =</span> iq <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(iq)</span>
<span id="cb298-8"><a href="chap-functions.html#cb298-8"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 120 x 6
##    participant    iq   age test1 test2 iq_meancenter
##    &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;         &lt;dbl&gt;
##  1 ppt_1          71    27    46    50        -28.3 
##  2 ppt_2         103    38    42    29          3.67
##  3 ppt_3          74    20    50    77        -25.3 
##  4 ppt_4         108    46    50    62          8.67
##  5 ppt_5         118    45    60    29         18.7 
##  6 ppt_6         129    33    45    45         29.7 
##  7 ppt_7         103    49    42    41          3.67
##  8 ppt_8         120    27    63    33         20.7 
##  9 ppt_9          96    37    53    44         -3.33
## 10 ppt_10         80    26    53    21        -19.3 
## # … with 110 more rows</code></pre>
<div class="yellow">
<p><strong>Standardisation</strong></p>
<p>When we <strong>standardise</strong> a variable, we call the transformed values <strong>z-scores</strong>. To transform a given value <span class="math inline">\(x_i\)</span> into a <strong>z-score</strong>, we simply calculate the distance from <span class="math inline">\(x_i\)</span> to the mean, <span class="math inline">\(\bar{x}\)</span>, and divide this by the standard deviation, <span class="math inline">\(s\)</span></p>
<p><span class="math display">\[
z = \frac{x_i - \bar{x}}{s}
\]</span></p>
<p>So for each of the <em>raw</em> IQ scores, we can transform them to <strong>z-scores</strong> by subtracting the mean and then dividing by the standard deviation. The resulting values tell us how low/high each participant’s IQ score is compared to observed distribution of scores:<br />
<span class="math display">\[
\textrm{raw IQ} = \begin{bmatrix} 71 \\ 103 \\ 74 \\ 108 \\ 118 \\ 129 \\ ... \end{bmatrix}, \qquad
\textrm{standardised IQ} = \begin{bmatrix} \frac{71-99.3}{15.43} \\ \frac{103-99.3}{15.43} \\ \frac{74-99.3}{15.43} \\ \frac{108-99.3}{15.43} \\ \frac{118-99.3}{15.43} \\ \frac{129-99.3}{15.43} \\ ... \end{bmatrix} = \begin{bmatrix} -1.84 \\ 0.238 \\ -1.64 \\ 0.562 \\ 1.21 \\ 1.92 \\ ... \end{bmatrix}
\]</span></p>
</div>
<p>We can achieve this in R either by manually performing the calculation:</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="chap-functions.html#cb300-1"></a><span class="co"># Take the &quot;wechsler&quot; dataframe, and mutate it,</span></span>
<span id="cb300-2"><a href="chap-functions.html#cb300-2"></a><span class="co"># such that there is a variable called &quot;iq_z&quot; for which</span></span>
<span id="cb300-3"><a href="chap-functions.html#cb300-3"></a><span class="co"># the entries are equal to the &quot;iq&quot; variable entries minus the mean of the &quot;iq&quot;</span></span>
<span id="cb300-4"><a href="chap-functions.html#cb300-4"></a><span class="co"># variable, divided by the standard deviation of the &quot;iq&quot; variable.  </span></span>
<span id="cb300-5"><a href="chap-functions.html#cb300-5"></a>wechsler <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb300-6"><a href="chap-functions.html#cb300-6"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb300-7"><a href="chap-functions.html#cb300-7"></a>    <span class="dt">iq_z =</span> (iq <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(iq)) <span class="op">/</span><span class="st"> </span><span class="kw">sd</span>(iq)</span>
<span id="cb300-8"><a href="chap-functions.html#cb300-8"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 120 x 6
##    participant    iq   age test1 test2   iq_z
##    &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
##  1 ppt_1          71    27    46    50 -1.84 
##  2 ppt_2         103    38    42    29  0.238
##  3 ppt_3          74    20    50    77 -1.64 
##  4 ppt_4         108    46    50    62  0.562
##  5 ppt_5         118    45    60    29  1.21 
##  6 ppt_6         129    33    45    45  1.92 
##  7 ppt_7         103    49    42    41  0.238
##  8 ppt_8         120    27    63    33  1.34 
##  9 ppt_9          96    37    53    44 -0.216
## 10 ppt_10         80    26    53    21 -1.25 
## # … with 110 more rows</code></pre>
<p>Or we can use the <code>scale()</code> function:</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="chap-functions.html#cb302-1"></a><span class="co"># Take the &quot;wechsler&quot; dataframe, and mutate it,</span></span>
<span id="cb302-2"><a href="chap-functions.html#cb302-2"></a><span class="co"># such that there is a variable called &quot;iq_std&quot; for which</span></span>
<span id="cb302-3"><a href="chap-functions.html#cb302-3"></a><span class="co"># the entries are equal to the scaled values of the &quot;iq&quot; variable.  </span></span>
<span id="cb302-4"><a href="chap-functions.html#cb302-4"></a>wechsler <span class="op">%&gt;%</span></span>
<span id="cb302-5"><a href="chap-functions.html#cb302-5"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb302-6"><a href="chap-functions.html#cb302-6"></a>    <span class="dt">iq_std =</span> <span class="kw">scale</span>(iq)</span>
<span id="cb302-7"><a href="chap-functions.html#cb302-7"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 120 x 6
##    participant    iq   age test1 test2 iq_std[,1]
##    &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
##  1 ppt_1          71    27    46    50     -1.84 
##  2 ppt_2         103    38    42    29      0.238
##  3 ppt_3          74    20    50    77     -1.64 
##  4 ppt_4         108    46    50    62      0.562
##  5 ppt_5         118    45    60    29      1.21 
##  6 ppt_6         129    33    45    45      1.92 
##  7 ppt_7         103    49    42    41      0.238
##  8 ppt_8         120    27    63    33      1.34 
##  9 ppt_9          96    37    53    44     -0.216
## 10 ppt_10         80    26    53    21     -1.25 
## # … with 110 more rows</code></pre>
<p>We can also use the <code>scale()</code> function to mean-center a variable, by setting <code>scale(variable, center = TRUE, scale = FALSE)</code>:</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="chap-functions.html#cb304-1"></a><span class="co"># create two new variables in the &quot;wechsler&quot; dataframe, one which is </span></span>
<span id="cb304-2"><a href="chap-functions.html#cb304-2"></a><span class="co"># mean centered iq, and one which is standardised iq:</span></span>
<span id="cb304-3"><a href="chap-functions.html#cb304-3"></a>wechsler <span class="op">%&gt;%</span></span>
<span id="cb304-4"><a href="chap-functions.html#cb304-4"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb304-5"><a href="chap-functions.html#cb304-5"></a>    <span class="dt">iq_mc =</span> <span class="kw">scale</span>(iq, <span class="dt">center =</span> <span class="ot">TRUE</span>, <span class="dt">scale =</span> <span class="ot">FALSE</span>),</span>
<span id="cb304-6"><a href="chap-functions.html#cb304-6"></a>    <span class="dt">iq_std =</span> <span class="kw">scale</span>(iq, <span class="dt">center =</span> <span class="ot">TRUE</span>, <span class="dt">scale =</span> <span class="ot">TRUE</span>) <span class="co"># these are the default settings</span></span>
<span id="cb304-7"><a href="chap-functions.html#cb304-7"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 120 x 7
##    participant    iq   age test1 test2 iq_mc[,1] iq_std[,1]
##    &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
##  1 ppt_1          71    27    46    50    -28.3      -1.84 
##  2 ppt_2         103    38    42    29      3.67      0.238
##  3 ppt_3          74    20    50    77    -25.3      -1.64 
##  4 ppt_4         108    46    50    62      8.67      0.562
##  5 ppt_5         118    45    60    29     18.7       1.21 
##  6 ppt_6         129    33    45    45     29.7       1.92 
##  7 ppt_7         103    49    42    41      3.67      0.238
##  8 ppt_8         120    27    63    33     20.7       1.34 
##  9 ppt_9          96    37    53    44     -3.33     -0.216
## 10 ppt_10         80    26    53    21    -19.3      -1.25 
## # … with 110 more rows</code></pre>
<div class="optional-begin">
Test norms<span id="opt-start-160" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-160&#39;, &#39;opt-start-160&#39;)"></span>
</div>
<div id="opt-body-160" class="optional-body" style="display: none;">
<p>Many neuropsychological tests will have <em>norms</em> - parameters which describe the distribution of scores on the test in a normal population. For instance, in a normal adult population, scores on the WAIS have a mean of 100 and a standard deviation of 15.
<br>
What this means is that rather than calculating a standardised score against the <em>observed mean of our sample</em>, we might calculate a standardised score against the test norms. In the formula for <span class="math inline">\(z\)</span>, we replace our <strong>sample mean</strong> <span class="math inline">\(\bar{x}\)</span> with the <strong>population mean</strong> <span class="math inline">\(\mu\)</span>, and the <strong>sample standard deviation</strong> <span class="math inline">\(s\)</span> with the <strong>population standard deviation</strong> <span class="math inline">\(\sigma\)</span>:<br />
<span class="math display">\[
z = \frac{x - \mu}{\sigma}
\]</span></p>
<p>The resulting values tell us how low/high each participant’s IQ score is compared to the <em>distribution of IQ scores in the population.</em></p>
</div>
<p class="optional-end">
</p>
<hr />
</div>
<div id="glossary" class="section level2">
<h2><span class="header-section-number">5.4</span> Glossary</h2>
<ul>
<li><strong>Function:</strong> A mapping between two sets of numbers, associating every element of the first set with an elemet in the second.<br />
</li>
<li><strong>Transformation:</strong> Applying a function to a variable to map each value to a transformed value.</li>
<li><strong>Logarithm:</strong> The power to which a number must be raised in order to get some other number.</li>
</ul>
<ol style="list-style-type: decimal">
<li><strong>Centering:</strong> Transformation which re-expresses each value as the distance from a given number (e.g., the mean).<br />
</li>
<li><strong>Standardisation:</strong> Transformation which re-expresses each value as the distance from the mean <em>in units of standard deviations.</em>
<br><br></li>
</ol>
<ul>
<li><code>scale()</code> To mean center or standardise a variable (depending upon whether <code>center=TRUE/FALSE</code> and <code>scale=TRUE/FALSE</code>).</li>
</ul>
<hr />
</div>
<div id="exercises" class="section level2">
<h2><span class="header-section-number">5.5</span> Exercises</h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-relationships.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-probability-theory.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["labs.pdf", "labs.epub"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
