<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Handling numeric data | Data Analysis for Psychology in R 1</title>
  <meta name="description" content="This book contains the lab materials for DAPR-1 at UoE." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Handling numeric data | Data Analysis for Psychology in R 1" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book contains the lab materials for DAPR-1 at UoE." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Handling numeric data | Data Analysis for Psychology in R 1" />
  
  <meta name="twitter:description" content="This book contains the lab materials for DAPR-1 at UoE." />
  

<meta name="author" content="Department of Psychology, The University of Edinburgh" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap-categorical.html"/>
<link rel="next" href="chap-relationships.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus')) {
    f.classList.add('fa-minus')
    f.classList.remove('fa-plus')
} else {
    f.classList.add('fa-plus')
    f.classList.remove('fa-minus')
}
}
</script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><div style="margin-top:-13px; font-size: 25px; color: #0F4C81;"><left><b>DAPR1</b></left></div></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course overview</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#course-description"><i class="fa fa-check"></i>Course description</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#team"><i class="fa fa-check"></i>Team</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#schedule"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#textbook"><i class="fa fa-check"></i>Textbook</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html"><i class="fa fa-check"></i>Intro to R, Rstudio, and data in R</a><ul>
<li class="chapter" data-level="0.1" data-path="chap-intro.html"><a href="chap-intro.html#introducing-r-and-rstudio"><i class="fa fa-check"></i><b>0.1</b> Introducing R and Rstudio</a><ul>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#installing"><i class="fa fa-check"></i>Installing</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#first-look-at-rstudio"><i class="fa fa-check"></i>First look at Rstudio</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#r-as-a-calculator"><i class="fa fa-check"></i>R as a calculator</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#r-as-a-calculator-with-a-memory"><i class="fa fa-check"></i>R as a calculator with a memory</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#rscripts-and-rmarkdown"><i class="fa fa-check"></i>Rscripts and Rmarkdown</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#recap"><i class="fa fa-check"></i>Recap</a></li>
</ul></li>
<li class="chapter" data-level="0.2" data-path="chap-intro.html"><a href="chap-intro.html#take-a-breather"><i class="fa fa-check"></i><b>0.2</b> Take a breather</a></li>
<li class="chapter" data-level="0.3" data-path="chap-intro.html"><a href="chap-intro.html#starting-a-new-.rmd-document"><i class="fa fa-check"></i><b>0.3</b> Starting a new .Rmd document</a><ul>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#using-an-r-package"><i class="fa fa-check"></i>Using an R package</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#writing"><i class="fa fa-check"></i>Writing</a></li>
</ul></li>
<li class="chapter" data-level="0.4" data-path="chap-intro.html"><a href="chap-intro.html#data-in-r"><i class="fa fa-check"></i><b>0.4</b> Data in R</a><ul>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#storing-data-in-r-sequences-vectors-of-values"><i class="fa fa-check"></i>Storing data in R: Sequences (“Vectors”) of values</a></li>
<li class="chapter" data-level="" data-path="chap-intro.html"><a href="chap-intro.html#reading-data-into-r"><i class="fa fa-check"></i>Reading data into R</a></li>
</ul></li>
<li class="chapter" data-level="0.5" data-path="chap-intro.html"><a href="chap-intro.html#compiling-a-.rmd-document"><i class="fa fa-check"></i><b>0.5</b> Compiling a .Rmd document</a></li>
<li class="chapter" data-level="0.6" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>0.6</b> Glossary</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="chap-data-types.html"><a href="chap-data-types.html"><i class="fa fa-check"></i><b>1</b> Types of data</a><ul>
<li class="chapter" data-level="1.1" data-path="chap-data-types.html"><a href="chap-data-types.html#accessing-subsections-of-data"><i class="fa fa-check"></i><b>1.1</b> Accessing subsections of data</a><ul>
<li class="chapter" data-level="" data-path="chap-data-types.html"><a href="chap-data-types.html#accessing-by-a-condition"><i class="fa fa-check"></i>Accessing by a condition</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="chap-data-types.html"><a href="chap-data-types.html#editing-subsections-of-data"><i class="fa fa-check"></i><b>1.2</b> Editing subsections of data</a><ul>
<li class="chapter" data-level="" data-path="chap-data-types.html"><a href="chap-data-types.html#changing-specific-entries"><i class="fa fa-check"></i>Changing specific entries</a></li>
<li class="chapter" data-level="" data-path="chap-data-types.html"><a href="chap-data-types.html#changing-entries-by-a-condition"><i class="fa fa-check"></i>Changing entries by a condition</a></li>
<li class="chapter" data-level="" data-path="chap-data-types.html"><a href="chap-data-types.html#changing-a-variable"><i class="fa fa-check"></i>Changing a variable</a></li>
<li class="chapter" data-level="" data-path="chap-data-types.html"><a href="chap-data-types.html#removing-rows-or-columns"><i class="fa fa-check"></i>Removing rows or columns</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="chap-data-types.html"><a href="chap-data-types.html#different-types-of-data"><i class="fa fa-check"></i><b>1.3</b> Different types of data</a></li>
<li class="chapter" data-level="1.4" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>1.4</b> Glossary</a></li>
<li class="chapter" data-level="1.5" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>1.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-categorical.html"><a href="chap-categorical.html"><i class="fa fa-check"></i><b>2</b> Handling categorical data</a><ul>
<li class="chapter" data-level="2.1" data-path="chap-categorical.html"><a href="chap-categorical.html#data-exploration"><i class="fa fa-check"></i><b>2.1</b> Data Exploration</a></li>
<li class="chapter" data-level="2.2" data-path="chap-categorical.html"><a href="chap-categorical.html#unordered-categorical-nominal-data"><i class="fa fa-check"></i><b>2.2</b> Unordered Categorical (Nominal) Data</a><ul>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#frequency-table"><i class="fa fa-check"></i>Frequency table</a></li>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#central-tendency"><i class="fa fa-check"></i>Central tendency</a></li>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#relative-frequencies"><i class="fa fa-check"></i>Relative frequencies</a></li>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#visualising"><i class="fa fa-check"></i>Visualising</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="chap-categorical.html"><a href="chap-categorical.html#ordered-categorical-ordinal-data"><i class="fa fa-check"></i><b>2.3</b> Ordered Categorical (Ordinal) Data</a><ul>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#frequency-table-1"><i class="fa fa-check"></i>Frequency table</a></li>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#central-tendency-1"><i class="fa fa-check"></i>Central tendency</a></li>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#cumulative-percentages-quartiles"><i class="fa fa-check"></i>Cumulative percentages, Quartiles</a></li>
<li class="chapter" data-level="" data-path="chap-categorical.html"><a href="chap-categorical.html#visualising-1"><i class="fa fa-check"></i>Visualising</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>2.4</b> Glossary</a></li>
<li class="chapter" data-level="2.5" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>2.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-numeric.html"><a href="chap-numeric.html"><i class="fa fa-check"></i><b>3</b> Handling numeric data</a><ul>
<li class="chapter" data-level="3.1" data-path="chap-categorical.html"><a href="chap-categorical.html#central-tendency"><i class="fa fa-check"></i><b>3.1</b> Central tendency</a><ul>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#mode-and-median-revisited"><i class="fa fa-check"></i>Mode and median revisited</a></li>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#mean"><i class="fa fa-check"></i>Mean</a></li>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#summarising-variables"><i class="fa fa-check"></i>Summarising variables</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="chap-numeric.html"><a href="chap-numeric.html#spread"><i class="fa fa-check"></i><b>3.2</b> Spread</a><ul>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#interquartile-range"><i class="fa fa-check"></i>Interquartile range</a></li>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#variance"><i class="fa fa-check"></i>Variance</a></li>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#standard-deviation"><i class="fa fa-check"></i>Standard deviation</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="chap-categorical.html"><a href="chap-categorical.html#visualising"><i class="fa fa-check"></i><b>3.3</b> Visualising</a><ul>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#boxplots"><i class="fa fa-check"></i>Boxplots</a></li>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#histograms"><i class="fa fa-check"></i>Histograms</a></li>
<li class="chapter" data-level="" data-path="chap-numeric.html"><a href="chap-numeric.html#density-curves"><i class="fa fa-check"></i>Density curves</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="chap-numeric.html"><a href="chap-numeric.html#skew"><i class="fa fa-check"></i><b>3.4</b> Skew</a></li>
<li class="chapter" data-level="3.5" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>3.5</b> Glossary</a></li>
<li class="chapter" data-level="3.6" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>3.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-relationships.html"><a href="chap-relationships.html"><i class="fa fa-check"></i><b>4</b> Visualising and describing relationships</a><ul>
<li class="chapter" data-level="4.1" data-path="chap-relationships.html"><a href="chap-relationships.html#outcome-vs-explanatory"><i class="fa fa-check"></i><b>4.1</b> Outcome vs Explanatory</a></li>
<li class="chapter" data-level="4.2" data-path="chap-relationships.html"><a href="chap-relationships.html#numeric-and-categorical"><i class="fa fa-check"></i><b>4.2</b> Numeric and Categorical</a><ul>
<li class="chapter" data-level="" data-path="chap-relationships.html"><a href="chap-relationships.html#visualising---colours"><i class="fa fa-check"></i>Visualising - Colours</a></li>
<li class="chapter" data-level="" data-path="chap-relationships.html"><a href="chap-relationships.html#visualising---facets"><i class="fa fa-check"></i>Visualising - Facets</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="chap-relationships.html"><a href="chap-relationships.html#numeric-and-numeric"><i class="fa fa-check"></i><b>4.3</b> Numeric and Numeric</a><ul>
<li class="chapter" data-level="" data-path="chap-relationships.html"><a href="chap-relationships.html#covariance"><i class="fa fa-check"></i>Covariance</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>4.4</b> Glossary</a></li>
<li class="chapter" data-level="4.5" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-functions.html"><a href="chap-functions.html"><i class="fa fa-check"></i><b>5</b> Types of relationships (functions)</a><ul>
<li class="chapter" data-level="5.1" data-path="chap-functions.html"><a href="chap-functions.html#functions"><i class="fa fa-check"></i><b>5.1</b> Functions</a><ul>
<li class="chapter" data-level="" data-path="chap-functions.html"><a href="chap-functions.html#linear-functions"><i class="fa fa-check"></i>Linear functions</a></li>
<li class="chapter" data-level="" data-path="chap-functions.html"><a href="chap-functions.html#non-linear-functions"><i class="fa fa-check"></i>Non-linear functions</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="chap-functions.html"><a href="chap-functions.html#transformations"><i class="fa fa-check"></i><b>5.2</b> Transformations</a></li>
<li class="chapter" data-level="5.3" data-path="chap-functions.html"><a href="chap-functions.html#centering-and-standardisation"><i class="fa fa-check"></i><b>5.3</b> Centering and Standardisation</a></li>
<li class="chapter" data-level="5.4" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>5.4</b> Glossary</a></li>
<li class="chapter" data-level="5.5" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>5.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html"><i class="fa fa-check"></i><b>6</b> Basics of probability theory</a><ul>
<li class="chapter" data-level="" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#where-are-we-going-to"><i class="fa fa-check"></i>Where are we going to?</a></li>
<li class="chapter" data-level="6.1" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section"><i class="fa fa-check"></i><b>6.1</b> Section</a></li>
<li class="chapter" data-level="6.2" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section-1"><i class="fa fa-check"></i><b>6.2</b> Section</a></li>
<li class="chapter" data-level="6.3" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>6.3</b> Glossary</a></li>
<li class="chapter" data-level="6.4" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>6.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-probability-rules.html"><a href="chap-probability-rules.html"><i class="fa fa-check"></i><b>7</b> Probability rules</a><ul>
<li class="chapter" data-level="7.1" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section"><i class="fa fa-check"></i><b>7.1</b> Section</a></li>
<li class="chapter" data-level="7.2" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section-1"><i class="fa fa-check"></i><b>7.2</b> Section</a></li>
<li class="chapter" data-level="7.3" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>7.3</b> Glossary</a></li>
<li class="chapter" data-level="7.4" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>7.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap-discrete-distributions.html"><a href="chap-discrete-distributions.html"><i class="fa fa-check"></i><b>8</b> Random variables &amp; distributions (discrete)</a><ul>
<li class="chapter" data-level="8.1" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section"><i class="fa fa-check"></i><b>8.1</b> Section</a></li>
<li class="chapter" data-level="8.2" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section-1"><i class="fa fa-check"></i><b>8.2</b> Section</a></li>
<li class="chapter" data-level="8.3" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>8.3</b> Glossary</a></li>
<li class="chapter" data-level="8.4" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>8.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap-continuous-distributions.html"><a href="chap-continuous-distributions.html"><i class="fa fa-check"></i><b>9</b> Random variables and distributions (continuous)</a><ul>
<li class="chapter" data-level="9.1" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section"><i class="fa fa-check"></i><b>9.1</b> Section</a></li>
<li class="chapter" data-level="9.2" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section-1"><i class="fa fa-check"></i><b>9.2</b> Section</a></li>
<li class="chapter" data-level="9.3" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>9.3</b> Glossary</a></li>
<li class="chapter" data-level="9.4" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>9.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap-sampling.html"><a href="chap-sampling.html"><i class="fa fa-check"></i><b>10</b> Sampling variability and sampling distributions</a><ul>
<li class="chapter" data-level="10.1" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section"><i class="fa fa-check"></i><b>10.1</b> Section</a></li>
<li class="chapter" data-level="10.2" data-path="chap-probability-theory.html"><a href="chap-probability-theory.html#section-1"><i class="fa fa-check"></i><b>10.2</b> Section</a></li>
<li class="chapter" data-level="10.3" data-path="chap-intro.html"><a href="chap-intro.html#glossary"><i class="fa fa-check"></i><b>10.3</b> Glossary</a></li>
<li class="chapter" data-level="10.4" data-path="chap-data-types.html"><a href="chap-data-types.html#exercises"><i class="fa fa-check"></i><b>10.4</b> Exercises</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://www.handbooks.psy.ed.ac.uk/psychology-1a-and-1b/dapr1" target="blank">Psychology Handbooks</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis for Psychology in R 1</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap-numeric" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Handling numeric data</h1>
<div class="lo">
<p><strong>LEARNING OBJECTIVES</strong></p>
<ul>
<li>LO1: Understand the appropriate visualization for numeric data.</li>
<li>LO2: Understand methods to calculate the spread of numeric data.</li>
<li>LO3: Understand methods to calculate central tendency for numeric data.</li>
</ul>
</div>
<p>In the previous chapter, we looked into describing and visualising <strong>categorical</strong> data.
We looked at using the <strong>mode</strong> and <strong>median</strong> as measures of <strong>central tendency</strong>, before discussing how for <strong>ordered categorical</strong> data we could look at the <strong>quartiles</strong> (the points in rank-ordered data below which falls 25%, 50%, 75% and 100% of the data) to gain an understanding of how <em>spread out</em> the data are.<br />
We now move to looking at measures of central tendency and of spread for <strong>numeric data</strong>.</p>
<div id="central-tendency" class="section level2">
<h2><span class="header-section-number">3.1</span> Central tendency</h2>
<div class="frame">
<p>In the following examples, we are going to use some data on 120 participants’ IQ scores (measured on the Wechsler Adult Intelligence Scale (WAIS)), their ages, and their scores on 2 other tests.<br />
It is available at <a href="https://uoepsy.github.io/data/dapr1/wechsler.csv" class="uri">https://uoepsy.github.io/data/dapr1/wechsler.csv</a></p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="chap-numeric.html#cb201-1"></a>wechsler &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://uoepsy.github.io/data/dapr1/wechsler.csv&quot;</span>)</span>
<span id="cb201-2"><a href="chap-numeric.html#cb201-2"></a><span class="kw">summary</span>(wechsler)</span></code></pre></div>
<pre><code>##  participant              iq              age            test1           test2      
##  Length:120         Min.   : 58.00   Min.   :20.00   Min.   :30.00   Min.   : 2.00  
##  Class :character   1st Qu.: 88.00   1st Qu.:29.50   1st Qu.:45.75   1st Qu.:42.00  
##  Mode  :character   Median :100.50   Median :37.00   Median :49.00   Median :52.50  
##                     Mean   : 99.33   Mean   :36.63   Mean   :49.33   Mean   :51.24  
##                     3rd Qu.:109.00   3rd Qu.:44.00   3rd Qu.:53.25   3rd Qu.:62.00  
##                     Max.   :137.00   Max.   :71.00   Max.   :67.00   Max.   :80.00</code></pre>
</div>
<div id="mode-and-median-revisited" class="section level3 unnumbered">
<h3>Mode and median revisited</h3>
<p>In the previous chapter we learned about two measures of central tendency:</p>
<ul>
<li><strong>Mode:</strong> The most frequent value (the value that occurs the greatest number of times).<br />
</li>
<li><strong>Median:</strong> The value for which 50% of observations a lower and 50% are higher. It is the mid-point of the values when they are rank-ordered.</li>
</ul>
<p>We applied both of these to categorical data, but we can also use them for <strong>numeric</strong> data.</p>
<table>
<colgroup>
<col width="25%" />
<col width="25%" />
<col width="25%" />
<col width="25%" />
</colgroup>
<thead>
<tr class="header">
<th align="right"></th>
<th align="right">Mode</th>
<th align="right">Median</th>
<th align="right">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">Nominal (unordered categorical)</td>
<td align="right">✔</td>
<td align="right">✘</td>
<td align="right">✘</td>
</tr>
<tr class="even">
<td align="right">Ordinal (ordered categorical)</td>
<td align="right">✔</td>
<td align="right">✔</td>
<td align="right"><strong>?</strong><br>(you may see it sometimes for certain types of ordinal data - there’s no consensus)</td>
</tr>
<tr class="odd">
<td align="right">Numeric Continuous</td>
<td align="right">✔</td>
<td align="right">✔</td>
<td align="right">✔</td>
</tr>
</tbody>
</table>
<p><br>
The mode of numeric variables is not frequently used. Unlike categorical variables where there are a distinct set of possible values which the data can take, for numeric variables, data can take a many more (or infinitely many) different values. Finding the “most common” is sometimes not possible.<br />
<br>
The most frequent value (the <strong>mode</strong>) of the <em>iq</em> variable is 97:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="chap-numeric.html#cb203-1"></a><span class="co"># take the &quot;wechsler&quot; dataframe %&gt;%</span></span>
<span id="cb203-2"><a href="chap-numeric.html#cb203-2"></a><span class="co"># count() the values in the &quot;iq&quot; variable (creates an &quot;n&quot; column), and</span></span>
<span id="cb203-3"><a href="chap-numeric.html#cb203-3"></a><span class="co"># from there, arrange() the data so that the &quot;n&quot; column is descending - desc()</span></span>
<span id="cb203-4"><a href="chap-numeric.html#cb203-4"></a>wechsler <span class="op">%&gt;%</span></span>
<span id="cb203-5"><a href="chap-numeric.html#cb203-5"></a><span class="st">    </span><span class="kw">count</span>(iq) <span class="op">%&gt;%</span></span>
<span id="cb203-6"><a href="chap-numeric.html#cb203-6"></a><span class="st">    </span><span class="kw">arrange</span>(<span class="kw">desc</span>(n))</span></code></pre></div>
<pre><code>## # A tibble: 53 x 2
##       iq     n
##    &lt;dbl&gt; &lt;int&gt;
##  1    97     7
##  2   108     6
##  3    92     5
##  4   103     5
##  5   105     5
##  6   110     5
##  7    85     4
##  8    99     4
##  9   107     4
## 10   113     4
## # … with 43 more rows</code></pre>
<p>Recall that the <strong>median</strong> is found by ordering the data from lowest to highest, and finding the mid-point.
In the <em>wechsler</em> dataset we have IQ scores for 120 participants.
We find the median by ranking them from lowest to highest IQ, and finding the mid-point between the <span class="math inline">\(60^{th}\)</span> and <span class="math inline">\(61^{st}\)</span> participants’ scores.</p>
<p>We can also use the <code>median()</code> function we used in the previous chapter:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="chap-numeric.html#cb205-1"></a><span class="kw">median</span>(wechsler<span class="op">$</span>iq)</span></code></pre></div>
<pre><code>## [1] 100.5</code></pre>
</div>
<div id="mean" class="section level3 unnumbered">
<h3>Mean</h3>
<p>One of the most frequently used measures of central tendency for <strong>numeric</strong> data is the <strong>mean</strong>.</p>
<div class="yellow">
<p><strong>Mean:</strong> <span class="math inline">\(\bar{x}\)</span></p>
<p>The mean is calculated by summing all of the observations together and then dividing by the total number of obervations (<span class="math inline">\(n\)</span>).</p>
<p>When we have sampled some data, we denote the mean of our sample with the symbol <span class="math inline">\(\bar{x}\)</span> (sometimes referred to as “x bar”). The equation for the mean is:</p>
<p><span class="math display">\[\bar{x} = \frac{\sum\limits_{i = 1}^{n}x_i}{n}\]</span></p>
<div class="optional-begin">
Optional - Help reading mathematical formulae<span id="opt-start-137" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-137&#39;, &#39;opt-start-137&#39;)"></span>
</div>
<div id="opt-body-137" class="optional-body" style="display: none;">
<p>This might be the first mathematical formula you have seen in a while, so let’s unpack it.</p>
<p>The <span class="math inline">\(\sum\)</span> symbol is used to denote a <em>series of additions</em> - a <strong>“summation”.</strong></p>
<p>When we include the bits around it: <span class="math inline">\(\sum\limits_{i = 1}^{n}x_i\)</span> we are indicating that we add together all the terms <span class="math inline">\(x_i\)</span> for values of <span class="math inline">\(i\)</span> between <span class="math inline">\(1\)</span> and <span class="math inline">\(n\)</span>:
<span class="math display">\[\sum\limits_{i = 1}^{n}x_i \qquad = \qquad x_1+x_2+x_3+...+x_n\]</span></p>
<p>So in order to calculate the mean, we do the summation (adding together) of all the values from the <span class="math inline">\(1^{st}\)</span> to the <span class="math inline">\(n^{th}\)</span> (where <span class="math inline">\(n\)</span> is the total number of values), and we divide that by <span class="math inline">\(n\)</span>.</p>
</div>
<p class="optional-end">
</p>
<div class="optional-begin">
Optional - Samples and populations<span id="opt-start-138" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-138&#39;, &#39;opt-start-138&#39;)"></span>
</div>
<div id="opt-body-138" class="optional-body" style="display: none;">
<p>Statistics is all about drawing inferences from some <strong>sampled</strong> data about the larger <strong>population</strong> from which it is sampled.</p>
<p>A statistic which we calculate from our sample provides us with <em>an estimate</em> of something in the population (for instance, we might take the average age of students at Edinburgh University as an estimate of the age of <em>all</em> students).</p>
<p>Because of this, statisticians have different notations for when we are talking about populations vs talking about samples:</p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="right"></th>
<th align="right">Sample</th>
<th align="right">Population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">Number of observations</td>
<td align="right"><span class="math inline">\(n\)</span></td>
<td align="right"><span class="math inline">\(N\)</span></td>
</tr>
<tr class="even">
<td align="right">Mean</td>
<td align="right"><span class="math inline">\(\bar{x} = \frac{\sum\limits_{i = 1}^{n}x_i}{n}\)</span></td>
<td align="right"><span class="math inline">\(\mu = \frac{\sum\limits_{i = 1}^{N}x_i}{N}\)</span></td>
</tr>
</tbody>
</table>
</div>
<p class="optional-end">
</p>
</div>
<p>We can do the calculation by summing the <em>iq</em> variable, and dividing by the number of observations (in our case we have 120 participants):</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="chap-numeric.html#cb207-1"></a><span class="co"># get the values in the &quot;iq&quot; variable from the &quot;wechsler&quot; dataframe, and</span></span>
<span id="cb207-2"><a href="chap-numeric.html#cb207-2"></a><span class="co"># sum them all together. Then divide this by 120</span></span>
<span id="cb207-3"><a href="chap-numeric.html#cb207-3"></a><span class="kw">sum</span>(wechsler<span class="op">$</span>iq)<span class="op">/</span><span class="dv">120</span></span></code></pre></div>
<pre><code>## [1] 99.33333</code></pre>
<p>Or, more easily, we can use the <code>mean()</code> function:</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="chap-numeric.html#cb209-1"></a><span class="kw">mean</span>(wechsler<span class="op">$</span>iq)</span></code></pre></div>
<pre><code>## [1] 99.33333</code></pre>
</div>
<div id="summarising-variables" class="section level3 unnumbered">
<h3>Summarising variables</h3>
<p>Functions such as <code>mean()</code>, <code>median()</code>, <code>min()</code> and <code>max()</code> can quickly summarise data, and we can use them together really easily in combination with <code>summarise()</code>.</p>
<div class="yellow">
<p><strong>Summarise()</strong></p>
<p>The <code>summarise()</code> function is used to reduce variables down to a single summary value.</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="chap-numeric.html#cb211-1"></a><span class="co"># take the data %&gt;%</span></span>
<span id="cb211-2"><a href="chap-numeric.html#cb211-2"></a><span class="co"># summarise() it, such that there is a value called &quot;summary_value&quot;, which</span></span>
<span id="cb211-3"><a href="chap-numeric.html#cb211-3"></a><span class="co"># is the sum() of &quot;variable1&quot; column, and a value called </span></span>
<span id="cb211-4"><a href="chap-numeric.html#cb211-4"></a><span class="co"># &quot;summary_value2&quot; which is the mean() of the &quot;variable2&quot; column.</span></span>
<span id="cb211-5"><a href="chap-numeric.html#cb211-5"></a>data <span class="op">%&gt;%</span></span>
<span id="cb211-6"><a href="chap-numeric.html#cb211-6"></a><span class="st">  </span><span class="kw">summarise</span>(</span>
<span id="cb211-7"><a href="chap-numeric.html#cb211-7"></a>    <span class="dt">summary_value =</span> <span class="kw">sum</span>(variable1),</span>
<span id="cb211-8"><a href="chap-numeric.html#cb211-8"></a>    <span class="dt">summary_value2 =</span> <span class="kw">mean</span>(variable2)</span>
<span id="cb211-9"><a href="chap-numeric.html#cb211-9"></a>  )</span></code></pre></div>
<p><strong>Note:</strong> Just like with <code>mutate()</code> (introduced in the previous chapter) we don’t have to keep using the dollar sign <code>$</code>, as we have already told it what dataframe to look for the variables in.</p>
</div>
<p>So if we want to show the mean IQ score and the mean age of our participants:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="chap-numeric.html#cb212-1"></a><span class="co"># take the &quot;wechsler&quot; dataframe %&gt;%</span></span>
<span id="cb212-2"><a href="chap-numeric.html#cb212-2"></a><span class="co"># summarise() it, such that there is a value called &quot;mean_iq&quot;, which</span></span>
<span id="cb212-3"><a href="chap-numeric.html#cb212-3"></a><span class="co"># is the mean() of the &quot;iq&quot; variable, and a value called </span></span>
<span id="cb212-4"><a href="chap-numeric.html#cb212-4"></a><span class="co"># &quot;mean_age&quot; which is the mean() of the &quot;age&quot; variable. </span></span>
<span id="cb212-5"><a href="chap-numeric.html#cb212-5"></a>wechsler <span class="op">%&gt;%</span></span>
<span id="cb212-6"><a href="chap-numeric.html#cb212-6"></a><span class="st">    </span><span class="kw">summarise</span>(</span>
<span id="cb212-7"><a href="chap-numeric.html#cb212-7"></a>        <span class="dt">mean_iq =</span> <span class="kw">mean</span>(iq),</span>
<span id="cb212-8"><a href="chap-numeric.html#cb212-8"></a>        <span class="dt">mean_age =</span> <span class="kw">mean</span>(age)</span>
<span id="cb212-9"><a href="chap-numeric.html#cb212-9"></a>    )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   mean_iq mean_age
##     &lt;dbl&gt;    &lt;dbl&gt;
## 1    99.3     36.6</code></pre>
</div>
</div>
<div id="spread" class="section level2">
<h2><span class="header-section-number">3.2</span> Spread</h2>
<div id="interquartile-range" class="section level3 unnumbered">
<h3>Interquartile range</h3>
<p>If we are using the <strong>median</strong> as our measure of central tendency and we want to discuss how spread out the spread are around it, then we will want to use quartiles (recall that these are linked: the <span class="math inline">\(2^{nd}\)</span> quartile = the median).</p>
<p>In the previous chapter we briefly introduced how for <strong>ordinal</strong> data, the 1st and 3rd quartiles give us information about how spread out the data are across the possible response categories.
For numeric data, we can likewise find the 1st and 3rd quartiles in the same way - we rank-order all the data, and find the point at which 25% and 75% of the data falls below.</p>
<p>The <em>difference</em> between the 1st and 3rd quartiles is known as the <strong>interquartile range (IQR)</strong>.<br />
<small>( <strong>Note</strong>, we couldn’t take the <em>difference</em> for ordinal data, because “difference” would not be quantifiable - the categories are ordered, but intervals are between categories are unknown)</small></p>
<p>In R, we can find the IQR as follows:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="chap-numeric.html#cb214-1"></a><span class="kw">IQR</span>(wechsler<span class="op">$</span>age)</span></code></pre></div>
<pre><code>## [1] 14.5</code></pre>
<p>Alternatively, we can use this inside <code>summarise()</code>:</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="chap-numeric.html#cb216-1"></a><span class="co"># take the &quot;wechsler&quot; dataframe %&gt;%</span></span>
<span id="cb216-2"><a href="chap-numeric.html#cb216-2"></a><span class="co"># summarise() it, such that there is a value called &quot;median_age&quot;, which</span></span>
<span id="cb216-3"><a href="chap-numeric.html#cb216-3"></a><span class="co"># is the median() of the &quot;age&quot; variable, and a value called &quot;iqr_age&quot;, which</span></span>
<span id="cb216-4"><a href="chap-numeric.html#cb216-4"></a><span class="co"># is the IQR() of the &quot;age&quot; variable.</span></span>
<span id="cb216-5"><a href="chap-numeric.html#cb216-5"></a>wechsler <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb216-6"><a href="chap-numeric.html#cb216-6"></a><span class="st">  </span><span class="kw">summarise</span>(</span>
<span id="cb216-7"><a href="chap-numeric.html#cb216-7"></a>    <span class="dt">median_age =</span> <span class="kw">median</span>(age),</span>
<span id="cb216-8"><a href="chap-numeric.html#cb216-8"></a>    <span class="dt">iqr_age =</span> <span class="kw">IQR</span>(age)</span>
<span id="cb216-9"><a href="chap-numeric.html#cb216-9"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   median_age iqr_age
##        &lt;dbl&gt;   &lt;dbl&gt;
## 1         37    14.5</code></pre>
</div>
<div id="variance" class="section level3 unnumbered">
<h3>Variance</h3>
<p>If we are using the <strong>mean</strong> as our as our measure of central tendency, we can think of the spread of the data in terms of the <strong>deviations</strong> (distances from each value to the mean).</p>
<p>Recall that the mean is denoted by <span class="math inline">\(\bar{x}\)</span>. If we use <span class="math inline">\(x_i\)</span> to denote the <span class="math inline">\(i^{th}\)</span> value of <span class="math inline">\(x\)</span>, then we can denote deviation for <span class="math inline">\(x_i\)</span> as <span class="math inline">\(x_i - \bar{x}\)</span>.<br />
The deviations can be visualised by the red lines in Figure <a href="chap-numeric.html#fig:deviations">3.1</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:deviations"></span>
<img src="images/numeric/deviations.png" alt="Deviations from the mean"  />
<p class="caption">
Figure 3.1: Deviations from the mean
</p>
</div>
<div class="frame">
<p><strong>The sum of deviations is always zero</strong></p>
<p><span class="math display">\[\sum\limits_{i = 1}^{n}x_i - \bar{x} \qquad = \qquad 0\]</span></p>
<p>The mean is like a center of gravity - the sum of the positive deviations (where <span class="math inline">\(x_i &gt; \bar{x}\)</span>) is equal to the sum of the negative deviations (where <span class="math inline">\(x_i &lt; \bar{x}\)</span>).</p>
</div>
<p>Because deviations around the mean always sum to zero, in order to express how spread out the data are around the mean, we must we consider <strong>squared deviations</strong>.<br />
Squaring the deviations makes them all positive. Observations far away from the mean <em>in either direction</em> will have large, positive squared deviations. The average squared deviation is known as the <strong>variance,</strong> and denoted by <span class="math inline">\(s^2\)</span></p>
<div class="yellow">
<p><strong>Variance:</strong> <span class="math inline">\(s^2\)</span></p>
<p>The variance is calculated as the average of the squared deviations from the mean.</p>
<p>When we have sampled some data, we denote the mean of our sample with the symbol <span class="math inline">\(\bar{x}\)</span> (sometimes referred to as “x bar”). The equation for the variance is:</p>
<p><span class="math display">\[s^2 = \frac{\sum\limits_{i=1}^{n}(x_i - \bar{x})^2}{n-1}\]</span></p>
<div class="optional-begin">
Optional: Why n minus 1?<span id="opt-start-139" class="fa fa-plus optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-139&#39;, &#39;opt-start-139&#39;)"></span>
</div>
<div id="opt-body-139" class="optional-body" style="display: none;">
<p>The top part of the equation <span class="math inline">\(\sum\limits_{i=1}^{n}(x_i - \bar{x})^2\)</span> can be expressed in <span class="math inline">\(n-1\)</span> terms, so we divide by <span class="math inline">\(n-1\)</span> to get the average.<br />
<br>
<strong>Example:</strong> If we only have two observations <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, then we can write out the formula for variance in full quite easily. The top part of the equation would be:
<span class="math display">\[
\sum\limits_{i=1}^{2}(x_i - \bar{x})^2 \qquad = \qquad (x_1 - \bar{x})^2 + (x_2 - \bar{x})^2
\]</span></p>
<p>The mean for only two observations can be expressed as <span class="math inline">\(\bar{x} = \frac{x_1 + x_2}{2}\)</span>, so we can substitute this in to the formula above.
<span class="math display">\[
(x_1 - \bar{x})^2 + (x_2 - \bar{x})^2 \qquad = \qquad \left(x_1 - \frac{x_1 + x_2}{2}\right)^2 + \left(x_2 - \frac{x_1 + x_2}{2}\right)^2 
\]</span>
Which simplifies down to one value:
<span class="math display">\[
\left(x_1 - \frac{x_1 + x_2}{2}\right)^2 + \left(x_2 - \frac{x_1 + x_2}{2}\right)^2 \qquad = \qquad  \left(\frac{x_1 - x_2}{\sqrt{2}}\right)^2
\]</span>
<br>
So although we have <span class="math inline">\(n=2\)</span> datapoints (<span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>), the top part of the equation for the variance has only 1 (<span class="math inline">\(n-1\)</span>) units of information. In order to take the average of these bits of information, we divide by <span class="math inline">\(n-1\)</span>.</p>
</div>
<p class="optional-end">
</p>
</div>
<p>We can get R to calculate this for us using the <code>var()</code> function:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="chap-numeric.html#cb218-1"></a>wechsler <span class="op">%&gt;%</span></span>
<span id="cb218-2"><a href="chap-numeric.html#cb218-2"></a><span class="st">  </span><span class="kw">summarise</span>(</span>
<span id="cb218-3"><a href="chap-numeric.html#cb218-3"></a>    <span class="dt">variance_iq =</span> <span class="kw">var</span>(iq)</span>
<span id="cb218-4"><a href="chap-numeric.html#cb218-4"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   variance_iq
##         &lt;dbl&gt;
## 1        238.</code></pre>
</div>
<div id="standard-deviation" class="section level3 unnumbered">
<h3>Standard deviation</h3>
<p>One difficulty in interpreting <strong>variance</strong> as a measure of spread is that it is in units of <strong>squared deviations.</strong> It relects the typical <em>squared</em> distance from a value to the mean.<br />
Conveniently, by taking the square root of the variance, we can translate the measure back into the units of our original variable. This is known as the <strong>standard deviation.</strong></p>
<div class="yellow">
<p><strong>Standard Deviation:</strong> <span class="math inline">\(s\)</span></p>
<p>The standard deviation, denoted by <span class="math inline">\(s\)</span>, is a rough estimate of the typical distance from a value to the mean.<br />
It is the square root of the variance (the typical <em>squared</em> distance from a value to the mean).</p>
<p><span class="math display">\[
s = \sqrt{\frac{\sum\limits_{i=1}^{n}(x_i - \bar{x})^2}{n-1}}
\]</span></p>
</div>
<p>We can get R to calculate the standard deviation of a variable <code>sd()</code> function:</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="chap-numeric.html#cb220-1"></a>wechsler <span class="op">%&gt;%</span></span>
<span id="cb220-2"><a href="chap-numeric.html#cb220-2"></a><span class="st">  </span><span class="kw">summarise</span>(</span>
<span id="cb220-3"><a href="chap-numeric.html#cb220-3"></a>    <span class="dt">variance_iq =</span> <span class="kw">var</span>(iq),</span>
<span id="cb220-4"><a href="chap-numeric.html#cb220-4"></a>    <span class="dt">sd_iq =</span> <span class="kw">sd</span>(iq)</span>
<span id="cb220-5"><a href="chap-numeric.html#cb220-5"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   variance_iq sd_iq
##         &lt;dbl&gt; &lt;dbl&gt;
## 1        238.  15.4</code></pre>
</div>
</div>
<div id="visualising" class="section level2">
<h2><span class="header-section-number">3.3</span> Visualising</h2>
<div id="boxplots" class="section level3 unnumbered">
<h3>Boxplots</h3>
<p>Boxplots provide a useful way of visualising the <strong>interquartile range (IQR).</strong> You can see what each part of the boxplot represents in Figure <a href="chap-numeric.html#fig:boxplotdesc">3.2</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:boxplotdesc"></span>
<img src="labs_files/figure-html/boxplotdesc-1.png" alt="Anatomy of a boxplot" width="100%" />
<p class="caption">
Figure 3.2: Anatomy of a boxplot
</p>
</div>
<p>We can create a boxplot of our age variable using the following code:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="chap-numeric.html#cb222-1"></a><span class="co"># Notice, we put age on the x axis, making the box plot vertical. </span></span>
<span id="cb222-2"><a href="chap-numeric.html#cb222-2"></a><span class="co"># If we had set aes(y = age) instead, then it would simply be rotated 90 degrees </span></span>
<span id="cb222-3"><a href="chap-numeric.html#cb222-3"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> wechsler, <span class="kw">aes</span>(<span class="dt">x =</span> age)) <span class="op">+</span></span>
<span id="cb222-4"><a href="chap-numeric.html#cb222-4"></a><span class="st">  </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="labs_files/figure-html/unnamed-chunk-133-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="histograms" class="section level3 unnumbered">
<h3>Histograms</h3>
<p>Now that we have learned about the different measures of central tendency and of spread, we can look at how these influence visualisations of numeric variables.</p>
<p>We can visualise numeric data using a <strong>histogram</strong>, which shows the frequency of values which fall within <em>bins</em> of an equal width.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="chap-numeric.html#cb223-1"></a><span class="co"># make a ggplot with the &quot;wechsler&quot; data. </span></span>
<span id="cb223-2"><a href="chap-numeric.html#cb223-2"></a><span class="co"># on the x axis put the possible values in the &quot;iq&quot; variable,</span></span>
<span id="cb223-3"><a href="chap-numeric.html#cb223-3"></a><span class="co"># add a histogram geom (will add bars representing the count </span></span>
<span id="cb223-4"><a href="chap-numeric.html#cb223-4"></a><span class="co"># in each bin of the variable on the x-axis)</span></span>
<span id="cb223-5"><a href="chap-numeric.html#cb223-5"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> wechsler, <span class="kw">aes</span>(<span class="dt">x =</span> iq)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb223-6"><a href="chap-numeric.html#cb223-6"></a><span class="st">  </span><span class="kw">geom_histogram</span>()</span></code></pre></div>
<p><img src="labs_files/figure-html/unnamed-chunk-134-1.png" width="672" style="display: block; margin: auto;" />
We can specifiy the width of the bins:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="chap-numeric.html#cb224-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> wechsler, <span class="kw">aes</span>(<span class="dt">x =</span> iq)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb224-2"><a href="chap-numeric.html#cb224-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">5</span>)</span></code></pre></div>
<p><img src="labs_files/figure-html/unnamed-chunk-135-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Let’s take a look at the means and standard deviations of participants’ scores on the other tests (the <em>test1</em> and <em>test2</em> variables):</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="chap-numeric.html#cb225-1"></a>wechsler <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb225-2"><a href="chap-numeric.html#cb225-2"></a><span class="st">  </span><span class="kw">summarise</span>(</span>
<span id="cb225-3"><a href="chap-numeric.html#cb225-3"></a>    <span class="dt">mean_test1 =</span> <span class="kw">mean</span>(test1),</span>
<span id="cb225-4"><a href="chap-numeric.html#cb225-4"></a>    <span class="dt">sd_test1 =</span> <span class="kw">sd</span>(test1),</span>
<span id="cb225-5"><a href="chap-numeric.html#cb225-5"></a>    <span class="dt">mean_test2 =</span> <span class="kw">mean</span>(test2),</span>
<span id="cb225-6"><a href="chap-numeric.html#cb225-6"></a>    <span class="dt">sd_test2 =</span> <span class="kw">sd</span>(test2)</span>
<span id="cb225-7"><a href="chap-numeric.html#cb225-7"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   mean_test1 sd_test1 mean_test2 sd_test2
##        &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;
## 1       49.3     7.15       51.2     14.4</code></pre>
<p>Tests 1 and 2 have similar means (around 50), but the standard deviation of Test 2 is almost double that of Test 1. We can see this distinction in the visualisation below - the histograms are centered at around the same point (50), but the one for Test 2 is a lot wider than that for Test 1.
<img src="labs_files/figure-html/unnamed-chunk-137-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="density-curves" class="section level3 unnumbered">
<h3>Density curves</h3>
<p>In addition to grouping numeric data into <em>bins</em> in order to produce a histogram, we can also visualise a <strong>density curve.</strong></p>
<p>For the time being, you can think of the density as a bit similar to the notion of <strong>relative frequency</strong> which was discussed in the previous chapter, in that for a density curve, the values on the y-axis are scaled so that the total area under the curve is equal to 1. Because there are infinitely many values that numeric variables could take (e.g., 50, 50.1, 50.01, 5.001, …), we could group the data into infinitely many bins. In creating a curve for which the total area underneath is equal to one, we can use the area under the curve in a range of values to indicate the proportion of values in that range.</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="chap-numeric.html#cb227-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> wechsler, <span class="kw">aes</span>(<span class="dt">x =</span> iq)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb227-2"><a href="chap-numeric.html#cb227-2"></a><span class="st">  </span><span class="kw">geom_density</span>()<span class="op">+</span></span>
<span id="cb227-3"><a href="chap-numeric.html#cb227-3"></a><span class="st">  </span><span class="kw">xlim</span>(<span class="dv">50</span>,<span class="dv">150</span>)</span></code></pre></div>
<p><img src="labs_files/figure-html/unnamed-chunk-138-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="skew" class="section level2">
<h2><span class="header-section-number">3.4</span> Skew</h2>
<p>Skewness is a measure of <em>asymmetry</em> in a distribution. Distributions can be <em>positively skewed</em> or <em>negatively skewed</em>, and this influences our measures of central tendency and of spread to different degrees (see Figure <a href="chap-numeric.html#fig:skewplot">3.3</a>).</p>
<div class="figure" style="text-align: center"><span id="fig:skewplot"></span>
<img src="labs_files/figure-html/skewplot-1.png" alt="Skew influences the mean and median to different degrees." width="672" />
<p class="caption">
Figure 3.3: Skew influences the mean and median to different degrees.
</p>
</div>
<hr />
</div>
<div id="glossary" class="section level2">
<h2><span class="header-section-number">3.5</span> Glossary</h2>
<ul>
<li><strong>Interquartile Range (IQR):</strong> The <span class="math inline">\(3^{rd}\)</span> quartile minus the <span class="math inline">\(1^{st}\)</span> quartile.</li>
<li><strong>Mean:</strong> The sum of all observations divided by the total number of observations. The center of gravity of a variable.</li>
<li><strong>Deviation:</strong> The distance from an observation to the mean value.</li>
<li><strong>Variance:</strong> The average squared distance from observations to the mean value.</li>
<li><strong>Standard deviation:</strong> Square root of variance - can be thought of as the average distance from observations to the mean value.</li>
<li><strong>Boxplot:</strong> Displays the median and the IQR, and any extreme values.<br />
</li>
<li><strong>Histogram:</strong> Shows the frequency of values which fall within <em>bins</em> of an equal width.</li>
<li><strong>Density curve:</strong> A curve for reflecting the distribution of a variable, for which the area under the curve sums to 1.</li>
<li><strong>Skew:</strong> A measure of <em>asymmetry</em> in a distribution.
<br><br></li>
<li><code>summarise()</code> To summarise variables into a single value according to whatever calculation we give it.</li>
<li><code>IQR()</code> To calculate the interquartile range for a given variable.</li>
<li><code>mean()</code> To calculate the mean of a given variable.</li>
<li><code>sd()</code> To calculate the standard deviation of a given variable.</li>
<li><code>var()</code> To calculate the variance of a given variable.</li>
<li><code>geom_boxplot()</code> To add a boxplot to a ggplot.</li>
<li><code>geom_histogram()</code> To add a histogram to a ggplot.</li>
<li><code>geom_density()</code> To add a density curve to a ggplot.</li>
<li><code>geom_vline()</code> To add a vertical line to a ggplot.
<br><br>
<strong>Note:</strong> The following functions are introduced in the exercises below.<br />
</li>
<li><code>filter()</code> allows us to filter a dataframe to those rows which meet a given condition. It will return all columns.<br />
</li>
<li><code>select()</code> allows us to choose certain columns in a dataframe. It will return all rows.</li>
</ul>
<hr />
</div>
<div id="exercises" class="section level2">
<h2><span class="header-section-number">3.6</span> Exercises</h2>
<div class="frame">
The data we are going to use for these exercises is from an experiment using one of the best known tasks in psychology, the “Stroop task”.<br />
<br>
130 participants completed an online task in which they saw two sets of coloured words. Participants spoke out loud the colour of each word, and timed how long it took to complete each set. In the first set of words, the words <em>matched</em> the colours they were presented in (e.g., word “blue” was coloured blue). In the second set of words, the words <em>mismatched</em> the colours (e.g., the word “blue” was coloured red, see Figure <a href="chap-numeric.html#fig:stroop">3.4</a>). Participants’ recorded their times for each set (<em>matching</em> and <em>mismatching</em>).<br />
Participants were randomly assigned to either do the task once only, or to record their times after practicing the task twice.<br />
<br>
You can try out the experiment at <a href="https://faculty.washington.edu/chudler/java/ready.html" class="uri">https://faculty.washington.edu/chudler/java/ready.html</a>.<br />
<br>
The data is available at <a href="https://uoepsy.github.io/data/dapr1/strooptask.csv" class="uri">https://uoepsy.github.io/data/dapr1/strooptask.csv</a>
<br><br>
<div class="figure" style="text-align: center"><span id="fig:stroop"></span>
<img src="images/numeric/stroop1.png" alt="Stroop Task - Color word interference. Images from  https://faculty.washington.edu/chudler/java/ready.html"  />
<p class="caption">
Figure 3.4: Stroop Task - Color word interference. Images from <a href="https://faculty.washington.edu/chudler/java/ready.html" class="uri">https://faculty.washington.edu/chudler/java/ready.html</a>
</p>
</div>
</div>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Open a new Rmarkdown file, load the tidyverse package and read in the data.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution 1<span id="sol-start-140" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-140&#39;, &#39;sol-start-140&#39;)"></span>
</div>
<div id="sol-body-140" class="solution-body" style="display: none;">
<p>It should look something like this:
<img src="images/numeric/freshrmd.png" /></p>
<p>Make sure you regularly save the Rmarkdown files you are writing in, and it might help to close the ones from previous weeks to make your Rstudio experience less busy.<br />
You can see in the bottom right window, the “Files” tab is open, and there are the Rmardkown files from the previous chapters’ exercises.</p>
</div>
<p class="solution-end">
</p>
<hr />
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>using <code>summarise()</code>, show the minimum, maximum, mean and median of the times taken to read the matching word set, and then do the same for the mismatching word set.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution 2<span id="sol-start-141" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-141&#39;, &#39;sol-start-141&#39;)"></span>
</div>
<div id="sol-body-141" class="solution-body" style="display: none;">
<p>Matching words</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="chap-numeric.html#cb228-1"></a>stroopdata <span class="op">%&gt;%</span></span>
<span id="cb228-2"><a href="chap-numeric.html#cb228-2"></a><span class="st">  </span><span class="kw">summarise</span>(</span>
<span id="cb228-3"><a href="chap-numeric.html#cb228-3"></a>    <span class="dt">min_time =</span> <span class="kw">min</span>(matching),</span>
<span id="cb228-4"><a href="chap-numeric.html#cb228-4"></a>    <span class="dt">max_time =</span> <span class="kw">max</span>(matching),</span>
<span id="cb228-5"><a href="chap-numeric.html#cb228-5"></a>    <span class="dt">mean_time =</span> <span class="kw">mean</span>(matching),</span>
<span id="cb228-6"><a href="chap-numeric.html#cb228-6"></a>    <span class="dt">median_time =</span> <span class="kw">median</span>(matching)</span>
<span id="cb228-7"><a href="chap-numeric.html#cb228-7"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   min_time max_time mean_time median_time
##      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1     5.61     31.4      15.1        14.8</code></pre>
<p>Mismatching words</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="chap-numeric.html#cb230-1"></a>stroopdata <span class="op">%&gt;%</span></span>
<span id="cb230-2"><a href="chap-numeric.html#cb230-2"></a><span class="st">  </span><span class="kw">summarise</span>(</span>
<span id="cb230-3"><a href="chap-numeric.html#cb230-3"></a>    <span class="dt">min_time =</span> <span class="kw">min</span>(mismatching),</span>
<span id="cb230-4"><a href="chap-numeric.html#cb230-4"></a>    <span class="dt">max_time =</span> <span class="kw">max</span>(mismatching),</span>
<span id="cb230-5"><a href="chap-numeric.html#cb230-5"></a>    <span class="dt">mean_time =</span> <span class="kw">mean</span>(mismatching),</span>
<span id="cb230-6"><a href="chap-numeric.html#cb230-6"></a>    <span class="dt">median_time =</span> <span class="kw">median</span>(mismatching)</span>
<span id="cb230-7"><a href="chap-numeric.html#cb230-7"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   min_time max_time mean_time median_time
##      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1     9.79     35.2      23.0        22.5</code></pre>
</div>
<p class="solution-end">
</p>
<hr />
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>What we are interested in is the differences between these times. For someone who took 10 seconds for the matching set, and 30 seconds for the mismatching set, we want to record the difference of 20 seconds.</p>
<p>Create a new variable called <em>stroop_effect</em> which is the difference between the <em>mismatching</em> and <em>matching</em> variables.</p>
<p><strong>Hint:</strong> Remember we can use the <code>mutate()</code> function to add a new variable. Recall also that we need to <em>reassign</em> this to the name “stroopdata”, to make the changes appear in the <strong>environment</strong> (rather than just printing them out).</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="chap-numeric.html#cb232-1"></a>stroopdata &lt;-<span class="st"> </span></span>
<span id="cb232-2"><a href="chap-numeric.html#cb232-2"></a><span class="st">  </span>stroopdata <span class="op">%&gt;%</span></span>
<span id="cb232-3"><a href="chap-numeric.html#cb232-3"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb232-4"><a href="chap-numeric.html#cb232-4"></a>    ?? =<span class="st"> </span>??</span>
<span id="cb232-5"><a href="chap-numeric.html#cb232-5"></a>  )</span></code></pre></div>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution 3<span id="sol-start-142" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-142&#39;, &#39;sol-start-142&#39;)"></span>
</div>
<div id="sol-body-142" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="chap-numeric.html#cb233-1"></a>stroopdata &lt;-<span class="st"> </span></span>
<span id="cb233-2"><a href="chap-numeric.html#cb233-2"></a><span class="st">  </span>stroopdata <span class="op">%&gt;%</span></span>
<span id="cb233-3"><a href="chap-numeric.html#cb233-3"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb233-4"><a href="chap-numeric.html#cb233-4"></a>    <span class="dt">stroop_effect =</span> mismatching <span class="op">-</span><span class="st"> </span>matching</span>
<span id="cb233-5"><a href="chap-numeric.html#cb233-5"></a>  )</span>
<span id="cb233-6"><a href="chap-numeric.html#cb233-6"></a></span>
<span id="cb233-7"><a href="chap-numeric.html#cb233-7"></a><span class="co"># and print it out:</span></span>
<span id="cb233-8"><a href="chap-numeric.html#cb233-8"></a>stroopdata</span></code></pre></div>
<pre><code>## # A tibble: 131 x 7
##       id   age practice matching mismatching height stroop_effect
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;       &lt;dbl&gt;  &lt;dbl&gt;         &lt;dbl&gt;
##  1     1    41 yes         22.3         22.4    162          0.1 
##  2     2    24 yes         22.3         24.6    168          2.3 
##  3     3    40 yes         15.4         19.1    166          3.69
##  4     4    46 yes          9.9         20.5    165         10.6 
##  5     5    36 yes         14.2         21.8    160          7.68
##  6     6    29 yes         19.9         23.5    154          3.60
##  7     7    45 no          10.2         22.6    179         12.3 
##  8     8    44 no          16.2         25.1    162          8.89
##  9     9    47 yes          9.73        11.6    148          1.91
## 10    10    59 no           7.68        17.1    153          9.38
## # … with 121 more rows</code></pre>
</div>
<p class="solution-end">
</p>
<hr />
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>For the <em>stroop_effect</em> variable you just created, produce both a histogram and a density curve.</p>
<p>What is the more appropriate guess for the mean of this variable?</p>
<ol style="list-style-type: lower-alpha">
<li>6</li>
<li>8</li>
<li>10</li>
<li>12</li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution 4<span id="sol-start-143" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-143&#39;, &#39;sol-start-143&#39;)"></span>
</div>
<div id="sol-body-143" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="chap-numeric.html#cb235-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> stroopdata, <span class="kw">aes</span>(<span class="dt">x =</span> stroop_effect)) <span class="op">+</span></span>
<span id="cb235-2"><a href="chap-numeric.html#cb235-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>()</span></code></pre></div>
<p><img src="labs_files/figure-html/unnamed-chunk-144-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The default binwidth of the histogram here might lead you astray in guessing the mean value - the highest bar by some distance is at around 5 seconds.<br />
Try changing the binwidth to get a different picture - for example:</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="chap-numeric.html#cb236-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> stroopdata, <span class="kw">aes</span>(<span class="dt">x =</span> stroop_effect)) <span class="op">+</span></span>
<span id="cb236-2"><a href="chap-numeric.html#cb236-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="labs_files/figure-html/unnamed-chunk-145-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>In both histograms, you can see that there is quite a lot of data between the values of 7 and 12.</p>
<p>An advantage of the density curve is that they are better at displaying the distribution shape as they are not influenced by the number of bins. However, this comes at the expense of no longer having the easily interpreted <em>count</em> on the y-axis. A benefit of a histogram is that the viewer can also gain an idea of <em>how much</em> data there is, whereas a density curve of 10 datapoints could be hard to distinguish from one of 100.</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="chap-numeric.html#cb237-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> stroopdata, <span class="kw">aes</span>(<span class="dt">x =</span> stroop_effect)) <span class="op">+</span></span>
<span id="cb237-2"><a href="chap-numeric.html#cb237-2"></a><span class="st">  </span><span class="kw">geom_density</span>()</span></code></pre></div>
<p><img src="labs_files/figure-html/unnamed-chunk-146-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<hr />
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>The code below will produce a histogram of the <em>stroop_effect</em> variable and add a vertical line (<code>geom_vline()</code>) at zero.</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="chap-numeric.html#cb238-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> stroopdata, <span class="kw">aes</span>(<span class="dt">x =</span> stroop_effect)) <span class="op">+</span></span>
<span id="cb238-2"><a href="chap-numeric.html#cb238-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>() <span class="op">+</span></span>
<span id="cb238-3"><a href="chap-numeric.html#cb238-3"></a><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>)</span></code></pre></div>
<p>Calculate the a measure of central tendency for the <em>stroop_effect</em> variable, and add a line to your histogram at that value.</p>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution 5<span id="sol-start-144" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-144&#39;, &#39;sol-start-144&#39;)"></span>
</div>
<div id="sol-body-144" class="solution-body" style="display: none;">
<p>We’ll go for the mean here</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="chap-numeric.html#cb239-1"></a>stroopdata <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb239-2"><a href="chap-numeric.html#cb239-2"></a><span class="st">  </span><span class="kw">summarise</span>(</span>
<span id="cb239-3"><a href="chap-numeric.html#cb239-3"></a>    <span class="dt">mean_diff =</span> <span class="kw">mean</span>(stroop_effect)</span>
<span id="cb239-4"><a href="chap-numeric.html#cb239-4"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1      7.90</code></pre>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="chap-numeric.html#cb241-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> stroopdata, <span class="kw">aes</span>(<span class="dt">x =</span> stroop_effect)) <span class="op">+</span></span>
<span id="cb241-2"><a href="chap-numeric.html#cb241-2"></a><span class="st">  </span><span class="kw">geom_histogram</span>() <span class="op">+</span></span>
<span id="cb241-3"><a href="chap-numeric.html#cb241-3"></a><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">7.9</span>)</span></code></pre></div>
<p><img src="labs_files/figure-html/unnamed-chunk-149-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p class="solution-end">
</p>
<hr />
<div class="question-begin">
Question 6
</div>
<div class="question-body">
<p>There are some other variables in the Stroop Task dataset.<br />
Provide some descriptive statistics for the <em>age</em>, <em>height</em> and <em>practice</em> variables.</p>
<p>For each variable, think:</p>
<ul>
<li>what type of data is it?<br />
</li>
<li>what do you want to report about it? central tendency? if so, what measure? or do you want to report frequencies?</li>
</ul>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution 6<span id="sol-start-145" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-145&#39;, &#39;sol-start-145&#39;)"></span>
</div>
<div id="sol-body-145" class="solution-body" style="display: none;">
<p>The <em>age</em> variable is numeric. The distribution of ages in an experiment will depend a bit on how participants were recruited.<br />
What do you think the shape of the distribution of the global populations’ ages would look like?
Are they likely to be evenly spread around a central value - i.e., are there a similar number of &lt;5 year olds as there are &gt;95 year olds? There are probably more &lt;5 year olds? It’s probably not symmetric. The median is less sensitive to asymmetry, so let’s report that (we would normally want to plot it first too).</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="chap-numeric.html#cb242-1"></a>stroopdata <span class="op">%&gt;%</span></span>
<span id="cb242-2"><a href="chap-numeric.html#cb242-2"></a><span class="st">  </span><span class="kw">summarise</span>(</span>
<span id="cb242-3"><a href="chap-numeric.html#cb242-3"></a>    <span class="dt">min_age =</span> <span class="kw">min</span>(age),</span>
<span id="cb242-4"><a href="chap-numeric.html#cb242-4"></a>    <span class="dt">max_age =</span> <span class="kw">max</span>(age),</span>
<span id="cb242-5"><a href="chap-numeric.html#cb242-5"></a>    <span class="dt">median_age =</span> <span class="kw">median</span>(age),</span>
<span id="cb242-6"><a href="chap-numeric.html#cb242-6"></a>    <span class="dt">iqr_age =</span> <span class="kw">IQR</span>(age)</span>
<span id="cb242-7"><a href="chap-numeric.html#cb242-7"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   min_age max_age median_age iqr_age
##     &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
## 1      14      77         42    14.5</code></pre>
<p>Think about what the distribution shape of everbody in the worlds’ heights might look like? We would expect it to be reasonably symmetric (evenly distributed around a central value). Probably? The mean is likely appropriate here (again, plotting first would be worthwhile).</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="chap-numeric.html#cb244-1"></a>stroopdata <span class="op">%&gt;%</span></span>
<span id="cb244-2"><a href="chap-numeric.html#cb244-2"></a><span class="st">  </span><span class="kw">summarise</span>(</span>
<span id="cb244-3"><a href="chap-numeric.html#cb244-3"></a>    <span class="dt">min_height =</span> <span class="kw">min</span>(height),</span>
<span id="cb244-4"><a href="chap-numeric.html#cb244-4"></a>    <span class="dt">max_height =</span> <span class="kw">max</span>(height),</span>
<span id="cb244-5"><a href="chap-numeric.html#cb244-5"></a>    <span class="dt">mean_height =</span> <span class="kw">mean</span>(height),</span>
<span id="cb244-6"><a href="chap-numeric.html#cb244-6"></a>    <span class="dt">sd_height =</span> <span class="kw">sd</span>(height)</span>
<span id="cb244-7"><a href="chap-numeric.html#cb244-7"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   min_height max_height mean_height sd_height
##        &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;
## 1        135        184        160.      10.4</code></pre>
<p>Lastly, the <em>practice</em> variable is categorical - there are only two categories (“Yes” and “No”). So all we can do is to report the counts (number of datapoints) in each category.</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="chap-numeric.html#cb246-1"></a>stroopdata <span class="op">%&gt;%</span></span>
<span id="cb246-2"><a href="chap-numeric.html#cb246-2"></a><span class="st">  </span><span class="kw">count</span>(practice)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   practice     n
##   &lt;chr&gt;    &lt;int&gt;
## 1 no          69
## 2 yes         62</code></pre>
</div>
<p class="solution-end">
</p>
<hr />
<div class="question-begin">
Question 7
</div>
<div class="question-body">
<p>Think back to Chapter 1, in which we learned how to access different sections of data.</p>
<ol style="list-style-type: decimal">
<li>Assign the name “no_practice” to a new object, which is all of the rows in the “stroopdata” dataframe where the <em>practice</em> variable is equal to “no”.</li>
<li>Assign the name “practice” to a new object, which is all of the rows in the “stroopdata” dataframe where the <em>practice</em> variable is equal to “yes”.</li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution 7<span id="sol-start-146" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-146&#39;, &#39;sol-start-146&#39;)"></span>
</div>
<div id="sol-body-146" class="solution-body" style="display: none;">
<p>We learned how to do this using <code>[]</code> and <code>$</code>:</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="chap-numeric.html#cb248-1"></a><span class="co"># In the stroopdata dataframe, give me all the rows for which the</span></span>
<span id="cb248-2"><a href="chap-numeric.html#cb248-2"></a><span class="co"># condition stroopdata$practice==&quot;no&quot; is TRUE, and give me all the columns.</span></span>
<span id="cb248-3"><a href="chap-numeric.html#cb248-3"></a><span class="co"># assign this as an object with the name &quot;no_practice&quot;</span></span>
<span id="cb248-4"><a href="chap-numeric.html#cb248-4"></a>no_practice &lt;-<span class="st"> </span>stroopdata[stroopdata<span class="op">$</span>practice <span class="op">==</span><span class="st"> &quot;no&quot;</span>, ]</span>
<span id="cb248-5"><a href="chap-numeric.html#cb248-5"></a></span>
<span id="cb248-6"><a href="chap-numeric.html#cb248-6"></a><span class="co">#and the same but for practice == &quot;yes&quot;</span></span>
<span id="cb248-7"><a href="chap-numeric.html#cb248-7"></a>practice &lt;-<span class="st"> </span>stroopdata[stroopdata<span class="op">$</span>practice <span class="op">==</span><span class="st"> &quot;yes&quot;</span>, ]</span></code></pre></div>
<p>Notice that when we run this code, the objects <strong>no_practice</strong> and <strong>practice</strong> will now show up in the environment (top right of Rstudio). We can see there that they have 69 and 62 observations each. This adds up to the 131 observations in the <strong>stroopdata</strong> object.</p>
</div>
<p class="solution-end">
</p>
<hr />
<p>We learned how to tackle things such Question 7 above by making use of <code>[]</code> and <code>$</code> to specify rows/columns/conditions which we want to access in a dataframe.</p>
<p>There are two functions which provide similar functionality - <code>filter()</code> and <code>select()</code>. They are part of the same package as <code>mutate()</code> and <code>summarise()</code> and are often used in conjunction with the <code>%&gt;%</code> operator to tell the functions where to find the variables (meaning we don’t need to use <code>data$variable</code>, we can just use the variable name)</p>
<div class="yellow">
<p><strong>filter()</strong></p>
<p>The <code>filter()</code> function allows us to filter a dataframe down to those rows which meet a given condition. It will return all columns.</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="chap-numeric.html#cb249-1"></a><span class="co"># take the data</span></span>
<span id="cb249-2"><a href="chap-numeric.html#cb249-2"></a><span class="co"># and filter it to only the rows where the &quot;variable1&quot; column is </span></span>
<span id="cb249-3"><a href="chap-numeric.html#cb249-3"></a><span class="co"># equal to &quot;value1&quot;. </span></span>
<span id="cb249-4"><a href="chap-numeric.html#cb249-4"></a>data <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb249-5"><a href="chap-numeric.html#cb249-5"></a><span class="st">  </span><span class="kw">filter</span>(variable1 <span class="op">==</span><span class="st"> </span>value1)</span></code></pre></div>
</div>
<div class="yellow">
<p><strong>select()</strong></p>
<p>The <code>select()</code> function allows us to choose certain columns in a dataframe. It will return all rows.</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="chap-numeric.html#cb250-1"></a><span class="co"># take the data</span></span>
<span id="cb250-2"><a href="chap-numeric.html#cb250-2"></a><span class="co"># and select the &quot;variable1&quot; and &quot;variable2&quot; columns</span></span>
<span id="cb250-3"><a href="chap-numeric.html#cb250-3"></a>data <span class="op">%&gt;%</span></span>
<span id="cb250-4"><a href="chap-numeric.html#cb250-4"></a><span class="st">  </span><span class="kw">select</span>(variable1, variable2)</span></code></pre></div>
</div>
<div class="question-begin">
Question 8
</div>
<div class="question-body">
<p>Using <code>filter()</code> and <code>select()</code>,</p>
<ol style="list-style-type: decimal">
<li>Assign the name “no_practice” to a new object, which is all of the rows in the “stroopdata” dataframe where the <em>practice</em> variable is equal to “no”.</li>
<li>Assign the name “practice” to a new object, which is all of the rows in the “stroopdata” dataframe where the <em>practice</em> variable is equal to “yes”.<br />
</li>
<li>Assign the name “participants” to a new object, which is all of the rows in the “stroopdata” dataframe where the <em>age</em> variable is greater than or equal to 40, but only the <em>id</em>, <em>age</em>, and <em>height</em> variables.</li>
</ol>
<p class="question-end">
</p>
</div>
<div class="solution-begin">
Solution 8<span id="sol-start-147" class="fa fa-plus solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-147&#39;, &#39;sol-start-147&#39;)"></span>
</div>
<div id="sol-body-147" class="solution-body" style="display: none;">
<p>We learned how to do this using <code>[]</code> and <code>$</code>:</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="chap-numeric.html#cb251-1"></a>no_practice &lt;-<span class="st"> </span>stroopdata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(practice <span class="op">==</span><span class="st"> &quot;no&quot;</span>)</span>
<span id="cb251-2"><a href="chap-numeric.html#cb251-2"></a></span>
<span id="cb251-3"><a href="chap-numeric.html#cb251-3"></a>practice &lt;-<span class="st"> </span>stroopdata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(practice <span class="op">==</span><span class="st"> &quot;yes&quot;</span>)</span>
<span id="cb251-4"><a href="chap-numeric.html#cb251-4"></a></span>
<span id="cb251-5"><a href="chap-numeric.html#cb251-5"></a>participants &lt;-<span class="st"> </span>stroopdata <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">40</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(id, age, height)</span></code></pre></div>
</div>
<p class="solution-end">
</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-categorical.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-relationships.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["labs.pdf", "labs.epub"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
