---
title: 'DAPR1 (2122): S2W1 - Lecture Activities'
author: "Department of Psychology<br>University of Edinburgh"
date: ""
output:
  html_document:
    theme: flatly
---


# Question 1

- The population mean $\mu$ is a random variable. True or False?


# Question 2

- The sample mean $\bar x$ varies from sample to sample and has a sampling distribution. True or False?


# Question 3

- You are given the following 95% confidence interval for a population mean reaction time $\mu$: [10.2, 15.6] seconds. Is the following interpretation correct?

There is a 95% chance that $\mu$ is between 10.2 and 15.6 seconds

# Question 4

- You are given the following 95% confidence interval for a population mean reaction time $\mu$: [10.2, 15.6] seconds. Is the following interpretation correct?

The population mean $\mu$ will fall within [10.2, 15.6] minutes 95% of the time.

<br>
<br>

---  

*Scroll down for answers*  
  
---

<div style="margin-bottom:750px;">

</div>

# Answers

## Question 1

False. The population mean is a FIXED but unknown number. It's unknown because we don't have the entire population data. But if we had the data, we could easily compute the mean and find that number - which won't change if you re-compute it.

## Question 2

True. The sample mean is a random variable and has a probability distribution. We can compute probabilities for the sample mean.

## Question 3

No, that interpretation is wrong. The population mean $\mu$ is not a random variable, it's a fixed number (even if unknown). Probability statements can only be written when referred to random variables. The statement presented in Question 3 involves $\mu$ (a fixed but unknown number) and two computed numbers (10.2 and 15.6). There is no random variable involved, hence we cannot speak of probability. Once we compute a confidence interval, the population mean $\mu$ either does or does not fall within it, we simply won't know for sure.

The correct interpretation would be:

> We are 95% confident that the population mean reaction time is between 10.2 and 15.6 minutes.

## Question 4

No, that interpretation is wrong. The correct interpretation would be:

> We are 95% confident that the population mean reaction time is between 10.2 and 15.6 minutes.
