---
title: "FAQs"
theme: zephyr
callout-appearance: simple
callout-icon: false
format:
  html:
    embed-resources: true
---

# R and RStudio

::: {.callout-tip collapse="true"}
## How do I access the RStudio Server online?

**STEP 1.** Try accessing the server directly: go to <https://rstudio.ppls.ed.ac.uk/> and log in with your university account via University Multifactor Authentication (MFA). If prompted, provide your university UUN and password.

**STEP 2.** If Step 1 didn't work, complete [this sign-up form](TODO) and wait for an email from us (this can take up to 3 working days). Once you receive it, try logging in again as in Step 1.
:::

# General

::: {.callout-tip collapse="true"}
## Where do I start?

- Navigate to the course Learn page.

- Read the contents of the 'Course Information' folder.

- Read the 'Assessment and feedback information' page.

- Move on to the weekly folders within each block, they will appear incrementally as the teaching progresses.

- Each weekly folder contains lecture slides, weekly activities (readings, videos, formative quizzes), and workshop exercises.
:::

::: {.callout-tip collapse="true"}
## Where do I find office hours information?

- Navigate to the course Learn page.

- Click 'Course information'.

- Click 'Course contacts and office hours'.

- Office hours information is displayed next to each instructor's name.
:::

::: {.callout-tip collapse="true"}
## Can I change the day and/or time of my workshop?

After Week 3 of Semester 1 it is **not** possible to change workshop day/time.

Before the end of Week 3, please submit a __Group Change Request__. Follow the video guidance available from this website: <https://registryservices.ed.ac.uk/timetabling-examinations/timetabling/continuous-improvement-and-systems/timetablingsystems/timetabling-applications/eventmap-timetabler/timetabler>

The university timetabling unit will process it after a few working days. In the meantime, continue going to your original workshop group.
:::

::: {.callout-tip collapse="true"}
## Is workshop attendance graded?

No, workshop attendance is not graded. However, workshops are where you practise the skills that are assessed in this course, so attending is important.
:::

::: {.callout-tip collapse="true"}
## Do I need to tell someone if I cannot attend a workshop?

No, you don't need to notify anyone if you miss a workshop.
:::

::: {.callout-tip collapse="true"}
## Where can I get help and support?

The following is a list of sources of help and support:

- **Workshops**. Attend the workshops to get help and support from tutors on the content of the workshop exercises, R and RStudio, as well as lecture contents.

- **Office Hours**. Attend office hours to receive one-to-one help on the course materials.

- **Discussion Forum**. Search the discussion forum in case another student had the same question and it was already answered. You can also ask a new question if no one has already asked the same one. Your student peers will be able to provide an answer.

- **Teaching organisation**. The [teaching organisation](mailto:ppls.psych@ed.ac.uk) can advise you on administrative inquiries about your course. This includes issues with submission of assessments, extensions, or exams.

- **Student Adviser**. Your student adviser (you can find their name on MyEd or Euclid) is your first point of contact for generic help and support on matters that are not directly related to your course materials or organisation. They can also refer you to wider University services, such as the Wellbeing adviser, see below.

- **Wellbeing adviser**. The [Wellbeing adviser](https://www.ed.ac.uk/student-wellbeing-service) can provide you with advice on wellbeing-related issues and recommend other specialist services, such as the Student Counselling Service or the Disability and Learning Support Service, who may be able to help you. You can be referred to the Wellbeing adviser by your Student adviser, or you can self-refer at the link above.

- **Cohort lead**. Your cohort lead (name on Euclid) can support you with academic-related questions, reference letters, and general advice on how to make the most of your time at university.

If you email any member of the teaching team, please include the course name (DAPR1) in the subject line, as some instructors teach across multiple courses.
:::

# Skills and assessment

::: {.callout-tip collapse="true"}
## How do I find my grade?

DAPR1 doesn't use grades, it monitors the skills you gain throughout the course. There are 40 skills to demonstrate across the year and they are all listed [in this table](https://uoepsy.github.io/dapr1/2627/misc/skilltable.html). Once you've demonstrated a skill, it's yours forever, and you can attempt a skill as many times as you like with no penalty for trying again (it's your 'best attempt', and not the most recent one, that indicates if you have demonstrated a skill).

Some skills are automatically graded: these are the multiple-choice style questions. These skills will be marked, and your demonstration of the skill will be updated, every time you attempt the skill.

Other skills require manual grading by somebody on the teaching team. These are the short-answer write-up questions, marked with a `*` in the [skills table](https://uoepsy.github.io/dapr1/2627/misc/skilltable.html). We mark these after every 5-week teaching block, so if you submit by the last Friday of a block, it will be marked in the subsequent weeks. You can submit a response to these questions any time you want as the semester goes on, or even submit multiple responses. However, at the end of each block we will grade the most recently submitted response.
:::

::: {.callout-tip collapse="true"}
## How do I see which skills I have/haven't demonstrated?

Check the folder called "My Skills" on Learn. It gives a list of which of the 40 skills you've demonstrated so far.
:::

::: {.callout-tip collapse="true"}
## How do I get feedback on my skills?

Ask a tutor during a workshop, or come to office hours, to talk through your attempt and get feedback on how to improve.
:::

::: {.callout-tip collapse="true"}
## How do I pass DAPR1?

You need to pass both of the following components:

- **Coursework**: Demonstrate at least three quarters of the skills included in the exam, including at least one skill from each category (see Learn for the category breakdown).

- **Exam**: demonstrate at least three quarters of the skills included in the exam, including at least one skill from each category. (see Learn for the category breakdown).

If you fail either component, you'll have another chance at the August reassessment.
:::

::: {.callout-tip collapse="true"}
## How do I apply for extensions or special circumstances?

Extensions don't apply to the coursework skills component: there's no deadline, and you can attempt each skill as many times as you need throughout the year.

For the exam, special circumstances are handled by a separate office of the University. Please follow the steps detailed in [this website](https://www.ed.ac.uk/student-administration/extensions-special-circumstances).
:::

::: {.callout-tip collapse="true"}
## What will the exam look like?

- In person, closed book, hand written with no computer or RStudio.

- A mix of multiple-choice questions and short written-answer questions.

- Each question corresponds to one or more skills, and these will be clearly indicated on the question.

- You'll also be given a checklist so you can tick off which skills you've attempted in the exam.

- The exam covers 20 of the 40 skills, drawn only from the Summarising, Visualising, Analysing, Inferring, and Communicating categories in [the skills table](https://uoepsy.github.io/dapr1/2627/misc/skilltable.html). Programming skills and Reflecting skills are not assessed in the exam.
:::

