<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.262">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>DAPR1 - Probability 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./rd1_09.html" rel="next">
<link href="./rd1_07.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="assets/styles.css">
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR1</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-semester-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Semester 1</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-semester-1">
<li>
    <a class="dropdown-item" href="./1_01_design_and_data.html">
 <span class="dropdown-text">S1-W1: Research design &amp; data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_categorical_data.html">
 <span class="dropdown-text">S1-W2: Categorical data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_numeric_data.html">
 <span class="dropdown-text">S1-W3 Numeric data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_04_relationships.html">
 <span class="dropdown-text">S1-W4: Relationships</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_05_formative_report_a.html">
 <span class="dropdown-text">S1-W5: Formative Report A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_07_prob_theory.html">
 <span class="dropdown-text">S1-W7: Probability Theory</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_08_prob_rules.html">
 <span class="dropdown-text">S1-W8: Probability Rules</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_09_discrete_dist.html">
 <span class="dropdown-text">S1-W9: Discrete Random Variables</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-semester-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Semester 2</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-semester-2"></ul>
</li>
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-readings---sem.-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Readings - Sem. 1</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-readings---sem.-1">
<li>
    <a class="dropdown-item" href="./rd1_01.html">
 <span class="dropdown-text">S1-W1: Getting started with R and RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_02.html">
 <span class="dropdown-text">S1-W2: Categorical data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_03.html">
 <span class="dropdown-text">S1-W3: Numeric data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_04.html">
 <span class="dropdown-text">S1-W4: Relationships</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_05.html">
 <span class="dropdown-text">S1-W5: Functions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_07.html">
 <span class="dropdown-text">S1-W7: Probability 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_08.html">
 <span class="dropdown-text">S1-W8: Probability 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_09.html">
 <span class="dropdown-text">S1-W9: Discrete random variables</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-readings---sem.-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Readings - Sem. 2</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-readings---sem.-2"></ul>
</li>
  <li class="nav-item">
    <a class="nav-link" href="./index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
<div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
                  <a href="" class="quarto-reader-toggle nav-link" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#recap" id="toc-recap" class="nav-link active" data-scroll-target="#recap"><span class="toc-section-number">1</span>  Recap</a></li>
  <li><a href="#general-addition-rule" id="toc-general-addition-rule" class="nav-link" data-scroll-target="#general-addition-rule"><span class="toc-section-number">2</span>  General addition rule</a></li>
  <li><a href="#conditional-probability" id="toc-conditional-probability" class="nav-link" data-scroll-target="#conditional-probability"><span class="toc-section-number">3</span>  Conditional probability</a></li>
  <li><a href="#general-multiplication-rule" id="toc-general-multiplication-rule" class="nav-link" data-scroll-target="#general-multiplication-rule"><span class="toc-section-number">4</span>  General multiplication rule</a></li>
  <li><a href="#independence" id="toc-independence" class="nav-link" data-scroll-target="#independence"><span class="toc-section-number">5</span>  Independence</a></li>
  <li><a href="#bayes-rule-reversing-the-conditioning" id="toc-bayes-rule-reversing-the-conditioning" class="nav-link" data-scroll-target="#bayes-rule-reversing-the-conditioning"><span class="toc-section-number">6</span>  Bayes’ rule: reversing the conditioning</a></li>
  <li><a href="#glossary" id="toc-glossary" class="nav-link" data-scroll-target="#glossary"><span class="toc-section-number">7</span>  Glossary</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Probability 2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="recap" class="level2" data-number="1"><h2 data-number="1" class="anchored" data-anchor-id="recap">
<span class="header-section-number">1</span> Recap</h2>
<p>Let’s recap the probability rules discussed last week.</p>
<p><strong>Rule 1: Probability assignment rule</strong></p>
<p>The probability of an impossible event (an event which never occurs) is 0 and the probability of a certain event (an event which always occurs) is 1.</p>
<p>Hence, we have that <em>the probability is a number between 0 and 1</em>: <span class="math display">\[\text{for any event }A, \\ 0 \leq P(A) \leq 1\]</span></p>
<p><strong>Rule 2: Total probability rule</strong></p>
<p>If an experiment has a single possible outcome, it is not random as that outcome will happen with certainty (i.e.&nbsp;probability 1).</p>
<p>When dealing with two or more possible outcomes, we need to be sure to distribute the entire probability among all of the possible outcomes in the sample space <span class="math inline">\(S\)</span>.</p>
<p>The sample space must have probability 1: <span class="math display">\[P(S) = 1\]</span></p>
<p>It must be that the will observe one of the outcomes listed within the collection of all possible outcomes of the experiment.</p>
<p><strong>Rule 3: Complement rule</strong></p>
<p>If the probability of observing the face “2” in a die is 1/6 = 0.17, what’s the probability of not observing the face “2”? It must be 1 - 1/6 = 5/6 = 0.83.</p>
<p>If <span class="math inline">\(A = \{2\}\)</span>, the event not A is written <span class="math inline">\(\sim A\)</span>, which is a shortcut for <span class="math inline">\(S\)</span> without <span class="math inline">\(A\)</span>, that is <span class="math inline">\(\{1, 3, 4, 5, 6\}\)</span>.</p>
<p><span class="math display">\[P(\sim A) = 1 - P(A)\]</span></p>
<p><strong>Rule 4: Addition rule for disjoint events</strong></p>
<p>Suppose the probability that a randomly picked person in a town is <span class="math inline">\(A\)</span> = “a high school student” is <span class="math inline">\(P(A) = 0.3\)</span> and that the probability of being <span class="math inline">\(B\)</span> = “a university student” is <span class="math inline">\(P(B) = 0.5\)</span>.</p>
<p>What is the probability that a randomly picked person from the town is <em>either</em> a high school student <em>or</em> a university student? We write the event “either A or B” as <span class="math inline">\(A \cup B\)</span>, pronounced “A union B”.</p>
<p>If you said 0.8, because it is 0.3 + 0.5, then you just applied the <em>addition rule</em>: <span class="math display">\[
\text{If }A \text{ and } B \text{ are mutually exclusive events,}\\
P(A \cup B) = P(A) + P(B)
\]</span></p>
<p><strong>Rule 5: Multiplication rule for independent events</strong></p>
<p>We saw that probability of observing an even number (<span class="math inline">\(E\)</span>) when throwing a die is 0.5.</p>
<p>You also know that the probability of observing heads (<span class="math inline">\(H\)</span>) when throwing a fair coin is 0.5.</p>
<p>What’s the probability of observing an even number and heads (that is, <span class="math inline">\(E\)</span> <em>and</em> <span class="math inline">\(H\)</span>, written <span class="math inline">\(E \cap H\)</span>) when throwing both items together?</p>
<p>The rule simply says that in this case we multiply the two probabilities together: 0.5 * 0.5 = 0.25.</p>
<p>The <em>multiplication rule for independent events</em> says: <span class="math display">\[
\text{If }A \text{ and } B \text{ are independent events,}\\
P(A \cap B) = P(A) \times P(B)
\]</span></p>
</section><section id="general-addition-rule" class="level2" data-number="2"><h2 data-number="2" class="anchored" data-anchor-id="general-addition-rule">
<span class="header-section-number">2</span> General addition rule</h2>
<p>Consider throwing a six-sided die, for which we already know that the sample space is <span class="math inline">\(S = \{1, 2, 3, 4, 5, 6\}\)</span>. What’s the probability of observing an odd number <em>or</em> a number which is less than 4?</p>
<p>The relevant events are:</p>
<ul>
<li><span class="math inline">\(A = \text{result is odd} = \{1, 3, 5\}\)</span></li>
<li><span class="math inline">\(B = \text{result is less than four} = \{1, 2, 3\}\)</span></li>
</ul>
<p>and we know that:</p>
<ul>
<li><span class="math inline">\(P(A) = 3/6 = 0.5\)</span></li>
<li><span class="math inline">\(P(B) = 3/6 = 0.5\)</span></li>
</ul>
<p>However, the probability of <span class="math inline">\(A\)</span> <em>or</em> <span class="math inline">\(B\)</span>, written <span class="math inline">\(P(A \cup B)\)</span>, is not simply <span class="math inline">\(P(A) + P(B)\)</span>, because the events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are not disjoint; they overlap. The outcomes 1 and 3 play a crucial role here as they are both odd and are less than four, i.e.&nbsp;they are in both sets. They are both in <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, which places them in the intersection of the two circles.</p>
<p>The diagram below represents the sample space as <span class="math inline">\(S\)</span>. Notice that the outcomes 4 and 6 are neither odd nor less than four, so they sit outside both circles.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/prob/venn_die.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>The reason we can’t simply add the probabilities of <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> is that we would count the outcomes 1 and 3 twice. If we did add the two probabilities, we could compensate by subtracting the probability of the outcomes 1 and 3.</p>
<p><span class="math display">\[
\begin{aligned}
P(\text{odd or less than 4}) &amp;= P(\text{odd}) + P(\text{less than 4}) - P(\text{odd and less than 4}) \\
&amp;= P(\{1, 3, 5\}) + P(\{1, 2, 3\}) - P(\{1, 3\}) \\
&amp;= 3/6 + 3/6 - 2/6 \\
&amp;= 0.667
\end{aligned}
\]</span></p>
<p>This is true in general and is called the <strong>general addition rule</strong>, which does not require disjoint events. Consider two generic events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> such that</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/prob/venn_gen_add.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>Then, the probability of observing <span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span> is: <span class="math display">\[
P(A \cup B) = P(A) + P(B) - P(A \cap B)
\]</span></p>
<p>Intuitively, <span class="math inline">\(P(A) + P(B)\)</span> counts <span class="math inline">\(A \cap B\)</span> twice, so we have to subtract <span class="math inline">\(P(A \cap B)\)</span> to make the net number of times <span class="math inline">\(A \cap B\)</span> is counted equal to 1.</p>
<p>When the two events have no outcomes in common, i.e.&nbsp;<span class="math inline">\(P(A \cap B) = 0\)</span> as the two events can’t happen together, the general addition rule reduces to the addition rule for disjoint events.</p>
<div class="callout-note callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
TERMINOLOGY
</div>
</div>
<div class="callout-body-container callout-body">
<blockquote class="blockquote">
<p><strong>Would you like fruit or dessert?</strong></p>
</blockquote>
<p>Everyday language can be ambiguous. It’s not clear if by answering “yes” to the question above our choice is only one of the two options, or we can actually have both.</p>
<p>Typically, everyday language uses “or” meaning the exclusive version. That is, you can have one or the other, but not both. In other words, you can have fruit or dessert, but not both.</p>
<p>When talking about probability, being imprecise and ambiguous can get us into trouble. For this reason, we will here define once for all what we mean by “or” in a mathematical sense.</p>
<p>In statistics, when we say “or” we always mean the inclusive version. In other words, the probability of <span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span> means the probability of either <span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span> or both.</p>
</div>
</div>
<p>Let’s consider another example. Suppose that 25% of people have an electric scooter, 29% of people have a bike, and 12% of people own both. What is the probability that someone owns an electric scooter or a bike?</p>
<p>This question concerns the following two events</p>
<ul>
<li><span class="math inline">\(A = \text{owning an electric scooter}\)</span></li>
<li><span class="math inline">\(B = \text{owning a bike}\)</span></li>
</ul>
<p>and we are told that</p>
<ul>
<li><span class="math inline">\(P(A) = 0.25\)</span></li>
<li><span class="math inline">\(P(B) = 0.29\)</span></li>
<li><span class="math inline">\(P(A \cap B) = 0.12\)</span></li>
</ul>
<p>Clearly, <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are not mutually exclusive (or disjoint) events. Having a scooter doesn’t exclude owning a bike, and vice versa. In fact, the problem statements tells us exactly the percentage of people having <strong>both</strong> an electric scooter and a bike, 12%.</p>
<p>So… how do we calculate the probability of owning an electric scooter or a bike?</p>
<p>If we simply did <span class="math inline">\(P(A) + P(B)\)</span>, we would count twice those having both a scooter and a bike. Hence, we need to subtract <span class="math inline">\(P(A \cap B)\)</span>: <span class="math display">\[
\begin{aligned}
P(A \cup B) &amp;= P(A) + P(B) - P(A \cap B) \\
&amp;= 0.25 + 0.29 - 0.12 \\
&amp;= 0.42
\end{aligned}
\]</span></p>
</section><section id="conditional-probability" class="level2" data-number="3"><h2 data-number="3" class="anchored" data-anchor-id="conditional-probability">
<span class="header-section-number">3</span> Conditional probability</h2>
<p>The following <em>contingency table</em> displays the counts of passengers who did or did not survive the Titanic sinking by travelling class.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1"></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Survived</div></th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1"></th>
</tr>
<tr>
<th style="text-align:left;"> Class </th>
   <th style="text-align:right;"> No </th>
   <th style="text-align:right;"> Yes </th>
   <th style="text-align:right;"> Total </th>
  </tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;"> 1st </td>
   <td style="text-align:right;"> 122 </td>
   <td style="text-align:right;"> 203 </td>
   <td style="text-align:right;"> 325 </td>
  </tr>
<tr>
<td style="text-align:left;"> 2nd </td>
   <td style="text-align:right;"> 167 </td>
   <td style="text-align:right;"> 118 </td>
   <td style="text-align:right;"> 285 </td>
  </tr>
<tr>
<td style="text-align:left;"> 3rd </td>
   <td style="text-align:right;"> 528 </td>
   <td style="text-align:right;"> 178 </td>
   <td style="text-align:right;"> 706 </td>
  </tr>
<tr>
<td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 817 </td>
   <td style="text-align:right;"> 499 </td>
   <td style="text-align:right;"> 1316 </td>
  </tr>
</tbody>
</table>
</div>
</div>
<p>You already encountered contingency tables when studying the relationship between two categorical variables in <a href="1_04_relationships.html#categorical-and-categorical">week 4</a>.</p>
<p>If you divide the frequency table by the total number of passengers, 1316, you obtain a table of relative frequencies. It is just a small step from these relative frequencies to probabilities.</p>
<p>Let;s focus on the Titanic survival study and make the sample space just the set of these 1316 passengers. If we select a passenger at random from this study, the probability we select a first class passenger is just the corresponding relative frequency (since we are equally likely to select any of the 1316 passengers). There are 325 first class passengers in the data out of a total of 1316, giving a probability of <span class="math display">\[
P( \text{1st} ) = \frac{325}{1316} = 0.247
\]</span> The same method works for more complicated events like intersections. For example, what’s the probability of selecting a 1st class passenger who survived? Well, 203 first class passengers survived, so the probability is <span class="math display">\[
P( \text{1st} \cap \text{survived} ) = \frac{203}{1316} = 0.154
\]</span></p>
<p>The probability of selecting a passenger who survived is <span class="math display">\[
P( \text{survived} ) = \frac{499}{1316} = 0.379
\]</span> What if we are given the information that the selected passenger was in first class? Would that change the probability that the selected passenger survived? You bet it would!</p>
<p>When we restrict our focus to first class passengers, we look only at the row of the table where “Class” is “1st”. Of the 325 first class passengers, only 203 of them said survived. We write the probability that a selected passenger survived given that we have selected a first class passenger as <span class="math display">\[
P(\text{survived} \mid \text{1st}) = \frac{203}{325} = 0.625
\]</span></p>
<p>Now, imagine dividing numerator and denominator by the total, 1316: <span class="math display">\[
\begin{aligned}
P(\text{survived} \mid \text{1st})
= \frac{203 / 1316}{325 / 1316}
= \frac{P(\text{1st} \cap \text{survived})}{P(\text{1st})}
\end{aligned}
\]</span></p>
<p>A probability that takes into account a given <em>condition</em>, such as being a first class passenger, is called a <em>conditional probability.</em> For generic events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, we write the conditional probability as <span class="math inline">\(P(B | A)\)</span> and pronounce it “the probability of <span class="math inline">\(B\)</span> given <span class="math inline">\(A\)</span>”.</p>
<p>Suppose we are told that the event <span class="math inline">\(A\)</span> with <span class="math inline">\(P(A) &gt; 0\)</span> occurs. The <strong>conditional probability</strong> of <span class="math inline">\(B\)</span> given <span class="math inline">\(A\)</span> is given by: <span class="math display">\[
P(B | A) = \frac{P(A \cap B)}{P(A)}
\]</span> Intuitively, we need to divide the formula by <span class="math inline">\(P(A)\)</span> to make sure that <span class="math inline">\(P(A|A) = 1\)</span>.</p>
<p>The formula wouldn’t work if <span class="math inline">\(P(A) = 0\)</span>, but this makes sense as we couldn’t be told that <span class="math inline">\(A\)</span> occurred if it was an impossible event!</p>
<div class="callout-note callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
IMPORTANT NOTE
</div>
</div>
<div class="callout-body-container callout-body">
<p>The conditional probability <span class="math inline">\(P(\text{some event} | A)\)</span> satisfies the standard rules of probability. You can think of it as the same as <span class="math inline">\(P(\text{some event})\)</span> but after having replaced the sample space from <span class="math inline">\(S\)</span> to <span class="math inline">\(A\)</span>, which is the event that we have been told happened. As the event happened, we know that the new sample space is now <span class="math inline">\(A\)</span>, so that <span class="math inline">\(P(A) = 1\)</span>.</p>
<p>To see this, remember that <span class="math inline">\(P(S) = 1\)</span> and we can then rewrite</p>
<p><span class="math display">\[P(A) = \frac{P(A)}{1} = \frac{P(A)}{P(S)} = \frac{P(A \cap S)}{P(S)} = P(A | S)\]</span></p>
<p>The rule <span class="math inline">\(P(A) + P({} \sim A) = 1\)</span> can be written as <span class="math inline">\(P(A | S) + P({} \sim A | S) = 1\)</span>.</p>
<p><strong>Complement rule for conditional probabilities</strong><br>
In general, according to the complement rule, <span class="math inline">\(P({}\sim B|A) = 1 - P(B|A)\)</span>.</p>
<p><strong>Product rule for conditionally independent events</strong><br>
We also have a similar rule for independence. Two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are conditionally independent given <span class="math inline">\(C\)</span> if:</p>
<p><span class="math display">\[
P(A \cap B | C) = P(A | C) \times P(B | C)
\]</span></p>
</div>
</div>
<p>Consider the following plot:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="rd1_08_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>On the y-axis we see the conditional probabilities of survival given the passenger class. That is <span class="math inline">\(P(\text{survived} | \text{1st}) = 0.62\)</span>, <span class="math inline">\(P(\text{survived} | \text{2nd}) = 0.41\)</span>, and <span class="math inline">\(P(\text{survived} | \text{3rd}) = 0.25\)</span>.</p>
<p>The x-axis displays the probability of a randomly selected passenger to be in each travelling class. For example, <span class="math inline">\(P(\text{1st}) = 0.25\)</span>, <span class="math inline">\(P(\text{2nd}) = (0.46 - 0.25) = 0.21\)</span>, and <span class="math inline">\(P(\text{3rd}) = 1 - (P(\text{1st}) + P(\text{2nd})) = 1 - 0.25 - 0.21 = 1 - 0.46 = 0.54\)</span></p>
</section><section id="general-multiplication-rule" class="level2" data-number="4"><h2 data-number="4" class="anchored" data-anchor-id="general-multiplication-rule">
<span class="header-section-number">4</span> General multiplication rule</h2>
<p>Consider two generic events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>. Before, we saw that <span class="math display">\[
P(B | A) = \frac{P(A \cap B)}{P(A)}
\]</span></p>
<p>Rearranging the conditional probability formula we obtain the <strong>general multiplication rule</strong>: <span class="math display">\[
P(A \cap B) = P(A) P(B|A)
\]</span></p>
<p>If you were to start from <span class="math inline">\(P(A | B)\)</span> you would reach to the equivalent version: <span class="math display">\[
P(A \cap B) = P(B) P(A|B)
\]</span></p>
</section><section id="independence" class="level2" data-number="5"><h2 data-number="5" class="anchored" data-anchor-id="independence">
<span class="header-section-number">5</span> Independence</h2>
<p>We say that two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent, if knowing that one occurred doesn’t change the probability of the other occurring:</p>
<p><span class="math display">\[
P(B|A) = P(B)
\]</span></p>
<p>From this we have that</p>
<p><span class="math display">\[
P(B) = P(B|A) = \frac{P(A \cap B)}{P(A)}
\]</span></p>
<p>Leading to</p>
<p><span class="math display">\[
P(A \cap B) = P(A) P(B)
\]</span> At the same time,</p>
<p><span class="math display">\[
P(A|B) = \frac{P(A \cap B)}{P(B)} = \frac{P(A) P(B)}{P(B)} = P(A)
\]</span></p>
<p>So, we have three <strong>equivalent</strong> definitions of independent events! If one holds, the remaining ones hold as well. Two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent if and only if <span class="math display">\[
\begin{aligned}
P(A | B) &amp;= P(A) \\
P(B | A) &amp;= P(B) \\
P(A \cap B) &amp;= P(A) P(B)
\end{aligned}
\]</span></p>
<div class="callout-note callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
In pictures: Independence vs Dependence
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Independence happens when the probability of “Survived = Yes” is the same regardless of whether the passenger was in 1st, 2nd, or 3rd class.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="rd1_08_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>Perfect dependence happens when knowing the passenger class leads to a perfect prediction of whether a passenger survived or not.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="rd1_08_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>Note that, for independent events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> such that <span class="math inline">\(P(B | A) = P(B)\)</span>, the general multiplication rule reduces to the multiplication rule for independent events: <span class="math display">\[
P(A \cap B) = P(B|A)P(A) = P(B) P(A)
\]</span></p>
</section><section id="bayes-rule-reversing-the-conditioning" class="level2" data-number="6"><h2 data-number="6" class="anchored" data-anchor-id="bayes-rule-reversing-the-conditioning">
<span class="header-section-number">6</span> Bayes’ rule: reversing the conditioning</h2>
<p>Suppose we have <span class="math inline">\(P(A | B)\)</span> but we are interested in <span class="math inline">\(P(B | A)\)</span>. That is, we want to reverse the conditioning.</p>
<p>By applying the rule for conditional probability and the general multiplication rule, we have that: <span class="math display">\[
P(B | A) = \frac{P(A \cap B)}{P(A)} = \frac{P(A|B)P(B)}{P(A)}
\]</span></p>
</section><section id="glossary" class="level2" data-number="7"><h2 data-number="7" class="anchored" data-anchor-id="glossary">
<span class="header-section-number">7</span> Glossary</h2>
<ul>
<li>
<strong>General addition rule</strong>. For any events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, <span class="math inline">\(P(A \cup B) = P(A) + P(B) - P(A \cap B)\)</span>.</li>
<li>
<strong>General multiplication rule</strong>. For any events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, <span class="math inline">\(P(A \cap B) = P(B|A)P(A) = P(A | B) P(B)\)</span>.</li>
<li>
<strong>Independent events</strong>. Two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent if and only if <span class="math inline">\(P(A \cap B) = P(A) P(B)\)</span>
</li>
<li>
<strong>Bayes’ rule</strong>. <span class="math inline">\(P(B | A) = \frac{P(A | B)P(B)}{P(A)}\)</span>
</li>
</ul>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./rd1_07.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">S1-W7: Probability 1</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./rd1_09.html" class="pagination-link">
        <span class="nav-page-text">S1-W9: Discrete random variables</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2019-2022 <a href="https://www.ed.ac.uk/">The University of Edinburgh</a>. Site licensed under the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPLv3</a> license.</div>   
  </div>
</footer>


</body></html>