project:
  type: website
  render: 
    - "*.qmd"
    - "!working/*"
    - "!template.qmd"
  output-dir: ./wipdocs/

website:
  title: "DAPR1 Workshops"
  navbar: 
    background: primary
    search: true
    left:
      - text: "Block 1: Exploratory Data Analysis"
        menu: 
          - 01ex.qmd
          - 02ex.qmd
          - 03ex.qmd
          - 04ex.qmd
          - 05ex.qmd
      - text: "Block 2: Inference"
        menu: 
          - 07ex.qmd
          - 08ex.qmd
      - text: "Block 3: Associations and Basic Tests"
      - text: "Block 4: The Linear Model"

format:
  html:
    page-layout: full
    theme: 
      - united
      - assets/style-workshops.scss
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    link-citations: true
    number-sections: false
    code-copy: true
