project:
  type: website
  render: 
    - "*.qmd"
    - "!working/*"
  output-dir: ./wip/

website:
  title: "DAPR1 Workshops"
  navbar: 
    background: primary
    search: true
    left:
      - text: "Block 1: Intro & Descriptives"
        menu: 
          - 01ex.qmd
      - text: "Block 2"
        # menu: 
          # - 07ex.qmd
      - text: "Block 3"
      - text: "Block 4"

format:
  html:
    page-layout: full
    theme: 
      - united
      - assets/style-workshops.scss
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    link-citations: true
    number-sections: false
    code-copy: true
