---
title: "WX: Title"
params: 
    SHOW_SOLS: TRUE
    TOGGLE: TRUE
format: html
---

```{r}
#| include: false
library(tidyverse)
source('assets/dropdowns.R')
source('assets/setup.R')
```

<!-- MAX 5 QUESTIONS -->
<!-- make each question ~10 minute work -->
<!-- MAX 5 QUESTIONS -->
<!-- MAX 5 QUESTIONS -->

:::frame
Pick someone new to be the driver this week. If everyone in the group has already had a week as the driver, start going round again!  

The driver will type the code. The rest of you are navigators, you need to tell the driver where to go (i.e., what to type!). 

Driver instructions:

1. Log in to the bigger screen at your table
2. Open [RStudio Server](https://rstudio.ppls.ed.ac.uk){target="_blank"}
3. Listen to your navigators

Navigator instructions:

1. Tell your driver where to go (i.e., what to type)!

:::

`r qbegin(qcounter())`

:::flash
🗂️
See [flashcard](https://uoepsy.github.io/dapr1/2627/flashcards/){target="_blank"} flash card.
:::

::: {.callout-tip collapse="true"}
#### Hint

if needed

:::

`r qend()`
`r solbegin(show=params$SHOW_SOLS, toggle=params$TOGGLE)`


`r solend()`



`r qbegin(qcounter())`

:::flash
🗂️
See [flashcard](https://uoepsy.github.io/dapr1/2627/flashcards/){target="_blank"} flash card.
:::

::: {.callout-tip collapse="true"}
#### Hint

if needed

:::

`r qend()`
`r solbegin(show=params$SHOW_SOLS, toggle=params$TOGGLE)`


`r solend()`



`r qbegin(qcounter())`

:::flash
🗂️
See [flashcard](https://uoepsy.github.io/dapr1/2627/flashcards/){target="_blank"} flash card.
:::

::: {.callout-tip collapse="true"}
#### Hint

if needed

:::

`r qend()`
`r solbegin(show=params$SHOW_SOLS, toggle=params$TOGGLE)`


`r solend()`



`r qbegin(qcounter())`

:::flash
🗂️
See [flashcard](https://uoepsy.github.io/dapr1/2627/flashcards/){target="_blank"} flash card.
:::

::: {.callout-tip collapse="true"}
#### Hint

if needed

:::

`r qend()`
`r solbegin(show=params$SHOW_SOLS, toggle=params$TOGGLE)`


`r solend()`



`r qbegin(qcounter())`

:::flash
🗂️
See [flashcard](https://uoepsy.github.io/dapr1/2627/flashcards/){target="_blank"} flash card.
:::

::: {.callout-tip collapse="true"}
#### Hint

if needed

:::

`r qend()`
`r solbegin(show=params$SHOW_SOLS, toggle=params$TOGGLE)`


`r solend()`




:::frame
__Finishing up__  

Once you've finished, don't forget to: 

1. Save your R script
2. Post the R script to the group discussion space on Learn, to ensure that everyone has access to it! (For step-by-step instructions on how to do this, click [here](00serverfiles.html){target="_blank"})  


:::








