---
title: 'dapR1: More Probability Activities - 3'
author: "Department of Psychology<br>University of Edinburgh"
date: ""
output:
  html_document:
    theme: flatly
---


Jedi Master Plo Koon hypothesises that there is a relationship between being a Sith and taking a holiday on the planet Korriban. Here is a contingency table showing the relationship between sith and non sith: 

|          | Sith    | Non-sith  | Marginal |
|----------|---------|-----------|----------|
| Korriban | 17      | 13        | 30       |
| Other    |  6      | 64        | 70       |
| Marginal | 23      | 77        | 100      |


# Question 1

Calculate the expected probabilities if being a Sith and holidaying on Korriban are independent. 

# Question 2

Use the marginal probabilities to calculate the expected probabilities in the contingency table if the two variables are independent. 

# Question 3

Compare the expected to the actual probability values. Does Mater Plo Koon's hypothesis that the two variables are not independent seem to hold any value? 

<br>
<br>

---  

*Scroll down for answers*  
  
---

<div style="margin-bottom:750px;">

</div>

# Answers 

1. We can calculate the marginal probabilities by taking each marginal value and dividing by the total:  

    |          | Sith    | Non-sith | Marginal |
    |----------|---------|----------|----------|
    | Korriban | 17      | 13        | 30/100  |
    | Other    |  6      | 64        | 70/100  |
    | Marginal | 23/100  | 77/100    | 100     |
    
    or 
    
    |          | Sith    | Non-sith | Marginal |
    |----------|---------|----------|----------|
    | Korriban | 17      | 13        | .3      |
    | Other    |  6      | 64        | .7      |
    | Marginal | .23     | .77       | 1.00    |

2. We can use the simple multiplication rule if the variables are independent.  

    |          | Sith          | Non-sith     | Marginal |
    |----------|---------------|--------------|----------|
    | Korriban | $.3*.23=0.07$ | $.3*.77=.23$ | .3       |
    | Other    | $.7*.23=.16$  | $.77*.7=.54$ | .7       |
    | Marginal | .23           | .77          | 1.00     |

3. Compare the table of expected to actual probabilites. Specifically look at the cells for Sith taking a holiday on Korriban. If being a Sith and taking a holiday on Korriban were indeed independent, then the $p(K|S) = p(K)$. However, the $p(K|S)=.74$. It sure seems like Plo Koon might be on to something! 



