project:
  type: website
  render: 
    - "*.qmd"
  output-dir: ./wip/

website:  
  title: "DAPR1 Flashcards"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - index.qmd
              
      - section: "Block 1"  # EDA
        contents:
          - section: "Skills"
            contents:
             - skills/x.qmd
          - section: "How to"
            contents:
             - block1/packages.qmd
             - block1/vectors.qmd
             - block1/functions.qmd
             - block1/read-data.qmd
             - block1/pipe.qmd
             - block1/mutate.qmd
             - block1/factor.qmd
             - block1/freq-table.qmd
             - block1/intro-ggplot.qmd
             - block1/central-tendency.qmd
             - block1/variability.qmd
             # - block1/cat-summarise.qmd
             # - block1/cat-visualise.qmd
             # - block1/num-summarise.qmd
             # - block1/num-visualise.qmd
             # - block1/bivariate-summ-vis.qmd
             # - block1/functions-math.qmd
          # - section: "Worked examples"
          #   contents:
          #    - examples/rsch-design-data.qmd
          #    - examples/categorical-data.qmd
          #    - examples/numeric-data.qmd
          #    - examples/relationships.qmd
              
      - section: "Block 2"  # Inference
        contents:
          - section: "Skills"
            contents:
             - skills/x.qmd
          - section: "Concepts"
            contents:
             - block2/transform.qmd
             - block2/zscores.qmd
             - block2/normal-distribution.qmd
             - block2/prob-auc.qmd
             - block2/sampling-distribution.qmd
             - block2/bias-precision.qmd
             - block2/central-limit-theorem.qmd
             - block2/standard-error.qmd
             - block2/pop-vs-sample.qmd
             - block2/confint.qmd
             - block2/pvalues.qmd
             - block2/type-i-ii-errors.qmd
             - block2/assumptions.qmd
             - block2/cohens-d.qmd
             - block2/one-sample-t.qmd
          - section: "Worked examples"
            contents:
             - examples/sampling-distribution-gestation.qmd
             - examples/confint.qmd
             - examples/hypothesis-testing.qmd
             - examples/ttest-effsize-assumptions.qmd
             - examples/power.qmd
             - examples/one-sample-t-examples.qmd
              
      - section: "Block 3"  # Tests
        contents:
          - section: "Skills"
            contents:
             - skills/x.qmd
          - section: "Concepts"
            contents:
             - block3/associations.qmd
             - block3/paired-t.qmd
             - block3/indep-t.qmd
             - block3/chisq.qmd
             - block3/cor.qmd
          - section: "Worked examples"
            contents:
             - examples/paired-t-example.qmd
             - examples/indep-t-example.qmd
             - examples/chisq-example.qmd
             - examples/cor-example.qmd
          
      - section: "Block 4"  # LM
        contents:
          - section: "Skills"
            contents:
             - skills/x.qmd
          - section: "Concepts"
            contents:
             - block4/intro-lm.qmd
             - block4/Ftest.qmd
             - block4/Rsq.qmd
             - block4/coefs.qmd
             - block4/all-lm.qmd
          - section: "Worked examples"
            contents:
             - examples/lm-example.qmd
             
      - section: "More resources"
        contents:
          - resources/x.qmd
      
format:
  html:
    toc: true
    toc_float: true
    link-citations: true
    theme: 
      - cosmo
      - assets/style-readings.scss
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


