project:
  type: website
  render: 
    - "*.qmd"
  output-dir: ./wip/

website:  
  title: "DAPR1 Flashcards"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - index.qmd
      - section: "Block 1"
        contents:
          - section: "Skills"
            contents:
             - block1/x.qmd
          - section: "How to"
            contents:
             - block1/start-rstudio.qmd
             - block1/packages.qmd
             - block1/rstudio-glossary.qmd
             - block1/vectors.qmd
             - block1/read-data.qmd
             - block1/functions.qmd
              
      - section: "Block 2"
        contents:
          - section: "Skills"
            contents:
             - block1/x.qmd
          - section: "How to"
            contents:
             - block1/x.qmd
              
      - section: "Block 3"
        contents:
          - section: "Skills"
            contents:
             - block1/x.qmd
          - section: "How to"
            contents:
             - block1/x.qmd
          
      - section: "Block 4:"
        contents:
          - section: "Skills"
            contents:
             - block1/x.qmd
          - section: "How to"
            contents:
             - block1/x.qmd
          
      - section: "More resources"
        contents:
          - resources/x.qmd

format:
  html:
    toc: true
    toc_float: true
    link-citations: true
    theme: 
      - cosmo
      - assets/style-readings.scss
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


