project:
  type: website
  render: 
    - "*.qmd"
    - "!block2/"
    - "!block3/"
    - "!block4/"
    - "!uncategorised/"
    - "!skills/"
    - "!examples/"
  output-dir: ./wip/

website:  
  title: "DAPR1 Flashcards"
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - index.qmd
              
      - section: "Block 1: Exploratory Data Analysis"
        contents:
         - block1/packages.qmd
         - block1/vectors.qmd
         - block1/functions.qmd
         - block1/read-data.qmd
         - block1/pipe.qmd
         - block1/mutate.qmd
         - block1/factor.qmd
         - block1/freq-table.qmd
         - block1/intro-ggplot.qmd
         - block1/central-tendency.qmd
         - block1/variability.qmd
              
      - section: "Block 2: Introduction to Inference"
        # contents:
              
      - section: "Block 3: Common Statistical Tests"  # Tests
        # contents:
          
      - section: "Block 4: The Move to Modelling"  # LM
        # contents:
             
      # - section: "More resources"
      #   contents:
      #     - resources/dapr1_ggplot_formatting.qmd        # EP: already in block1/intro-ggplot.qmd
      #     - resources/dapr1_descriptives_formatting.qmd  # EP: no Rmd so not needed
      
format:
  html:
    toc: true
    toc_float: true
    link-citations: true
    theme: 
      - cosmo
      - assets/style-readings.scss
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false


