---
title: "DAPR1 flash cards (2026/27)"

---

These flash cards are here to complement your lecture and workshop materials by offering additional guidance and examples on key concepts/topics.

You can use the flash cards as supporting documents whilst you work through the workshop exercises.
They might also help you revise and keep concepts fresh.


::: {.callout-caution collapse="false"}
#### Find extra content down rabbit holes!

If you want to dive deeper or work toward a more complete understanding of certain topics, we've added **"rabbit holes"** (like this one!) throughout the flash cards.

**We will not assess any content introduced in the rabbit holes.
If you only want to know the basics, you can safely skip them.**
But if you're interested in learning more (or if you find yourself doing more complex data analysis in the future), you might find the extra information useful.
:::



These flash cards have been developed by [Elizabeth Pankratz](https://edwebprofiles.ed.ac.uk/profile/elizabethpankratz){target="_blank"}, [Umberto Noè](https://edwebprofiles.ed.ac.uk/profile/umberto-noe){target="_blank"}, and [Josiah King](https://edwebprofiles.ed.ac.uk/profile/josiahking) (who also drew the cute rabbit)!



### Tip: Develop your own glossary

A good understanding of R functions is essential for your success in the DAPR curriculum and the degree more generally. We strongly recommend you get into the habit of keeping track of any new R function that you encounter and write a short description of what the function does and which package it comes from. You could save this into a Word or Excel file.
You should get into the habit of updating that document as you encounter new R functions. 
Here's an example to help you get started:

| Function   | Use and package |
|:-----------|:--------------|
| `<-`       | Assignment operator. Stores the value on the right into the named object on the left |
| `read_csv` | For reading comma separated value files. Part of tidyverse package |
| `View`     | Opens a spreadsheet-like data viewer in RStudio. Base R function |
| `head`     | Shows the first 6 rows of a dataset (by default). Base R function |
| `nrow`     | Returns the number of rows. Base R function |
| `ncol`     | Returns the number of columns. Base R function |
| `dim`      | Returns the dimensions (rows and columns). Base R function |
| `glimpse`  | Similar to `str`. Displays an overview of the data variables with their types. Part of tidyverse package |
| `str`      | Similar to `glimpse`. Displays an overview of the data variables with their types. Base R function |
| `summary`  | Produces summary statistics. Base R function |
| `factor`   | Creates or modifies a variable into a categorical one (factor) with levels. Base R function |
