---
title: 'dapR1 (week 4): Activity1'
author: "Alex Doumas"
date: ""
output: html_document
---


# Relationships 1

I hypothesise that playing a particular strategy video game causes an increase in reasoning skills. I decide I want to test his hypothesis, so I set up an experiment where people play the game for different amounts of time and I measure whether their reasoning ability increases. The indepdent variable is?

a. time playing the video game
b. performance on the reasoning task
c. the kind of game (strategy)
d. reasoning skill before playing the game


# Relationships 2

In the experiment from question 1, what is the dependent variable? 
(Just in case you don't remember the experiment, here is the description again: I hypothesise that playing a particular strategy video game causes an increase in reasoning skills. I decide I want to test his hypothesis, so I set up an experiment where people play the game for different amounts of time and I measure whether their reasoning ability increases.)

a. time playing the video game
b. performance on the reasoning task
c. the kind of game (strategy)
d. reasoning skill before playing the game


# Relationships 3

In the experiment from question 1, what is a potential covariate? 
(Just in case you don't remember the experiment, here is the description again: I hypothesise that playing a particular strategy video game causes an increase in reasoning skills. I decide I want to test his hypothesis, so I set up an experiment where people play the game for different amounts of time and I measure whether their reasoning ability increases.)

a. time playing the video game
b. performance on the reasoning task
c. the kind of game (strategy)
d. reasoning skill before playing the game


# Answers
1. a
2. b
3. d



