---
title: "Block 4: Weeks 1-3 Reaction Time Report"
output: bookdown::pdf_document2
toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r include = FALSE}
######## LOAD LIBRARIES & DATA ######## 

#load packages
library(tidyverse)
library(patchwork)
library(kableExtra)
library(psych)
library(effectsize)

#read in data
rt_data <- read_csv("https://uoepsy.github.io/data/reaction_time_2425.csv")

########################### WEEK 1 ###############################

###### STEP 1: INSPECT, CLEAN, AND TIDY DATA ######

#examine dataset
head(rt_data)
str(rt_data) # data that should be factors/numeric not currently coded as so
summary(rt_data) # we have values over 30cm, need to remove these

#make numeric / factors
rt_data <- rt_data %>% 
    mutate(age = as.numeric(age),
           sex = as.factor(sex),
           handedness = as.factor(handedness),
           participation_order = as.factor(participation_order),
           lab_session = as.factor(lab_session),
           first_condition = as.factor(first_condition),
           visualcue_attempt1 = as.numeric(visualcue_attempt1),
           visualcue_attempt2 = as.numeric(visualcue_attempt2),
           visualcue_attempt3 = as.numeric(visualcue_attempt3),
           visualcue_attempt4 = as.numeric(visualcue_attempt4),
           visualcue_attempt5 = as.numeric(visualcue_attempt5),
           auditorycue_attempt1 = as.numeric(auditorycue_attempt1),
           auditorycue_attempt2 = as.numeric(auditorycue_attempt2),
           auditorycue_attempt3 = as.numeric(auditorycue_attempt3),
           auditorycue_attempt4 = as.numeric(auditorycue_attempt4),
           auditorycue_attempt5 = as.numeric(auditorycue_attempt5)
           )

#remove impossible values - data can only range 0-30cm
rt_data[ , c(8:17)][rt_data[ , c(8:17)] > 30] <- NA


###### STEP 2: DISTANCE TO TIME CONVERSION (ON PSYCH 1A LAB SHEET) ###### 

#function to convert distance to time
rt_data <- rt_data %>%
  mutate(across(visualcue_attempt1:auditorycue_attempt5, .fns = function(y) sqrt(2 * y / 980)) )

###### STEP 3: CREATE AVERAGE SCORES (ON PSYCH 1A LAB SHEET) AND SUBSET / FILTER ###### 


### STEP 4: CONDUCT ANALYSIS & ASSUMPTION CHECKS ##### 

```

# Introduction

## Research Questions

# Analysis 

## Research Question 1

# Discussion

# Appendix

```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```

