<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Hypothesis testing: critical values</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="assets/style-labs.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><strong>DAPR1</strong></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
  </a>
</li>
<li>
  <a href="intro_r_rstudio_year1.html">DAPR1 starts here</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Intro to data and R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_01_data_types.html">1/1: Collecting data</a>
    </li>
    <li>
      <a href="1_02_categorical.html">1/2: Categorical data</a>
    </li>
    <li>
      <a href="1_03_numerical.html">1/3: Numerical data</a>
    </li>
    <li>
      <a href="1_04_relationships.html">1/4: Relationships</a>
    </li>
    <li>
      <a href="1_05_functions.html">1/5: Types of relations</a>
    </li>
    <li class="dropdown-header">1/6: Break week!</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Probability &amp; sampling
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="1_07_probability_basics.html">1/7: Probability basics</a>
    </li>
    <li>
      <a href="1_08_probability_rules.html">1/8: Probability rules!</a>
    </li>
    <li>
      <a href="1_09_discrete_distributions.html">1/9: Discrete random variables</a>
    </li>
    <li>
      <a href="1_10_continuous_distributions.html">1/10: Continuous random variables</a>
    </li>
    <li>
      <a href="1_11_sampling_distributions.html">1/11: Sampling distributions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Hypothesis testing
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="2_01_confidence_intervals.html">2/1: Confidence intervals</a>
    </li>
    <li>
      <a href="2_02_ht_pvalues.html">2/2: Hypothesis testing: p-values</a>
    </li>
    <li>
      <a href="2_03_ht_critvalues.html">2/3: Hypothesis testing: critical values</a>
    </li>
    <li>
      <a href="2_04_htci.html">2/4: Hypothesis testing &amp; Confidence intervals</a>
    </li>
    <li>
      <a href="2_05_hterrorspower.html">2/5: Errors, Power, Effect size, Assumptions</a>
    </li>
    <li class="dropdown-header">2/6: Break week</li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Basic tests
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">2/7: Test for one mean</li>
    <li class="dropdown-header">2/8: Test for two means</li>
    <li class="dropdown-header">2/9: Test for paired samples</li>
    <li class="dropdown-header">2/10: Chi-square</li>
    <li class="dropdown-header">2/11: Covariance and correlation</li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Hypothesis testing: critical values</h1>

</div>


<div class="lo">
<ol style="list-style-type: decimal">
<li><p>Understand the parallel between p-values and critical values</p></li>
<li><p>Be able to perform a one-sided or two-sided hypothesis test using the critical value method</p></li>
<li><p>Understand the link between t-scores and critical values</p></li>
</ol>
</div>
<div id="hypothesis-testing-p-value-method" class="section level1">
<h1>Hypothesis testing: p-value method</h1>
<p>Last week we saw that, to perform a hypothesis test, we need to:</p>
<ol style="list-style-type: decimal">
<li><p>Identify the <strong>null hypothesis</strong>, denoted <span class="math inline">\(H_0\)</span>.</p></li>
<li><p>Identify the <strong>alternative hypothesis</strong>, denoted <span class="math inline">\(H_1\)</span>.</p></li>
<li><p>Select the <strong>significance level</strong>, denoted <span class="math inline">\(\alpha\)</span>. Typical values are 0.1, 0.05, or 0.01.</p></li>
<li><p>Compute the <strong>test statistic</strong>. This is used to measure how consistent the data are with the null hypothesis.</p>
<ul>
<li>For testing a mean we use the <strong>t-statistic</strong>, denoted <span class="math inline">\(t\)</span>, which takes the following form:
<span class="math display">\[t = \frac{\bar x - \mu_0}{s / \sqrt{n}}\]</span></li>
</ul></li>
<li><p>Compute the <strong>p-value</strong>.</p></li>
<li><p>Make a <strong>decision</strong>:</p>
<ul>
<li>if p-value <span class="math inline">\(\leq \alpha\)</span>, reject <span class="math inline">\(H_0\)</span>.</li>
<li>if p-value <span class="math inline">\(&gt; \alpha\)</span>, fail to reject <span class="math inline">\(H_0\)</span>.</li>
</ul></li>
</ol>
</div>
<div id="hypothesis-testing-critical-value-method" class="section level1">
<h1>Hypothesis testing: critical value method</h1>
<p>The method we used last week to perform a hypothesis test is called the p-value method because it reduces to comparing the area corresponding to the p-value with the area corresponding to <span class="math inline">\(\alpha\)</span>.
This week we investigate an equivalent approach, called the critical value method, which compares the t-statistics delimiting the <span class="math inline">\(\alpha\)</span> area with the observed t-statistic that is used to compute the p-value area.</p>
<p>The changes to the procedure are minimal:</p>
<ol style="list-style-type: decimal">
<li><p>Identify the <strong>null hypothesis</strong>, denoted <span class="math inline">\(H_0\)</span>.</p></li>
<li><p>Identify the <strong>alternative hypothesis</strong>, denoted <span class="math inline">\(H_1\)</span>.</p></li>
<li><p>Select the <strong>significance level</strong>, denoted <span class="math inline">\(\alpha\)</span>. Typical values are 0.1, 0.05, or 0.01.</p></li>
<li><p>Compute the <strong>test statistic</strong>. This is used to measure how consistent the data are with the null hypothesis.</p>
<ul>
<li>For testing a mean we use the <strong>t-statistic</strong>, denoted <span class="math inline">\(t\)</span>, which takes the following form:
<span class="math display">\[t = \frac{\bar x - \mu_0}{s / \sqrt{n}}\]</span></li>
</ul></li>
<li><p>Compute the <strong>critical values</strong>.</p></li>
<li><p>Make a <strong>decision</strong>:</p>
<ul>
<li>if the observed test statistic <span class="math inline">\(t\)</span> lies beyond the critical values, reject <span class="math inline">\(H_0\)</span>.</li>
<li>if the observed test statistic <span class="math inline">\(t\)</span> lies within the critical values, fail to reject <span class="math inline">\(H_0\)</span>.</li>
</ul></li>
</ol>
</div>
<div id="examples" class="section level1">
<h1>Examples</h1>
<div id="two-sided-alternative" class="section level2">
<h2>1. Two-sided alternative</h2>
<p>Suppose I give you a sample, for example:</p>
<pre class="r"><code>library(tidyverse)

sample_data &lt;- tibble(
    score = c(0.1, 1, -0.2, 1.2)
)</code></pre>
<p>Using <span class="math inline">\(\alpha = 0.01\)</span>, we wish to test whether the population the sample came from has a mean score that is different from 0:</p>
<p><span class="math display">\[
H_0: \mu = 0 \\
H_1: \mu \neq 0
\]</span></p>
<p>Sample mean:</p>
<pre class="r"><code>xbar &lt;- mean(sample_data$score)
xbar</code></pre>
<pre><code>## [1] 0.525</code></pre>
<p>Just because the sample mean is different from 0, it doesn’t mean that the population mean necessarily must also be. This difference could perhaps only be due to random sampling variation.</p>
<pre class="r"><code>s &lt;- sd(sample_data$score)
s</code></pre>
<pre><code>## [1] 0.6800735</code></pre>
<pre class="r"><code>n &lt;- nrow(sample_data)
n</code></pre>
<pre><code>## [1] 4</code></pre>
<pre class="r"><code>SE &lt;- s / sqrt(n)
SE</code></pre>
<pre><code>## [1] 0.3400368</code></pre>
<pre class="r"><code>mu0 &lt;- 0   # hypothesised value for mu in H0
tobs &lt;- (xbar - mu0) / SE
tobs</code></pre>
<pre><code>## [1] 1.543951</code></pre>
<p>The observed sample mean (<span class="math inline">\(\bar x =\)</span> 0.52) is 1.54 standard errors away from the hypothesised value of 0.</p>
<p>We need to compare the observed t-statistic (i.e. the one computed from the observed sample data) with the critical values from a t(3) distribution. These are the values that cut, respectively, an area of 0.005 to the left and 0.005 to the right.</p>
<p>Those are the <strong>quantiles</strong> of a t-distribution, hence the function required is <code>qt()</code>.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<p>If we want to have 0.01 probability equally divided among both tails, we will have 0.01/2 = 0.005 in each tail. Remember that <code>qt()</code> uses the probability <strong>to the left</strong> by default.</p>
<pre class="r"><code>tstar &lt;- qt(c(0.005, 0.995), df = n-1)
tstar</code></pre>
<pre><code>## [1] -5.840909  5.840909</code></pre>
<ul>
<li><p>In the t(3) distribution:</p>
<ul>
<li>The middle 0.99 probability of the distribution lies in between the values <span class="math inline">\(-t^*\)</span> = -5.84 and <span class="math inline">\(t^*\)</span> = 5.84.</li>
<li>To the left of <span class="math inline">\(-t^*\)</span> = -5.84 lies a probability of 0.005 = 0.01/2</li>
<li>To the right of <span class="math inline">\(t^*\)</span> = 5.84 lies a probability of 0.005 = 0.01/2</li>
<li>Hence, below -5.84 and beyond 5.84 lies a total of 0.01 probability. <strong>The probability in the tails is then 0.01 = <span class="math inline">\(\alpha\)</span></strong>.</li>
</ul></li>
</ul>
<div class="optional-begin">
<span id="opt-start-146" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-146&#39;, &#39;opt-start-146&#39;)"> Visually</span>
</div>
<div id="opt-body-146" class="optional-body" style="display: none;">
<p>You don’t need to plot a t-distribution usually, but if you want to, here is how you could do this.
First, create a sequence of t values, this is an arbitrary choice of points you want to plot the t distribution for. You can either go from -5 to 5, or -10 to 10, as you wish.
Then compute the t <strong>density</strong> for each value. You would only use the function <code>dt()</code> for plotting the t distribution, in fact this function doesn’t calculate a probability. Remember that a probability is an area, and it is computed by <code>pt()</code>.</p>
<pre class="r"><code>plt &lt;- tibble(
    t_values = seq(-10, 10, by = 0.1),
    t_dens = dt(t_values, df = n-1)
)

ggplot(plt, aes(x = t_values, y = t_dens)) +
    geom_line() +
    labs(x = &#39;t values&#39;, y = &#39;Density&#39;)</code></pre>
<p><img src="2_03_ht_critvalues_files/figure-html/unnamed-chunk-6-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>We can also add the critical values that cut an area of 0.005 to the left and 0.005 to the right. We computed those earlier, remember?</p>
<pre class="r"><code>tstar &lt;- qt(c(0.005, 0.995), df = n-1)
tstar</code></pre>
<pre><code>## [1] -5.840909  5.840909</code></pre>
<p>We could add those as follows:</p>
<pre class="r"><code>ggplot(plt, aes(x = t_values, y = t_dens)) +
    geom_line() +
    geom_vline(xintercept = tstar, col = &#39;red&#39;) +
    labs(x = &#39;t values&#39;, y = &#39;Density&#39;)</code></pre>
<p><img src="2_03_ht_critvalues_files/figure-html/unnamed-chunk-8-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Any t-statistic smaller than -6 or any t-statistic larger than 6 falls into the area corresponding to the significance level <span class="math inline">\(\alpha = 0.01\)</span>.</p>
<p>Remember that we use <span class="math inline">\(\alpha\)</span> to control the probability of the t-statistics in the null distribution that are considered “unlikely enough” to occur if <span class="math inline">\(H_0\)</span> were true.</p>
<p>Where does our observed t-statistic lie?</p>
<pre class="r"><code>ggplot(plt, aes(x = t_values, y = t_dens)) +
    geom_line() +
    geom_vline(xintercept = tstar, col = &#39;red&#39;) +
    geom_vline(xintercept = tobs, col = &#39;darkgreen&#39;) +
    labs(x = &#39;t values&#39;, y = &#39;Density&#39;)</code></pre>
<p><img src="2_03_ht_critvalues_files/figure-html/unnamed-chunk-9-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p class="optional-end">
</p>
<p>The observed t-statistic lies in between the critical values, rather than beyond. Hence, we fail to reject <span class="math inline">\(H_0\)</span> at the 1% significance level.</p>
<p>If you were to compute the p-value, this would be larger than <span class="math inline">\(\alpha = 0.01\)</span>.</p>
<pre class="r"><code>tobs</code></pre>
<pre><code>## [1] 1.543951</code></pre>
<pre class="r"><code>tstar</code></pre>
<pre><code>## [1] -5.840909  5.840909</code></pre>
<p>If you don’t like to check it visually by looking at the number, you can get R to check it for you:</p>
<pre class="r"><code>tobs &lt;= tstar[1]</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r"><code>tobs &gt;= tstar[2]</code></pre>
<pre><code>## [1] FALSE</code></pre>
</div>
<div id="one-sided-alternative" class="section level2">
<h2>2. One-sided alternative: &lt;</h2>
<p>Suppose you were given a different sample, such as</p>
<pre class="r"><code>sample_data &lt;- tibble(
    score = c(-2.1, -5.9, -3.8, -4.3)
)</code></pre>
<p>Using <span class="math inline">\(\alpha = 0.05\)</span>, we wish to test whether the population it came from has a mean score that is less than 0:</p>
<p><span class="math display">\[
H_0: \mu = 0 \\
H_1: \mu &lt; 0
\]</span></p>
<pre class="r"><code>xbar &lt;- mean(sample_data$score)
xbar</code></pre>
<pre><code>## [1] -4.025</code></pre>
<p>Compute the observed value of the t-statistic:</p>
<pre class="r"><code>s &lt;- sd(sample_data$score)
s</code></pre>
<pre><code>## [1] 1.564981</code></pre>
<pre class="r"><code>n &lt;- nrow(sample_data)
n</code></pre>
<pre><code>## [1] 4</code></pre>
<pre class="r"><code>SE &lt;- s / sqrt(n)
SE</code></pre>
<pre><code>## [1] 0.7824907</code></pre>
<pre class="r"><code>mu0 &lt;- 0   # hypothesised value for mu in H0
tobs &lt;- (xbar - mu0) / SE
tobs</code></pre>
<pre><code>## [1] -5.143831</code></pre>
<p>Compute the <strong>critical value</strong>. In a one-sided hypothesis test there is only one critical value as the entire <span class="math inline">\(\alpha\)</span> probability (= 0.05 in this case) is assigned all in one tail.</p>
<p>In this case <span class="math inline">\(H_1 : \mu &lt; 0\)</span> so <span class="math inline">\(\alpha\)</span> goes all in the <strong>left</strong> tail. This is because t-statistics that are much smaller than the hypothesised value, i.e. 0, will be considered as providing strong evidence against the null hypothesis.</p>
<pre class="r"><code>tstar &lt;- qt(0.05, df = n - 1)
tstar</code></pre>
<pre><code>## [1] -2.353363</code></pre>
<p>Compare the observed value of the t-statistic with the critical value:</p>
<pre class="r"><code>tobs</code></pre>
<pre><code>## [1] -5.143831</code></pre>
<pre class="r"><code>tstar</code></pre>
<pre><code>## [1] -2.353363</code></pre>
<p>The observed t-statistic is smaller than the critical value, so we reject <span class="math inline">\(H_0\)</span> in favour of the alternative.</p>
<pre class="r"><code>tobs &lt;= tstar</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>At the 5% significance level, the sample data provide strong evidence against the null hypothesis that the sample came from a population with a mean of 0, and in favour of the alternative that the population mean is less than 0.</p>
<p>As the observed <span class="math inline">\(t\)</span> = -5.14 is smaller than the critical value <span class="math inline">\(t^*\)</span> = -2.35, the p-value would also be smaller than <span class="math inline">\(\alpha = 0.05\)</span>.</p>
</div>
<div id="one-sided-alternative-1" class="section level2">
<h2>3. One-sided alternative: &gt;</h2>
<p>Suppose you were given a different sample, such as</p>
<pre class="r"><code>sample_data &lt;- tibble(
    score = c(2.1, 0.3, -0.9, 1.1)
)</code></pre>
<p>Using <span class="math inline">\(\alpha = 0.05\)</span>, we wish to test whether the population it came from has a mean score that is larger than 0:</p>
<p><span class="math display">\[
H_0: \mu = 0 \\
H_1: \mu &gt; 0
\]</span></p>
<pre class="r"><code>xbar &lt;- mean(sample_data$score)
xbar</code></pre>
<pre><code>## [1] 0.65</code></pre>
<p>Compute the observed value of the t-statistic:</p>
<pre class="r"><code>s &lt;- sd(sample_data$score)
s</code></pre>
<pre><code>## [1] 1.268858</code></pre>
<pre class="r"><code>n &lt;- nrow(sample_data)
n</code></pre>
<pre><code>## [1] 4</code></pre>
<pre class="r"><code>SE &lt;- s / sqrt(n)
SE</code></pre>
<pre><code>## [1] 0.6344289</code></pre>
<pre class="r"><code>mu0 &lt;- 0   # hypothesised value for mu in H0
tobs &lt;- (xbar - mu0) / SE
tobs</code></pre>
<pre><code>## [1] 1.024544</code></pre>
<p>Compute the <strong>critical value</strong>. In a one-sided hypothesis test there is only one critical value as the entire <span class="math inline">\(\alpha\)</span> probability (= 0.05 in this case) is assigned all in one tail.</p>
<p>In this case <span class="math inline">\(H_1 : \mu &gt; 0\)</span> so <span class="math inline">\(\alpha\)</span> goes all in the <strong>right</strong> tail. This is because t-statistics that are much larger than the hypothesised value, i.e. 0, will be considered as providing strong evidence against the null hypothesis.</p>
<pre class="r"><code>tstar &lt;- qt(0.95, df = n - 1)
tstar</code></pre>
<pre><code>## [1] 2.353363</code></pre>
<p>Compare the observed value of the t-statistic with the critical value:</p>
<pre class="r"><code>tobs</code></pre>
<pre><code>## [1] 1.024544</code></pre>
<pre class="r"><code>tstar</code></pre>
<pre><code>## [1] 2.353363</code></pre>
<p>The observed t-statistic is not more extreme than the critical value. It is smaller than the critical value, so we fail to reject <span class="math inline">\(H_0\)</span>. The sample data are consistent with the null hypothesis.</p>
<pre class="r"><code>tobs &gt;= tstar</code></pre>
<pre><code>## [1] FALSE</code></pre>
<p>At the 5% significance level, the sample data do not provide sufficient evidence against the null hypothesis and hence we fail to reject the null that the sample came from a population with a mean of 0.</p>
<p>If you were to compute the p-value, as the observed t-statistic is smaller than the critical value, the p-value would be larger than <span class="math inline">\(\alpha = 0.05\)</span>.</p>
</div>
</div>
<div id="summary" class="section level1">
<h1>Summary</h1>
<ul>
<li><p>We have learned to assess how much evidence the sample data bring against the null hypothesis and in favour of the alternative hypothesis.</p></li>
<li><p>The null hypothesis, denoted <span class="math inline">\(H_0\)</span>, is a claim about a population parameter that is initially assumed to be true. It typically represents “no effect” or “no difference between groups.”</p></li>
<li><p>The alternative hypothesis, denoted <span class="math inline">\(H_1\)</span>, is the claim we seek evidence for.</p></li>
<li><p>We performed a hypothesis test against <span class="math inline">\(H_0\)</span> (and in favour of <span class="math inline">\(H_1\)</span>) following these steps:</p>
<ul>
<li>Formally state your null and alternative hypotheses using precise symbols</li>
<li>Select a significance level for the test.</li>
<li>Consider the distribution of the t-statistics when <span class="math inline">\(H_0\)</span> is true</li>
<li>Compute the observed value of the t-statistic in our sample</li>
<li>Obtain the <strong>critical values</strong></li>
<li>Compare the observed t-statistic with the critical values. If it lies beyond, reject the null hypothesis.</li>
</ul></li>
</ul>
</div>
<div id="exercises" class="section level1">
<h1>Exercises</h1>
<p>In this week’s exercises you will perform the same test of hypothesis as last week’s lab, but using the critical value method rather than the p-value method.</p>
<p>A 2011 study by Courchesne et al.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> examined brain tissue of seven autistic male children between the ages of 2 and 16. The mean number of neurons in the prefrontal cortex in non-autistic male children of the same age is about 1.15 billion. The prefrontal cortex is the part of the brain most disrupted in autism, as it deals with language and social communication.</p>
<blockquote>
<p><strong>Research question</strong><br />
Do autistic male children have more neurons (on average) in the prefrontal cortex than non-autistic children?</p>
</blockquote>
<p>That is, we wish to test:</p>
<p><span class="math display">\[
H_0 : \mu = 1.15 \\
H_1 : \mu &gt; 1.15
\]</span></p>
<p>where <span class="math inline">\(\mu\)</span> is the mean number of neurons (in billions) in the prefrontal cortex for all autistic male children.</p>
<p>In the following you will use a significance level <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p><br></p>
<div class="optional-begin">
<span id="opt-start-147" class="fa fa-chevron-circle-right optional-icon clickable" onclick="toggle_visibility(&#39;opt-body-147&#39;, &#39;opt-start-147&#39;)"> Data Codebook</span>
</div>
<div id="opt-body-147" class="optional-body" style="display: none;">
<p><strong>Download link</strong></p>
<p>The data can be found at this address: <a href="https://uoepsy.github.io/data/NeuronCounts.csv" class="uri">https://uoepsy.github.io/data/NeuronCounts.csv</a></p>
<p><strong>Preview</strong></p>
<div id="osncjrvket" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#osncjrvket .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#osncjrvket .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#osncjrvket .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#osncjrvket .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#osncjrvket .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#osncjrvket .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#osncjrvket .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#osncjrvket .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#osncjrvket .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#osncjrvket .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#osncjrvket .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#osncjrvket .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#osncjrvket .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#osncjrvket .gt_from_md > :first-child {
  margin-top: 0;
}

#osncjrvket .gt_from_md > :last-child {
  margin-bottom: 0;
}

#osncjrvket .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#osncjrvket .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#osncjrvket .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#osncjrvket .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#osncjrvket .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#osncjrvket .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#osncjrvket .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#osncjrvket .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#osncjrvket .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#osncjrvket .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#osncjrvket .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#osncjrvket .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#osncjrvket .gt_left {
  text-align: left;
}

#osncjrvket .gt_center {
  text-align: center;
}

#osncjrvket .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#osncjrvket .gt_font_normal {
  font-weight: normal;
}

#osncjrvket .gt_font_bold {
  font-weight: bold;
}

#osncjrvket .gt_font_italic {
  font-style: italic;
}

#osncjrvket .gt_super {
  font-size: 65%;
}

#osncjrvket .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Case</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Age</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">PFC_NC</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">2.42</td></tr>
    <tr><td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">1.80</td></tr>
    <tr><td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">2.21</td></tr>
    <tr><td class="gt_row gt_right">4</td>
<td class="gt_row gt_right">4</td>
<td class="gt_row gt_right">2.18</td></tr>
    <tr><td class="gt_row gt_right">5</td>
<td class="gt_row gt_right">7</td>
<td class="gt_row gt_right">1.28</td></tr>
    <tr><td class="gt_row gt_right">6</td>
<td class="gt_row gt_right">8</td>
<td class="gt_row gt_right">1.59</td></tr>
    <tr><td class="gt_row gt_right">7</td>
<td class="gt_row gt_right">16</td>
<td class="gt_row gt_right">2.09</td></tr>
  </tbody>
  
  
</table>
</div>
<p><strong>Codebook</strong></p>
<ul>
<li>The first column, <code>Case</code>, is an anonymised index used to identify each child.</li>
<li>The second column, <code>Age</code>, records the age of each child.</li>
<li>The last column, <code>PFC_NC</code>, contains the prefrontal cortex neuron counts (in billions).</li>
</ul>
</div>
<p class="optional-end">
</p>
<p><br></p>
<div class="question-begin">
Question 1
</div>
<div class="question-body">
<p>Read the data into R.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-148" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-148&#39;, &#39;sol-start-148&#39;)"> Solution </span>
</div>
<div id="sol-body-148" class="solution-body" style="display: none;">
<pre class="r"><code>library(tidyverse)
autism &lt;- read_csv(&#39;https://uoepsy.github.io/data/NeuronCounts.csv&#39;)
autism</code></pre>
<pre><code>## # A tibble: 7 × 3
##    Case   Age PFC_NC
##   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1     1     2   2.42
## 2     2     3   1.8 
## 3     3     3   2.21
## 4     4     4   2.18
## 5     5     7   1.28
## 6     6     8   1.59
## 7     7    16   2.09</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 2
</div>
<div class="question-body">
<p>Compute the value of the t-statistic for the observed sample.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-149" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-149&#39;, &#39;sol-start-149&#39;)"> Solution </span>
</div>
<div id="sol-body-149" class="solution-body" style="display: none;">
<p>Recall the formula for the t-statistic:</p>
<p><span class="math display">\[
t = \frac{\bar x - \mu_0}{\frac{s}{\sqrt{n}}}
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(\bar x\)</span> is the sample average number of neurons in the prefrontal cortex</li>
<li><span class="math inline">\(\mu_0\)</span> is the hypothesised value for the population parameter found in <span class="math inline">\(H_0\)</span></li>
<li><span class="math inline">\(s\)</span> is the sample standard deviation</li>
<li><span class="math inline">\(n\)</span> is the sample size</li>
</ul>
<p>Hence, the value of the t-statistic for the observed sample is given by:</p>
<pre class="r"><code>xbar &lt;- mean(autism$PFC_NC)
xbar</code></pre>
<pre><code>## [1] 1.938571</code></pre>
<pre class="r"><code>s &lt;- sd(autism$PFC_NC)
n &lt;- nrow(autism)
SE &lt;- s / sqrt(n)

mu0 &lt;- 1.15

tobs &lt;- (xbar - mu0) / SE
tobs</code></pre>
<pre><code>## [1] 5.212963</code></pre>
<p>The sample mean neuron count, 1.94 billion, is 5.21 standard errors larger than the hypothesised value.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 3
</div>
<div class="question-body">
<p>Identify the null distribution, i.e. the distribution of the t-statistic when <span class="math inline">\(H_0\)</span> is true.</p>
<p>Compute the critical value(s) for the null distribution using the appropriate significance level.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-150" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-150&#39;, &#39;sol-start-150&#39;)"> Solution </span>
</div>
<div id="sol-body-150" class="solution-body" style="display: none;">
<p>When <span class="math inline">\(H_0\)</span> is true, the t-statistic <span class="math inline">\(t = (\bar x - \mu_0)/(s / \sqrt{n})\)</span> follows a t(6) distribution, where the degrees of freedom are computed as df = n - 1 = 7 - 1 = 6.</p>
<p>The critical value is the t-value cutting an area of 0.05 to its right, i.e. the following quantile</p>
<pre class="r"><code>tstar &lt;- qt(0.95, df = n - 1)
tstar</code></pre>
<pre><code>## [1] 1.94318</code></pre>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 4
</div>
<div class="question-body">
<p>Make a decision.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-151" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-151&#39;, &#39;sol-start-151&#39;)"> Solution </span>
</div>
<div id="sol-body-151" class="solution-body" style="display: none;">
<p>Making a decision using the critical value method entails comparing the observed t-statistic with the critical value.</p>
<pre class="r"><code>tobs</code></pre>
<pre><code>## [1] 5.212963</code></pre>
<pre class="r"><code>tstar</code></pre>
<pre><code>## [1] 1.94318</code></pre>
<p>The observed t-statistic is larger than the critical value for a 5% significance level, hence we reject the null hypothesis.</p>
<pre class="r"><code>tobs &gt;= tstar</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>If you were to compute the p-value, i.e. the probability of observing a t-statistic as large as, or larger, than the observed one, if the null hypothesis were true, you would obtain a value that is smaller than <span class="math inline">\(\alpha = 0.05\)</span>.</p>
</div>
<p class="solution-end">
</p>
<div class="question-begin">
Question 5
</div>
<div class="question-body">
<p>Write up your results in the context of the research question.</p>
</div>
<p class="question-end">
</p>
<div class="solution-begin">
<span id="sol-start-152" class="fa fa-chevron-circle-right solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-152&#39;, &#39;sol-start-152&#39;)"> Solution </span>
</div>
<div id="sol-body-152" class="solution-body" style="display: none;">
<div class="frame">
<p><strong>Side note</strong><br />
When you use the critical value method, you don’t have a computed p-value, so the reporting will only say whether p &lt; .05 or p &gt; .05 depending on whether the observed t-statistic is beyond or not beyond the critical value(s).</p>
<ul>
<li>If <span class="math inline">\(t &gt; t^*\)</span>, p &lt; .05 (if you use a different <span class="math inline">\(\alpha\)</span>, change accordingly)</li>
<li>If <span class="math inline">\(t &lt; t^*\)</span>, p &gt; .05 (if you use a different <span class="math inline">\(\alpha\)</span>, change accordingly)</li>
</ul>
</div>
<p>The estimated mean number of neurons in the prefrontal cortex of male autistic children is 1.94 billion, with a standard error of 0.15 billion.</p>
<p>At the 5% significance level, we performed a one-sided test of significance against the null hypothesis that the mean number of neurons in the prefrontal cortex of all male autistic children was equal to that of all non-autistic male children.
The sample results indicate that there is very strong evidence that the mean number of neurons in the prefrontal cortex may be larger for autistic compared to non-autistic male children: <span class="math inline">\(t(6) = 5.21, p &lt; .05\)</span>, one-sided.</p>
</div>
<p class="solution-end">
</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<!-- Formatting -->
<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;">

</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Remember the quantiles? <a href="1_10_continuous_distributions.html#The_inverse_problem:_quantiles_and_percentiles">See here if not</a><a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Courchesne, E., et al., “Neuron Number and Size in Prefrontal Cortex of Children with Autism,” <em>Journal of the American Medical Association</em>, November 2011;306(18): 2001–2010.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
<div class="ccfooter"></div>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
