---
title: 'dapR1: More Probability Activities - 1'
author: "Department of Psychology<br>University of Edinburgh"
date: ""
output:
  html_document:
    theme: flatly
---

# Context of questions  

I am waiting for a package to arrive.  
The Royal Mail promises me with absolute certainty that it will arrive before next Monday.  

## Question 1

The probability of it arriving on Monday is .20, and the probability of it arriving on Tuesday is .27. With this information can you calculate the probability of $p(M \cup T)$? 

## Question 2

The probability of it arriving on Monday is .20, and the probability of it arriving on Wednesday is .46. With this information can you calculate the probability of $p(M \cap W)$? 

## Question 3

What is the probability (according to the Royal Mail) that it will arrive on Monday or Tuesday or Wednesday or Thursday or Friday or Saturday or Sunday? 



<br>
<br>

---  

*Scroll down for answers*  
  
---

<div style="margin-bottom:750px;">

</div>


# Answers

1. Yes, you can calculate the probability using the simple addition rule because they are mutually exclusive. The probability is 47% or $p(M) + p(T)$.  

2. Yes. The two events are mutually exclusive, so the probability of their intersection is 0. 

3. That's all the possible days, so the sum of their probability must be 1.  


