---
title: 'dapR1: Critical values task'
date: "AY 2020-2021"
output:
  html_document:
    theme: flatly
---

**Question 1**

In a test of $H_0: \mu = 0$ against $H_1 : \mu > 0$, if the p-value is less than the 5% significance level, the observed statistic is larger than the 97.5th percentile of the distribution.

TRUE or FALSE?


**Question 2**

In a test of $H_0: \mu = 0$ against $H_1 : \mu \neq 0$, if the p-value is less than the 5% significance level, the observed statistic is larger than the 97.5th percentile of the distribution.

TRUE or FALSE?


**Question 3**

Consider a two-sided test which rejected $H_0: \mu = 0$ because $|\bar x|$ is larger than $1.96 \cdot SE$. This is equivalent to saying that the observed z-score is in absolute value larger than 1.96.
We reject the null because when the null is true, only 2.5% of the statistics are larger than 1.96, and 2.5% are smaller than -1.96.

TRUE or FALSE?


---

*Scroll down to find some thinking points.. and the answers!*

---

<div style="margin-bottom:750px;"></div>


**Question 1**: The correct answer is FALSE. 

The observed statistic will be more extreme than the 95th percentile of the distribution.


**Question 2** The correct answer is FALSE.

What if the observed statistic is negative? It could fall in the lower 2.5% tail of the distribution, meaning it is smaller than the 2.5th percentile.

The correct answer would have been "the observed statistic is _in absolute value_ larger than the 97.5th percentile of the distribution" or "the _absolute value_ of the observed statistic is larger than the 97.5th percentile of the distribution".


**Question 3** The correct answer is TRUE.

The -1.96 and 1.96 critical values correspond to a 5% area _in total_ in the tails, so 2.5% in each tail.

