---
title: "Probability (2)"
subtitle: Data Analysis for Psychology in R 1
author: Tom Booth
---

```{r premable, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(kableExtra)
```

## Today
- Brief recap of probability rules
- Contingency tables and conditional probability
  - Our first test (without the actual test!)

## Learning objectives
- Understand the use of probability rules to test dependence
- Understand use of probability to test independence

## Rules of probability
1. For any event 

$$0 \leq p(A) \leq 1$$

2. The sum of the probabilities of all possible outcomes = 1

$$p(A_1) + p(A_2) + ... p(A_i) = 1$$ 


3. Probability of the complement of A (Not A):

$$p(\sim A) = 1 - p(A)$$

 
## Rules of probability
4. For mutually exclusive events, probability of A or B: 

$$p(A \bigcup B) = p(A) + p(B)$$ 

- The probability of A or B, will always be equal or greater than the probability of single event.
  - Why?

## Rules of probability
5. General addition rule: 

$$p(A \bigcup B) = p(A) + p(B) - p(A \bigcap B)$$

- The general addition rule can be used when events are not mutually exclusive.
  - That is when an event can fall into both A and B.
  - E.g. Think a playing card being red or a 7.


## Rules of probability
6. If A and B are independent, probability of A and B

$$p(A \bigcap B) = p(A)p(B)$$

- The probability of A and B will always we less than or equal to the probability of single event.
    - Why? 

## Question from class
- Why is the probability of event A and event B occurring arrived at using multiplication?
  - As per they "Why?" above, the probability that two things occur, conceptually, has to be equally likely or less likely than a single event.
  - As we represent probability using decimal, multiplication is our tool. 
- But lets think about it in a another way.

## (Hopefully) an intuitive answer
- Suppose we have two events.
  - Event A occurs $\frac{1}{4}$ of the time
  - Event B occurs $\frac{1}{2}$ of the time
- If the events are independent (the probability of one does not impact the probability of the other), then event B will happen with equal probability when both A and not A.
  - So, of the total number of times A occurs, B will occur half the time.
  - And of the total number of times A does not occur, B will occur half the time.

## (Hopefully) an intuitive answer

| o | o | o | o | o | o | o | o |
| o | o | o | o | o | o | o | o |
| o | o | o | o | o | o | o | o |
| o | o | o | o | o | o | o | o |


- Each `o` above is an event (32 in total).

## (Hopefully) an intuitive answer

| A | A | o | o | o | o | o | o |
| A | A | o | o | o | o | o | o |
| A | A | o | o | o | o | o | o |
| A | A | o | o | o | o | o | o |


- Event A occurs $\frac{1}{4}$ of the time.
  - The A's above (8 times)

## (Hopefully) an intuitive answer

| o | o | o | o | o | o | o | o |
| o | o | o | o | o | o | o | o |
| B | B | B | B | B | B | B | B |
| B | B | B | B | B | B | B | B |


- Event B occurs $\frac{1}{2}$ of the time.
  - The B's above (16 times)

## (Hopefully) an intuitive answer

| A | A | o | o | o | o | o | o |
| A | A | o | o | o | o | o | o |
| X | X | B | B | B | B | B | B |
| X | X | B | B | B | B | B | B |


- Events A and B occur (or intersect) on 4 occasions.
  - 4/32 = 1/8
  - 1/8 = 1/2*1/4
  

## Rules of probability
7. General multiplication rule:

$$p(A \bigcap B) = p(A)p(B|A)$$ 

## Conditional probability
- What is $p(B|A)$?
- This is referred to as **conditional probability**.
- Probability of B **given** A, which is written, $p(B|A)$
- Note though that when $p(A)$ and $p(B)$ are independent, then the $p(B|A) = p(B)$
  - Hence the simple multiplication rule for independent events.

## Conditional probability
- We can calculate conditional probability as;

$$p(B|A) = \frac{p(A \bigcap B)}{p(A)}$$

- Or: 

$$p(A|B) = \frac{p(A \bigcap B)}{p(B)}$$

## Where does this come from?
- It comes from re-arranging our general multiplication rule.

$$p(A \bigcap B) = p(A)p(B|A)$$  

- Divide both side by $p(A)$

$$\frac{p(A \bigcap B)}{p(A)} = \frac{p(A)p(B|A)}{p(A)}$$ 

## Where does this come from?
- Cancel $p(A)$ from right hand side

$$\frac{p(A \bigcap B)}{p(A)} = p(B|A)$$
- Re-arrange

$$p(B|A) = \frac{p(A \bigcap B)}{p(A)}$$


## Conditional probability: an example

|          | Left   | Right   | Marginal |
|----------|--------|---------|----------|
| Boys     | 25     | 24      | 49       |
| Girls    | 10     | 41      | 51       |
| Marginal | 35     | 65      | 100      |

- We have data on the handedness of boys and girls in a class
- Let's say we select one student at random, and they are a girl.  
- What is the probability they are left handed?
  - $p(left | girl)$

## Conditional probability: an example

|          | Left   | Right   | Marginal |
|----------|--------|---------|----------|
| Boys     | 25     | 24      | 49       |
| **Girls**| **10** | **41**  | **51**   |
| Marginal | 35     | 65      | 100      |


$$p(Left|Girl) = \frac{0.10}{0.51} = 0.196$$

## Conditional probability: an example
- We can also work this through the longer way:
  - $p(left \bigcap girl)$ = $\frac{10}{100}$ = 0.10
  - $p(girl) = \frac{51}{100}$ = 0.51

$$p(Left|Girl) = \frac{p(Left \bigcap Girl)}{p(Girl)}$$

$$p(Left|Girl) = \frac{0.10}{0.51} = 0.196$$  



## Conditional probability: an example

|          |**Left**| Right   | Marginal |
|----------|--------|---------|----------|
| Boys     | **25** | 24      | 49       |
| Girls    | **10** | 41      | 51       |
| Marginal | **35** | 65      | 100      |


$$p(Girl|Left) = \frac{p(Left \bigcap Girl)}{p(Left)}$$

- Therefore: 

$$p(Girl|Left) = \frac{0.10}{0.35} = 0.286$$

## Are events independent?
- The multiplication rule, and the use of contingency tables, provides a way to assess if events are independent.
- **Example**: Consider a different school with 100 pupils.
  - 55 male and 45 female. 
  - Suppose we ask those students if they like stats. 40 say yes, 60 say no.
- We can tabulate the proportions and think about the probabilities.


## Are events independent?

|          | Yes             | No            | Marginal |
|----------|-----------------|---------------|----------|
| Male     | p(Male, Yes)    | p(Male, No)   | 0.55     |
| Female   | p(Female & Yes) | p(Female, No) | 0.45     |
| Marginal | 0.40            | 0.60          | 1.00     |

## Are events independent?

|          | Yes                | No                 | Marginal |
|----------|--------------------|--------------------|----------|
| Male     | $0.55*0.40 = 0.22$ | $0.55*0.60 = 0.33$ | 0.55     |
| Female   | $0.45*0.40 = 0.18$ | $0.45*0.60 = 0.27$ | 0.45     |
| Marginal | 0.40               | 0.60               | 1.00     |


- If we assume all events to be independent, we can calculate expected frequencies. 
  - These are the products of the two probabilities.
- Notice that here we do not have actual frequencies like in example 1. We have cell probabilities.

## Are events independent?

|          | Yes    | No    | Marginal |
|----------|--------|-------|----------|
| Male     | 0.22   | 0.33  | 0.55     |
| Female   | 0.18   | 0.27  | 0.45     |
| Marginal | 0.40   | 0.60  | 1.00     |


- From this, **if** preference and gender are independent, the probabilities of liking stats if male or female should be the same:
  - $p(yes|male)$ = $\frac{.22}{.55}$ = 0.40
  - $p(yes|female)$ = $\frac{.18}{.45}$ = 0.40

## Are events independent?


|          | Yes  | No   | Marginal |
|----------|------|------|----------|
| Male     | 0.10 | 0.45 | 0.55     |
| Female   | 0.30 | 0.15 | 0.45     |
| Marginal | 0.40 | 0.60 | 1.00     |


- But what if we observed the above...

## Are events independent?

|          | Yes  | No   | Marginal |
|----------|------|------|----------|
| Male     | 0.10 | 0.45 | 0.55     |
| Female   | 0.30 | 0.15 | 0.45     |
| Marginal | 0.40 | 0.60 | 1.00     |


- Given this, our conditional probabilities look like this;
  - $p(yes|male) = \frac{.10}{.55}$ = 0.18
  - $p(yes|female) = \frac{.30}{.45}$ = 0.67

- In other words, gender and whether you like stats are related.

## Our first statistical test
- What we have just done (more or less) is do all the background work to understand a $\chi^2$ test of independence.
- This is test of the independence of two nominal category variables.
- To use this in practice, we have a couple of extra steps, but the above is the fundamental principle.

## Tasks for this week...
1. Finish any existing tasks from labs.
2. Reading: See LEARN
3. Quiz 9 on probability
    - **This quiz counts**
    - Live now (as of Monday at 09:00).
    - Closes Sunday at 17:00

## Recommendations of the week (Lab Team)
- Podcast: [The Black Goat](http://www.theblackgoatpodcast.com/)
- Recipe: [Homemade Fudge](https://www.jamieoliver.com/features/creamy-sea-salted-fudge-recipe/)
- Book: [The End of Mr Y, Scarlett Thomas](https://www.theguardian.com/books/2007/jul/21/fiction.featuresreviews3)
- Thing to do: [Gallery of Modern Art](https://www.nationalgalleries.org/visit/scottish-national-gallery-modern-art)
- Coffee/food Place: [The Kilted Donut](https://www.kilteddonut.com/)