---
title: "RStudio glossary"
---

```{r setup, include=FALSE}
source('../assets/setup.R')
```


+ Console: where the code gets executed
+ Environment: R's memory, it lists all the names of things with stuff stored into them
+ Editor: where we edit code
+ R script: a file with R code and comments
+ package (also library): user-created bundles providing additional functionality to your local R installation
+ function: a function takes some input, does some transformation or computation on them, and returns a result (output)
+ ?: returns the help page of a function, e.g. ?dim.


| Symbol |  Description | Example |
|:--|:--|:--|
|`+` |  adds two numbers together | `2+2`, two plus two |
|`-`|   subtract one number from another  | `3-1`, three minus one |
|`*`|   multiply two numbers together | `3*3`, three times three |
|`/`|   divide one number by another  | `9/3`, nine divided by three |
|`()`|  group operations together     | `(2+2)/4` is different from `2+2/4` |
|`^`|   to the power of..    | `4^2` - four to the power of two, or four squared |
|`<-`|  stores an object in R with the left hand side (LHS) as the name, and the RHS as the value | `x <- 10` |
|`=`| stores an object in R with the left hand side (LHS) as the name, and the RHS as the value | `x = 10`     |
|`<`|   is less than?  | `2 < 3` |
|`>`|   is greater than? | `2 > 3` |
|`<=`|  is less than or equal to? | `2 <= 3` |
|`>=`|  is greater than or equal to? | `2 >= 2` |
|`==`|  is equal to? | `(5+5) == 10` |
|`!=` | is not equal to?  | `(2+3) != 4` |
| `c()` | combines values into a vector (a sequence of values) | `c(1,2,3,4)` | 
