---
title: 'DAPR1: Making decisions'
date: ""
output:
  html_document:
    theme: flatly
---

```{r echo=FALSE}
knitr::opts_chunk$set(out.width = '70%', fig.height = 5, fig.width = 6,
                      fig.align = 'center')
```

---

**TODAY'S ACTIVITY**

1. Go to the applet at the following address https://istats.shinyapps.io/power/
2. From the top grey navigation bar click: "Population Mean"
3. Scroll to the bottom and click "Show critical value(s) and rejection region(s)"
4. Use the applet to explore what happens by varying different values, and answer the following questions

---

**Question 1**

The significance level $\alpha$ varies with the sample size.

TRUE or FALSE?


**Question 2**

As the sample size increases, the power will increase.

TRUE or FALSE?


**Question 3**

The smaller the standard deviation of the original data (or the population), the higher the power.

TRUE or FALSE?


**Question 4**

If we increase the probability of a Type I error, the power will decrease.

---

*Scroll down to find some thinking points.. and the answers!*

---

<div style="margin-bottom:750px;"></div>


**Question 1**: The correct answer is FALSE.

The significance level $\alpha = P(\text{Type I error})$ is set by the researcher and won't depend on $n$.

**Question 2** The correct answer is TRUE.

Check by varying the sample size $n$ while keeping everything else fixed. This is because the distributions become narrower, so there is more probability beyond the critical values. Remember that $n$ appears in the denominator of the standard error formula: $SE = \sigma / \sqrt{n}$.

**Question 3** The correct answer is TRUE.

Check by varying $\sigma$ while keeping everything else fixed. This is also because the distributions become narrower, so there is more probability beyond the critical values. Remember that $\sigma$ appears in the numerator of the standard error formula: $SE = \sigma / \sqrt{n}$.

**Question 4** The correct answer is FALSE.

Check by varying $\alpha$ while keeping everything else fixed. To higher probabilities of Type I errors also correspond higher powers (and lower probabilities of Type II errors). If you increase $\alpha$, the critical values will move towards the centre of the distribution, meaning that there is more "alternative" distribution area beyond the critical values.
