<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Research design &amp; data – DAPR1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-1fa1d8026083a9bddc52b4aafc7f818e.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-8e00f2f28a1266a720913de837032221.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-4823d056cc0a8309e077c97e601d5ea4.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-936f437bde601076d6706b684ef02b78.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-chevron-circle-right')) {
    f.classList.add('fa-chevron-circle-down')
    f.classList.remove('fa-chevron-circle-right')
} else {
    f.classList.add('fa-chevron-circle-right')
    f.classList.remove('fa-chevron-circle-down')
}
}
</script><script src="https://kit.fontawesome.com/120b08a6f5.js" crossorigin="anonymous"></script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css">
<link rel="stylesheet" href="assets/styles.css">
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DAPR1</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-lab-materials" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Lab Materials</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-lab-materials">
<li class="dropdown-header"><b>Block 1: Exploratory data analysis</b></li>
        <li>
    <a class="dropdown-item" href="./1_01_design_and_data.html">
 <span class="dropdown-text">S1-W1: Research design &amp; data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_02_categorical_data.html">
 <span class="dropdown-text">S1-W2: Categorical data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_03_numeric_data.html">
 <span class="dropdown-text">S1-W3: Numeric data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_04_relationships.html">
 <span class="dropdown-text">S1-W4: Relationships</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_05_formative_report_a.html">
 <span class="dropdown-text">S1-W5: Formative Report A</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header"><b>Block 2: Probability</b></li>
        <li>
    <a class="dropdown-item" href="./1_07_prob_theory.html">
 <span class="dropdown-text">S1-W7: Probability Theory</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_08_prob_rules.html">
 <span class="dropdown-text">S1-W8: Probability Rules</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./1_09_discrete_dist.html">
 <span class="dropdown-text">S1-W9: Discrete Random Variables</span></a>
  </li>  
    </ul>
</li>
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-readings" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Readings</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-readings">
<li>
    <a class="dropdown-item" href="./zf_formatting_resources.html">
 <span class="dropdown-text">Formatting Resources</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header"><b>Block 1: Exploratory data analysis</b></li>
        <li>
    <a class="dropdown-item" href="./rd1_01.html">
 <span class="dropdown-text">S1-W1: Getting started with R and RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_02.html">
 <span class="dropdown-text">S1-W2: Categorical data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_03.html">
 <span class="dropdown-text">S1-W3: Numeric data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_04.html">
 <span class="dropdown-text">S1-W4: Relationships</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_05.html">
 <span class="dropdown-text">S1-W5: Functions</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header"><b>Block 2: Probability</b></li>
        <li>
    <a class="dropdown-item" href="./rd1_07.html">
 <span class="dropdown-text">S1-W7: Probability 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_08.html">
 <span class="dropdown-text">S1-W8: Probability 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./rd1_09.html">
 <span class="dropdown-text">S1-W9: Discrete random variables</span></a>
  </li>  
    </ul>
</li>
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">0 Setup</a></li>
  <li>
<a href="#formative-report-a" id="toc-formative-report-a" class="nav-link" data-scroll-target="#formative-report-a"><span class="header-section-number">1</span> Formative Report A</a>
  <ul class="collapse">
<li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">1.1</span> Data</a></li>
  <li><a href="#this-weeks-task" id="toc-this-weeks-task" class="nav-link" data-scroll-target="#this-weeks-task"><span class="header-section-number">1.2</span> This week’s task</a></li>
  </ul>
</li>
  <li><a href="#worked-example" id="toc-worked-example" class="nav-link" data-scroll-target="#worked-example"><span class="header-section-number">2</span> Worked example</a></li>
  <li><a href="#student-glossary" id="toc-student-glossary" class="nav-link" data-scroll-target="#student-glossary"><span class="header-section-number">3</span> Student Glossary</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Research design &amp; data</h1>
<p class="subtitle lead">Semester 1 - Week 1</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="setup" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="setup">0 Setup</h2>
<p><strong>Practicalities</strong>:</p>
<ul>
<li>Sit in tables of at most 5 students per table.</li>
<li>Check your table name and register for that group on LEARN. To do so, navigate to the course LEARN page &gt; click Groups &gt; select Labs_1_2_3_4 &gt; find your group &gt; click Join.</li>
<li>Each week, one person within a table will be the “driver”, responsible for typing on the PC, while the others are the “navigators”, responsible for spotting typos and suggesting the strategy/code the driver should use to answer tasks. This is based on novel pedagogical practice called pair-programming.</li>
<li>The person who is the “driver” will rotate every week, so that everyone experiences being a driver at least once.<br>
</li>
<li>Driver:
<ul>
<li>Log into the RStudio Server Online: go to the course LEARN page &gt; click <em>Quick Links</em> &gt; click <em>RStudio Server Online (by Noteable)</em> &gt; select <em>RStudio</em> from the dropdown &gt; click <em>Start</em>.</li>
<li><a href="https://uoepsy.github.io/dapr1/2526/useful_files/template_formative_report_a.Rmd">Click here to download the template Rmd file</a></li>
<li>Upload the template Rmd file to the RStudio server and add your work to that file.</li>
<li>Save your work regularly by clicking File &gt; Save.</li>
<li>At the end of the lab, download the Rmd file and then share it on your Group Discussion Space.</li>
</ul>
</li>
<li>Navigators:
<ul>
<li>Have the lab tasks open and be ready to tell the driver what to do.</li>
</ul>
</li>
<li>If you have questions, raise your hand and a tutor will come over to help!</li>
</ul>
<p><strong>Overview</strong>:</p>
<ul>
<li>At the start of each teaching block (recall that each block is five weeks long), you will be given a dataset that you will use throughout the labs of that block. By the end of each block your group should have produced a report that analyses the given dataset.</li>
<li>The reports are due by:
<ul>
<li>Formative Report A (Block 1): 12 noon, Friday the 17th of October 2025.</li>
<li>Formative Report B (Block 2): 12 noon, Friday the 28th of November 2025.</li>
<li>Formative Report C (Block 3): 12 noon, Friday the 13th of February 2026.</li>
<li>Assessed Report (Block 4): 12 noon, Friday the 27th of March 2026.</li>
</ul>
</li>
<li>You will be required to submit a PDF file, not the Rmd file used to create the PDF.</li>
<li>No extensions will be available for the formative reports.</li>
<li>You will receive written formative feedback on each of the formative reports the week after the report due date. This will be signposted via announcements.</li>
</ul>
<p><strong>Lab help and support</strong>:</p>
<ul>
<li>The lab is structured to provide various levels of support.</li>
<li>When attending a lab, you should put away distractions and prioritise completing that week’s tasks to make the most of the help available.</li>
<li>If you are unsure or stuck at any point, you should make use of all the available help:
<ul>
<li>Raise your hand to get help from a tutor;</li>
<li>Hover your mouse on the superscript number to get a quick hint. The hints may sometimes show multiple equivalent ways of getting an answer - you just need one way;</li>
<li>Scroll down to the <em>Worked Example</em> section, where you can read through a worked example.</li>
<li>Even if you don’t use the Worked Example to complete the tasks, ensure you review and study its content during your independent study time.</li>
</ul>
</li>
</ul></section><section id="formative-report-a" class="level2 page-columns page-full" data-number="1"><h2 data-number="1" class="anchored" data-anchor-id="formative-report-a">
<span class="header-section-number">1</span> Formative Report A</h2>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Instructions - Don’t Skip!
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Formative Report A covers the labs from weeks 1-5 of the DAPR1 course in semester 1. You’ll need to create a PDF report using RMarkdown, which will be submitted by 12 noon on Friday, 17th October 2025. No extensions are available as this is a formative report. Expect written formative feedback in week 6 of semester 1.</p>
<p>Your report should be tailored for a reader with basic statistical knowledge and should not include any references to R code or functions in the main report write-up. Instead, keep the main report focused on text, figures, and tables. All R code should be included in the compulsory Appendix B for reproducibility, which is automatically created for you in the template Rmd file (do not edit that section). If you need to add extra tables or figures that don’t fit in the main part of the report, you can use an optional Appendix A. Remember, the main report should be a PDF file and should not exceed six sides of A4 paper, though appendices at the end don’t count towards this limit.</p>
<p>Ensure to use the default settings for font and page margins in your RMarkdown file. Also, make sure your report title includes your group name: Group NAME.LETTER, and list the exam numbers of all group members in the author section.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formatting resources
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>At <a href="zf_formatting_resources.html" target="_blank">this page</a> you can find resources to help you with your report formatting.</p>
</div>
</div>
</div>
<section id="data" class="level3" data-number="1.1"><h3 data-number="1.1" class="anchored" data-anchor-id="data">
<span class="header-section-number">1.1</span> Data</h3>
<p><strong>Hollywood Movies</strong>. At the link <a href="https://uoepsy.github.io/data/hollywood_movies_subset.csv" class="uri">https://uoepsy.github.io/data/hollywood_movies_subset.csv</a> you will find data on Hollywood movies released between 2012 and 2018 from the top 5 lead studios and top 10 genres.</p>
<p>The following variables were recorded. For formative report A, please only focus on the variables <code>Movie</code> to <code>Year</code>, ignoring anything beyond that. In other words, do not analyse the variables <code>IQ1</code> to <code>PrivateTransport</code> in the next five weeks of the course. We will use those later in the course.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Movie</td>
<td style="text-align: left;">Title of the movie</td>
</tr>
<tr class="even">
<td style="text-align: left;">LeadStudio</td>
<td style="text-align: left;">Primary U.S. distributor of the movie</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RottenTomatoes</td>
<td style="text-align: left;">Rotten Tomatoes rating (critics)</td>
</tr>
<tr class="even">
<td style="text-align: left;">AudienceScore</td>
<td style="text-align: left;">Audience rating (via Rotten Tomatoes)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Genre</td>
<td style="text-align: left;">One of Action Adventure, Black Comedy, Comedy, Concert, Documentary, Drama, Horror, Musical, Romantic Comedy, Thriller, or Western</td>
</tr>
<tr class="even">
<td style="text-align: left;">TheatersOpenWeek</td>
<td style="text-align: left;">Number of screens for opening weekend</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OpeningWeekend</td>
<td style="text-align: left;">Opening weekend gross (in millions)</td>
</tr>
<tr class="even">
<td style="text-align: left;">BOAvgOpenWeekend</td>
<td style="text-align: left;">Average box office income per theater, opening weekend</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Budget</td>
<td style="text-align: left;">Production budget (in millions)</td>
</tr>
<tr class="even">
<td style="text-align: left;">DomesticGross</td>
<td style="text-align: left;">Gross income for domestic (U.S.) viewers (in millions)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WorldGross</td>
<td style="text-align: left;">Gross income for all viewers (in millions)</td>
</tr>
<tr class="even">
<td style="text-align: left;">ForeignGross</td>
<td style="text-align: left;">Gross income for foreign viewers (in millions)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Profitability</td>
<td style="text-align: left;">WorldGross as a percentage of Budget</td>
</tr>
<tr class="even">
<td style="text-align: left;">OpenProfit</td>
<td style="text-align: left;">Percentage of budget recovered on opening weekend</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Year</td>
<td style="text-align: left;">Year the movie was released</td>
</tr>
<tr class="even">
<td style="text-align: left;">IQ1-IQ50 (ignore for Formative report A)</td>
<td style="text-align: left;">IQ score of each of 50 audience raters</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Snacks (ignore for Formative report A)</td>
<td style="text-align: left;">How many of the 50 audience raters bought snacks</td>
</tr>
<tr class="even">
<td style="text-align: left;">PrivateTransport (ignore for Formative report A)</td>
<td style="text-align: left;">How many of the 50 audience raters reached the cinema via private transportation</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="this-weeks-task" class="level3 page-columns page-full" data-number="1.2"><h3 data-number="1.2" class="anchored" data-anchor-id="this-weeks-task">
<span class="header-section-number">1.2</span> This week’s task</h3>
<p><strong>Task A1</strong></p>
<blockquote class="blockquote">
<p>A1) Read the data into R, inspect it, and write a concise introduction to the data and its structure</p>
</blockquote>
<p><strong>Sub-steps</strong></p>
<p>Below there are sub-steps you need to consider to complete this week’s task.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>To see the hints, hover your cursor on the superscript numbers.</p>
</div>
</div>
</div></div><ul>
<li><p>Read the movie data into R, and give it a useful name. Inspect the data by looking at the data in RStudio. By viewing, we actually mean looking at the data either on the viewer or the console.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p></li>
<li><p>How many observations are there?<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p></li>
<li><p>How many variables are there?<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p></li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-simple callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Think about it
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>What does <code>dim(DATA)</code> return?</li>
<li>What is the function of appending a <code>[1]</code> or <code>[2]</code>?</li>
</ul>
</div>
</div>
</div>
</div></div><ul>
<li><p>What is the type of each variable?<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p></li>
<li><p>What’s the minimum and maximum budget in the sample? What about the minimum and maximum Rotten Tomatoes rating?<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p></li>
<li><p>Do you notice any issues when computing the minimum/maximum Budget and the minimum/maximum RottenTomatoes rating?<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p></li>
<li><p>Which variables have missing values in the dataset, and how many missing values does each have?<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p></li>
<li><p>Write-up a description of the dataset for the reader. You don’t need to show the actual data in the report, but a description in words is sufficient for the reader.</p></li>
</ul>
<!-- Example code --><!-- End --></section></section><section id="worked-example" class="level2 page-columns page-full" data-number="2"><h2 data-number="2" class="anchored" data-anchor-id="worked-example">
<span class="header-section-number">2</span> Worked example</h2>
<p>Consider the dataset available at <a href="https://uoepsy.github.io/data/RestaurantTips.csv" class="uri">https://uoepsy.github.io/data/RestaurantTips.csv</a>, containing 157 observations on the following 7 variables:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 84%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Variable Name</th>
<th style="text-align: left;">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bill</td>
<td style="text-align: left;">Size of the bill (in dollars)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tip</td>
<td style="text-align: left;">Size of the tip (in dollars)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Credit</td>
<td style="text-align: left;">Paid with a credit card? n or y</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guests</td>
<td style="text-align: left;">Number of people in the group</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Day</td>
<td style="text-align: left;">Day of the week: m=Monday, t=Tuesday, w=Wednesday, th=Thursday, or f=Friday</td>
</tr>
<tr class="even">
<td style="text-align: left;">Server</td>
<td style="text-align: left;">Code for specific waiter/waitress: A, B, or C</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PctTip</td>
<td style="text-align: left;">Tip as a percentage of the bill</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>These data were collected by the owner of a bistro in the US, who was interested in understanding the tipping patterns of their customers. The data are adapted from <span class="citation" data-cites="lock2020">Lock et al. (<a href="#ref-lock2020" role="doc-biblioref">2020</a>)</span>.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>We load the <code>tidyverse</code> package as we will use the functions <code>read_csv</code> and <code>glimpse</code> from this package.</p>
</div></div><div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tips</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://uoepsy.github.io/data/RestaurantTips.csv"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>read_csv</code> is the function to read CSV (comma separated values) files. Once we have read the file, it is stored into an object called tips using the arrow (<code>&lt;-</code>).</p>
</div></div><div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">tips</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
   Bill   Tip Credit Guests Day   Server PctTip
  &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt;
1  23.7 10    n           2 f     A        42.2
2  36.1  7    n           3 f     B        19.4
3  32.0  5.01 y           2 f     A        15.7
4  17.4  3.61 y           2 f     B        20.8
5  15.4  3    n           2 f     B        19.5
6  18.6  2.5  n           2 f     A        13.4</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code><a href="https://rdrr.io/r/utils/head.html">head()</a></code> shows by default the top 6 rows of the data. Use the <code>n = ...</code> option to change the default behaviour, e.g.&nbsp;<code>head(&lt;data&gt;, n = 10)</code>.</p>
</div></div><div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">tips</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 157   7</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>This returns the number of rows and columns in the data</p>
</div></div><div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">tips</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 157
Columns: 7
$ Bill   &lt;dbl&gt; 23.70, 36.11, 31.99, 17.39, 15.41, 18.62, 21.56, 19.58, 23.59, …
$ Tip    &lt;dbl&gt; 10.00, 7.00, 5.01, 3.61, 3.00, 2.50, 3.44, 2.42, 3.00, 2.00, 1.…
$ Credit &lt;chr&gt; "n", "n", "y", "y", "n", "n", "n", "n", "n", "n", "n", "n", "n"…
$ Guests &lt;dbl&gt; 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 3, 2, 2, 1, 5, 5, …
$ Day    &lt;chr&gt; "f", "f", "f", "f", "f", "f", "f", "f", "f", "f", "f", "f", "f"…
$ Server &lt;chr&gt; "A", "B", "A", "B", "B", "A", "B", "A", "A", "B", "B", "A", "B"…
$ PctTip &lt;dbl&gt; 42.2, 19.4, 15.7, 20.8, 19.5, 13.4, 16.0, 12.4, 12.7, 10.7, 11.…</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>glimpse</code> is part of the tidyverse package</p>
</div></div><div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Alternative
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Alternatives to glimpse are the data “structure” function:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">tips</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [157 × 7] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Bill  : num [1:157] 23.7 36.1 32 17.4 15.4 ...
 $ Tip   : num [1:157] 10 7 5.01 3.61 3 2.5 3.44 2.42 3 2 ...
 $ Credit: chr [1:157] "n" "n" "y" "y" ...
 $ Guests: num [1:157] 2 3 2 2 2 2 2 2 2 2 ...
 $ Day   : chr [1:157] "f" "f" "f" "f" ...
 $ Server: chr [1:157] "A" "B" "A" "B" ...
 $ PctTip: num [1:157] 42.2 19.4 15.7 20.8 19.5 13.4 16 12.4 12.7 10.7 ...
 - attr(*, "spec")=
  .. cols(
  ..   Bill = col_double(),
  ..   Tip = col_double(),
  ..   Credit = col_character(),
  ..   Guests = col_double(),
  ..   Day = col_character(),
  ..   Server = col_character(),
  ..   PctTip = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p>or:</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">tips</span>, <span class="va">data.class</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Bill         Tip      Credit      Guests         Day      Server 
  "numeric"   "numeric" "character"   "numeric" "character" "character" 
     PctTip 
  "numeric" </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example writeup
</div>
</div>
<div class="callout-body-container callout-body">
<p>A dataset containing records on 7 variables related to tipping was obtained from <a href="https://uoepsy.github.io/data/RestaurantTips.csv" class="uri">https://uoepsy.github.io/data/RestaurantTips.csv</a>, and was provided by the owner of a bistro in the US interested in studying which factors affected the tipping behaviour of the bistro’s customers. The data contains measurements for a total of 157 parties on four numeric variables: size of the bill (in dollars), size of the tip, number of guests in the group, and tip as a percentage of the bill total. The data also includes three categorical variables indicating whether or not the party paid with a credit card, the day of the week, as well as a server-specific identifier.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">tips</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Bill            Tip            Credit              Guests     
 Min.   : 1.66   Min.   : 0.250   Length:157         Min.   :1.000  
 1st Qu.:15.19   1st Qu.: 2.075   Class :character   1st Qu.:2.000  
 Median :20.22   Median : 3.340   Mode  :character   Median :2.000  
 Mean   :22.73   Mean   : 3.807                      Mean   :2.096  
 3rd Qu.:28.84   3rd Qu.: 5.000                      3rd Qu.:2.000  
 Max.   :70.51   Max.   :15.000                      Max.   :7.000  
                 NA's   :1                                          
     Day               Server              PctTip      
 Length:157         Length:157         Min.   :  6.70  
 Class :character   Class :character   1st Qu.: 14.30  
 Mode  :character   Mode  :character   Median : 16.20  
                                       Mean   : 17.89  
                                       3rd Qu.: 18.20  
                                       Max.   :221.00  
                                                       </code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>summary</code> returns a quick summary of the data, i.e.&nbsp;a list of numerical summaries.</p>
</div></div><p>You probably won’t understand some parts of the output above, but we will learn more in the coming weeks, so don’t worry too much about it. For the moment, you should be able to understand the minimum, maximum, and the mean.<br>
Currently, it is not showing very informative output for the categorical variables, also known as factors.</p>
<p>We can replace each factor level with a clearer label. The following code takes the column <code>Day</code> from the <code>tips</code> data and assigns a new label “Monday” to the level “m”, etc.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tips</span><span class="op">$</span><span class="va">Day</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">tips</span><span class="op">$</span><span class="va">Day</span>, </span>
<span>                   levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"m"</span>, <span class="st">"t"</span>, <span class="st">"w"</span>, <span class="st">"th"</span>, <span class="st">"f"</span><span class="op">)</span>,</span>
<span>                   labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Monday"</span>, <span class="st">"Tuesday"</span>, <span class="st">"Wednesday"</span>, <span class="st">"Thursday"</span>, <span class="st">"Friday"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">tips</span><span class="op">$</span><span class="va">Credit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">tips</span><span class="op">$</span><span class="va">Credit</span>, </span>
<span>                      levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"n"</span>, <span class="st">"y"</span><span class="op">)</span>,</span>
<span>                      labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"No"</span>, <span class="st">"Yes"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">tips</span><span class="op">$</span><span class="va">Server</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">tips</span><span class="op">$</span><span class="va">Server</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Alternative
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You can change/update a variable (column) in the data using the function <code>mutate</code> from the tidyverse package. It works as follows:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tips</span> <span class="op">&lt;-</span> <span class="va">tips</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>        Day <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Day</span>,</span>
<span>                     levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"m"</span>, <span class="st">"t"</span>, <span class="st">"w"</span>, <span class="st">"th"</span>, <span class="st">"f"</span><span class="op">)</span>,</span>
<span>                     labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Monday"</span>, <span class="st">"Tuesday"</span>, <span class="st">"Wednesday"</span>, <span class="st">"Thursday"</span>, <span class="st">"Friday"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>        Credit <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Credit</span>,</span>
<span>                        levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"n"</span>, <span class="st">"y"</span><span class="op">)</span>,</span>
<span>                        labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"No"</span>, <span class="st">"Yes"</span><span class="op">)</span><span class="op">)</span>,</span>
<span>        Server <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">Server</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The function <code>|&gt;</code> is called <strong>pipe</strong> and works by taking what’s on the left and passing it to the operation on the right. For example, you can take the logarithm of the whole numbers from 1 to 10 and round them to 2 digits using this code:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span><span class="op">)</span>, digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.00 0.69 1.10 1.39 1.61 1.79 1.95 2.08 2.20 2.30</code></pre>
</div>
</div>
<p>or this equivalent code that uses the pipe <code>|&gt;</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.00 0.69 1.10 1.39 1.61 1.79 1.95 2.08 2.20 2.30</code></pre>
</div>
</div>
<p>You can loosely think of the pipe as “then”. In fact, the pipe takes what’s to its left, and then passes it on to what’s on its right.</p>
<p><strong>Curiosity:</strong> Sometimes you may also find an older version of the pipe, which is <code>%&gt;%</code> and works in the same style. However, <strong>it requires the package tidyverse</strong> to be loaded before you can use the older pipe <code>%&gt;%</code>.</p>
</div>
</div>
</div>
<p>Let’s check the result of the changes to the variable types:</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">tips</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 157
Columns: 7
$ Bill   &lt;dbl&gt; 23.70, 36.11, 31.99, 17.39, 15.41, 18.62, 21.56, 19.58, 23.59, …
$ Tip    &lt;dbl&gt; 10.00, 7.00, 5.01, 3.61, 3.00, 2.50, 3.44, 2.42, 3.00, 2.00, 1.…
$ Credit &lt;fct&gt; No, No, Yes, Yes, No, No, No, No, No, No, No, No, No, No, No, N…
$ Guests &lt;dbl&gt; 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 3, 2, 2, 1, 5, 5, …
$ Day    &lt;fct&gt; Friday, Friday, Friday, Friday, Friday, Friday, Friday, Friday,…
$ Server &lt;fct&gt; A, B, A, B, B, A, B, A, A, B, B, A, B, B, B, B, C, C, C, C, C, …
$ PctTip &lt;dbl&gt; 42.2, 19.4, 15.7, 20.8, 19.5, 13.4, 16.0, 12.4, 12.7, 10.7, 11.…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">tips</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Bill            Tip         Credit        Guests             Day    
 Min.   : 1.66   Min.   : 0.250   No :106   Min.   :1.000   Monday   :20  
 1st Qu.:15.19   1st Qu.: 2.075   Yes: 51   1st Qu.:2.000   Tuesday  :13  
 Median :20.22   Median : 3.340             Median :2.000   Wednesday:62  
 Mean   :22.73   Mean   : 3.807             Mean   :2.096   Thursday :36  
 3rd Qu.:28.84   3rd Qu.: 5.000             3rd Qu.:2.000   Friday   :26  
 Max.   :70.51   Max.   :15.000             Max.   :7.000                 
                 NA's   :1                                                
 Server     PctTip      
 A:60   Min.   :  6.70  
 B:65   1st Qu.: 14.30  
 C:32   Median : 16.20  
        Mean   : 17.89  
        3rd Qu.: 18.20  
        Max.   :221.00  
                        </code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p>After making categorical variables factors, <code>summary</code> shows the count of each category for the categorical variables.</p>
</div></div><p>The percentage of total bill has a maximum value of 221, which seems very strange. Someone is very unlikely to tip more than their bill total. In this case 221% of their bill value seems unlikely.</p>
<p>Let’s inspect the row where <code>PctTip</code> is greater than 100:</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tips</span><span class="op">[</span><span class="va">tips</span><span class="op">$</span><span class="va">PctTip</span> <span class="op">&gt;</span> <span class="fl">100</span>, <span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
   Bill   Tip Credit Guests Day      Server PctTip
  &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;   &lt;dbl&gt; &lt;fct&gt;    &lt;fct&gt;   &lt;dbl&gt;
1  49.6    NA Yes         4 Thursday C         221</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Alternative
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Alternatively, using tidyverse, the function <code>filter</code> is used to only filter the rows that satisfy a condition:</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tips</span> <span class="op">|&gt;</span> </span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">PctTip</span> <span class="op">&gt;</span> <span class="fl">100</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
   Bill   Tip Credit Guests Day      Server PctTip
  &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;   &lt;dbl&gt; &lt;fct&gt;    &lt;fct&gt;   &lt;dbl&gt;
1  49.6    NA Yes         4 Thursday C         221</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>With a bill of 49.6, the tip would be 109.62 dollars:</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fl">49.6</span> <span class="op">*</span> <span class="fl">221</span> <span class="op">/</span> <span class="fl">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 109.616</code></pre>
</div>
</div>
<p>Furthermore, we also notice that the tipping amount is not available (NA). The corresponding value in the percentage of total tip seems likely an inputting error, perhaps due to double typing the leading 2 when recording the data. We will set that value to not available (NA) with the following code:</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tips</span><span class="op">$</span><span class="va">PctTip</span><span class="op">[</span><span class="va">tips</span><span class="op">$</span><span class="va">PctTip</span> <span class="op">&gt;</span> <span class="fl">100</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>a &gt; b</code> tests whether a is greater than b. <code>a &lt; b</code> tests whether a is smaller than b. <code>a == b</code> tests whether a is equal to b; notice the double equal sign! You can also use <code>&gt;=</code> or <code>&lt;=</code></p>
</div></div><div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Alternative
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Alternatively you can use tidyverse:</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tips</span> <span class="op">&lt;-</span> <span class="va">tips</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>        PctTip <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">PctTip</span> <span class="op">&gt;</span> <span class="fl">100</span>, <span class="cn">NA</span>, <span class="va">PctTip</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Where the function <code>ifelse</code> selects a value depending on a condition to test: <code>ifelse(test, value_if_true, value_if_false)</code>. In the case above, each value in the column PctTip is replaced by NA if Pct &gt; 100, and it is kept the same otherwise.</p>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">tips</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Bill            Tip         Credit        Guests             Day    
 Min.   : 1.66   Min.   : 0.250   No :106   Min.   :1.000   Monday   :20  
 1st Qu.:15.19   1st Qu.: 2.075   Yes: 51   1st Qu.:2.000   Tuesday  :13  
 Median :20.22   Median : 3.340             Median :2.000   Wednesday:62  
 Mean   :22.73   Mean   : 3.807             Mean   :2.096   Thursday :36  
 3rd Qu.:28.84   3rd Qu.: 5.000             3rd Qu.:2.000   Friday   :26  
 Max.   :70.51   Max.   :15.000             Max.   :7.000                 
                 NA's   :1                                                
 Server     PctTip     
 A:60   Min.   : 6.70  
 B:65   1st Qu.:14.30  
 C:32   Median :16.15  
        Mean   :16.59  
        3rd Qu.:18.05  
        Max.   :42.20  
        NA's   :1      </code></pre>
</div>
</div>
<p>The function <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> return a numeric answer for the min/max/mean, see above, even in the presence of missing values (NAs).</p>
<p>However, if you use functions such as <code><a href="https://rdrr.io/r/base/Extremes.html">min()</a></code>, <code><a href="https://rdrr.io/r/base/Extremes.html">max()</a></code>, <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>, which compute the minimum, maximum, and mean (i.e., average) of a variable respectively, they will return NA when applied to a variable that contains a missing value:</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">tips</span><span class="op">$</span><span class="va">Tip</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
</div>
<p>To get a numeric result, you need to include the argument, i.e.&nbsp;the option, <code>na.rm = TRUE</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">tips</span><span class="op">$</span><span class="va">Tip</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.25</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example writeup
</div>
</div>
<div class="callout-body-container callout-body">
<p>The average bill size was $22.73, and the average tip was $3.81, corresponding to roughly 17% of the total bill. Out of 157 parties, only 51 paid with a credit card. Most parties tended to be of around 2 people each, and people tended to go to that restaurant more often on Wednesday. Among the three servers, server C was the one that served the least number of parties. The data also included a missing tipping value, corresponding to a bill $49.59, and a data inputting error for the corresponding measure of the tip as a percentage of the total bill.</p>
</div>
</div>
</section><section id="student-glossary" class="level2" data-number="3"><h2 data-number="3" class="anchored" data-anchor-id="student-glossary">
<span class="header-section-number">3</span> Student Glossary</h2>
<p>A good understanding of R functions is essential for your success in the DAPR curriculum and the degree more generally. We strongly recommend you get into the habit of keeping track of any new R function that you encounter and write a short description of what the function does and which package it comes from. You could save this into a Word, Excel, or Notebook file. You should get into the habit of updating that document as you encounter new R functions. For this week, we have provided below a completed table to help you get started!</p>
<table class="caption-top table">
<colgroup>
<col style="width: 44%">
<col style="width: 55%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Function</th>
<th style="text-align: left;">Use and package</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>&lt;-</code></td>
<td style="text-align: left;">Assignment operator. Stores the value on the right into the named object on the left</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>read_csv</code></td>
<td style="text-align: left;">For reading comma separated value files. Part of tidyverse package</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>View</code></td>
<td style="text-align: left;">Opens a spreadsheet-like data viewer in RStudio. Base R function</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>head</code></td>
<td style="text-align: left;">Shows the first 6 rows of a dataset (by default). Base R function</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>nrow</code></td>
<td style="text-align: left;">Returns the number of rows. Base R function</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>ncol</code></td>
<td style="text-align: left;">Returns the number of columns. Base R function</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>dim</code></td>
<td style="text-align: left;">Returns the dimensions (rows and columns). Base R function</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>glimpse</code></td>
<td style="text-align: left;">Similar to <code>str</code>. Displays an overview of the data variables with their types. Part of tidyverse package</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>str</code></td>
<td style="text-align: left;">Similar to <code>glimpse</code>. Displays an overview of the data variables with their types. Base R function</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>summary</code></td>
<td style="text-align: left;">Produces summary statistics. Base R function</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>factor</code></td>
<td style="text-align: left;">Creates or modifies a variable into a categorical one (factor) with levels. Base R function</td>
</tr>
</tbody>
</table>



</section><a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-lock2020" class="csl-entry" role="listitem">
Lock, Robin H, Patti Frazer Lock, Kari Lock Morgan, Eric F Lock, and Dennis F Lock. 2020. <em>Statistics: Unlocking the Power of Data</em>. John Wiley &amp; Sons.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>
<ol>
<li id="fn1"><p> Hint: To read the data use <code><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv()</a></code> from the <code>tidyverse</code> package. <br> To preview the data, use <code>View(DATA)</code> or <code>head(DATA)</code><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p> Hint: <code>nrow(DATA)</code> <br> or <code>dim(DATA)[1]</code><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p> Hint: <code>ncol(DATA)</code> <br> or <code>dim(DATA)[2]</code><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p> Hint: <code>glimpse(DATA)</code> from <code>tidyverse</code><br> or <code>str(DATA)</code><br> or <code>sapply(DATA, data.class)</code><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p> Hint: <code>summary(DATA$VARIABLE)</code><br> or <code>min(DATA$VARIABLE)</code> and <code>max(DATA$VARIABLE)</code><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p> For some movies, data on the budget or rotten tomatoes rating are not available (NA). These are also called missing values.<br>
If you used the functions <code><a href="https://rdrr.io/r/base/Extremes.html">min()</a></code>, <code><a href="https://rdrr.io/r/base/Extremes.html">max()</a></code>, you will get NA as a result. This is because if a value is missing, you cannot compute the mean of something you don’t know. For example, what is the mean of 5, 10, and NA? How would I compute (5 + 10 + NA) / 3? I don’t know, so it remains NA.<br>
You can tell R to ignore the missing values by saying <code>min(DATA$VARIABLE, na.rm = TRUE)</code> and similarly for <code>max</code> and other functions like <code>mean</code>, which computes the average instead.<br>
The <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function, instead, does this for you automatically and immediately tells you if a variable had any NAs and how many.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p> Hint: <code>summary(DATA)</code> shows the variables and the number of missing values in each variable.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>