---
title: "Frequently Asked Questions (FAQs)"
author: "DAPR1 course"
date: ""
output: 
    html_document:
        theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("htmltools")
library("bsplus")
```

<br>
<center>
Please click to expand
</center>
<br>

```{r echo=FALSE}
bs_accordion(id = "faqs-dapr1") %>%
    bs_set_opts(panel_type = "default", 
                use_heading_link = TRUE) %>%
    bs_append(
        title = "Where do I start?", 
        content = HTML("Navigate to the course Learn page and read the 'Course Information' and the 'Assessment' -> 'Assessment information' pages.<br>Then, move on to the 'Course materials: Semester 1'.")
    ) %>%
    bs_append(
        title = "How do I register for RStudio server online?",
        content = HTML("Navigate to the course Learn page -> Click 'Course materials: Semester 1' -> 'S1 Week 0: DAPR1 starts here' -> 'Register for RStudio server online'")
    ) %>%
    bs_append(
        title = "I am registered for RStudio server online, how do I access it?",
        content = HTML("<ol><li>Log in to <a href=\"https://www.ease.ed.ac.uk/\"></a>EASE using your university UUN and password.</li>
<li>Access the server from <a href=\"https://rstudio.ppls.ed.ac.uk\">https://rstudio.ppls.ed.ac.uk</a> using your university UUN and the RStudio password.</li>
</ol>
If you have forgotten your RStudio password, you can reset it following the next FAQ instructions.")
    ) %>%
    bs_append(
        title = "How do I change my RStudio server password?",
        content = HTML("<ol><li>Set your RStudio password at <a href=\"https://rstudio.ppls.ed.ac.uk/setpass.php\">https://rstudio.ppls.ed.ac.uk/setpass.php</a>, the username will be the same as your UUN (make sure you type your UUN correctly).</li>
<li>Access the server from <a href=\"https://rstudio.ppls.ed.ac.uk\">https://rstudio.ppls.ed.ac.uk</a> using your university UUN and the password you just set above.</li>
</ol>")
    ) %>%
    bs_append(
        title = "Where do I find office hours information?",
        content = HTML("Navigate to the course Learn page -> Click 'Course information' -> 'Course contacts' -> Click the instructor\'s name")
    ) %>%
    bs_append(
        title = "Where do I find information about the course assessments?",
        content = HTML("Navigate to the course Learn page -> Click 'Assessment' -> 'Assessment information'")
    ) %>%
    bs_append(
        title = "Is lab attendance graded?",
        content = HTML("No, attending the labs does not affect your course grade. In the past years, however, students who failed the assessed report tended to not attend the labs. <br>
There was a positive association between attending the labs and the grade received in the report.")
    ) %>%
    bs_append(
        title = "Can I change the day and/or time of my lab?",
        content = HTML("After Week 3 of semester 1 it is <b>not</b> possible to change lab day/time. Before the end of Week 3, please submit the following <a href=\"https://www.ed.ac.uk/timetabling-examinations/timetabling/personalised-timetables/group-change-request\">form</a>.")
    ) %>%
    bs_append(
        title = "What are formative assessments?
Formative means practice, so formative assessments do not affect your course grade.",
content = HTML("They are meant to prepare you for summative (graded) assessments that will contribute towards your final course grade. Formative assessments give you the opportunity to 'learn by doing'. You should not be afraid to submit what you have done, as you will receive feedback on how to improve.")
    ) %>%
    bs_append(
        title = "Where can I find my quiz grades on LEARN?",
        content = HTML("Go to the LEARN page for your course. On the top menu bar, click 'Gradebook' and find the relevant quiz.")
    ) %>%
    bs_append(
        title = "Where can I find the solutions & feedback for the LEARN quizzes?",
        content = HTML("The quiz solutions and feedback are NOT immediately available after your submission, only your grade is. The solutions and feedback are available on Sunday after 5pm.<br>
Go to the LEARN page of your course. On the top menu bar, click 'Gradebook.' Then, click on the name of the quiz for which you would like to see the question by question feedback. Next, click on 'View Submission'.")
    ) %>%
    bs_append(
        title = "How do I access the Piazza Discussion Forum?",
        content = HTML("On the course LEARN page you will find a link to the Piazza Discussion Forum. Depending on your course, it may just be called Discussion Forum.")
    ) %>%
    bs_append(
        title = "How do I apply for extensions or special circumstances?",
        content = HTML("These are handled by a separated office of the University. Please follow the steps detailed in <a href=\"https://www.ed.ac.uk/student-administration/extensions-special-circumstances\" target=\"_blank\">this website</a>")
    ) %>%
    bs_append(
        title = "Where can I get help and support?",
        content = HTML("<p>The following is a list of sources of help and support:</p>
            
            <ul>
            
            <li><p><strong>Labs</strong>. Attend the labs to get help and support from tutors on the content of the lab exercises, R and RStudio, as well as lecture contents.</p></li>
            
            <li><p><strong>Office Hours</strong>. Attend office hours to receive one-to-one help on the course materials.</p></li>
            
            <li><p><strong>Discussion Forum</strong>. Search on the Piazza Discussion Forum, in case another student had the same question and it was already answered.</p>
            <p>You can also ask a new question on the Discussion Forum if no one has already asked the same question. Your student peers or instructors will be able to provide an answer to your question.</p></li>
            
            <li><p><strong>TO</strong>. The teaching organisation (<a href=\"mailto:ppls.psych@ed.ac.uk\" target=\"_blank\">ppls.psych@ed.ac.uk</a>) can advise you on administrative enquiries about your course. This includes issues with submission of assessments, extensions, special circumstances, or exams.</p></li>

            <li><p><strong>Student Adviser</strong>. Your student adviser (you can find their name on MyEd or Euclid) is your first point of contact for generic help and support on matters that are not directly related to your course materials or organisation. They are able to also refer you to wider University services, such as the Wellbeing adviser, see below.</p></li>
                       
                      
            <li><p><strong>Wellbeing adviser</strong>. The <a href=\"https://www.ed.ac.uk/student-wellbeing-service\" target=\"_blank\">Wellbeing adviser</a> can provide you with advice on wellbeing-related issues and recommend other specialist services, such as the Student Counselling Service or the Disability and Learning Support Service, who may be able to help you. You can be referred to the Wellbeing adviser by your Student adviser, or you can self-refer at the link above.</p></li>
                
            </ul>")
    )
```

