---
title: 'DAPR1: S2W2 - Lecture Activities'
author: "Department of Psychology<br>University of Edinburgh"
date: ""
output:
  html_document:
    theme: flatly
---


# Activity

For each of the following questions of interest formally state the null and alternative hypotheses using symbols.

1. Are children exposed to pesticides more likely to develop ADHD (attention-deficit/hyperactivity disorder) than those who aren't exposed? 

1. Is the average age of ICU patients at this hospital greater than 50 years?

1. If you want to remember something, does taking a nap work better than having some caffeine?

<!-- 1. When getting voters to support a candidate in an election, is there a difference between a recorded phone call from the candidate or a flyer about the candidate sent through the mail? -->

<!-- 1. Does this new allergy medication really reduce symptoms more than a placebo?  -->

<br>
<br>

---  

*Scroll down for answers*  
  
---

<div style="margin-bottom:750px;">

</div>

# Answers

1. Are children exposed to pesticides more likely to develop ADHD (attention-deficit/hyperactivity disorder) than those who aren't exposed? 

    $$
    H_0: p_{\text{exposed}} = p_{\text{not exposed}} \\
    H_1: p_{\text{exposed}} > p_{\text{not exposed}}
    $$  
    where $p$ is the proportion of children diagnosed with ADHD.
    
    Alternatively,
    
    $$
    H_0: p_{\text{exposed}} - p_{\text{not exposed}} = 0 \\
    H_1: p_{\text{exposed}} - p_{\text{not exposed}} > 0
    $$  
    
1. Is the average age of ICU patients at this hospital greater than 50 years?

    $$
    H_0 : \mu = 50 \\
    H_1 : \mu > 50
    $$  
    where $\mu$ is the population mean age (in years) in the hospital's ICU unit.

1. If you want to remember something, does taking a nap work better than having some caffeine?
    
    $$
    H_0 : \mu_{\text{nap}} = \mu_{\text{caffeine}} \\
    H_1 : \mu_{\text{nap}} > \mu_{\text{caffeine}}
    $$  
    where $\mu$ is the average number of items remembered from a list (that the researcher has developed and used for testing the participants).
    
    Alternatively:
    
    $$
    H_0 : \mu_{\text{nap}} - \mu_{\text{caffeine}} = 0\\
    H_1 : \mu_{\text{nap}} - \mu_{\text{caffeine}} > 0
    $$  

<!-- 1. When getting voters to support a candidate in an election, is there a difference between a recorded phone call from the candidate or a flyer about the candidate sent through the mail? -->

<!--     $$ -->
<!--     H_0 : p_{\text{call}} = p_{\text{flyer}} \\ -->
<!--     H_1 : p_{\text{call}} \neq p_{\text{flyer}} -->
<!--     $$   -->
<!--     where $p$ is the proportion of votes for that candidate. -->

<!--     Alternatively: -->
<!--     $$ -->
<!--     H_0 : p_{\text{call}} - p_{\text{flyer}} = 0 \\ -->
<!--     H_1 : p_{\text{call}} - p_{\text{flyer}} \neq 0 -->
<!--     $$   -->

<!-- 1. Does this new allergy medication really reduce symptoms more than a placebo?  -->

<!--     $$ -->
<!--     H_0 : p_{\text{medication}} = p_{\text{placebo}} \\ -->
<!--     H_1 : p_{\text{medication}} < p_{\text{placebo}} -->
<!--     $$   -->
<!--     where $p$ is the proportion of people that develop symptoms. -->

<!--     Alternatively: -->

<!--     $$ -->
<!--     H_0 : p_{\text{medication}} - p_{\text{placebo}} = 0\\ -->
<!--     H_1 : p_{\text{medication}} - p_{\text{placebo}} < 0 -->
<!--     $$ -->
