---
title: 'dapR1: Discrete Probability Distributions Activities - 1'
author: "Department of Psychology<br>University of Edinburgh"
date: "AY 2020-2021"
output:
  html_document:
    theme: flatly
---

## Question 1

I randomly select a house from a list of all the addresses in Edinburgh. What kind of random variable am I describing? 

a. A sample space. 
b. A continuous random variable. 
c. A discrete random variable. 
d. It's not a random variable. 

## Question 2

What is the difference between a probability mass function and a probability density function? 

## Question 3

I roll two six sided dice and add up the numbers on their faces. If I make a table that lists the number of ways that each outcome (2-12) can occur, what have I made?

a. A frequency distribution. 
b. A probability distribution. 
c. A probability mass function. 
d. A random variable



<br>
<br>

---  

*Scroll down for answers*  
  
---

<div style="margin-bottom:750px;">

</div>


# Answers

1. c 
2. A probability mass functions assigns probabilities to outcomes of a discrete random variable and a probability density function does so for a continuous random variable. 
3. a


