<<<<<<< HEAD
---
title: 'dapR1: More Probability Activities - 2'
author: "Department of Psychology<br>University of Edinburgh"
date: "AY 2020-2021"
output:
  html_document:
    theme: flatly
---


# Question 1

The probability of it raining is .20, and the probability of drawing a heart from a deck of cards is .25. With this information can you calculate the probability of $p(R \cup W)$? 

# Question 2

If I tell you that $p(A \cup B) = .14$ can you tell me what $p(B \cup A)$ is? 

# Question 3

If $p(A)$ is .4 and $p(A \cap B)$ is .2, what is $p(B|A)$? 

<br>
<br>

---  

*Scroll down for answers*  
  
---

<div style="margin-bottom:750px;">

</div>

# Answers

1. Yes, because the events are independent (whether it is raining has no bearing on whether you draw a heart from a deck of cards), so all you have to do multiply them.   

2. Yes, because $p(A \cup B) = p(B \cup A)$ (and is commutative), so the answer is just .14  

3. $p(B|A) = \frac{p(A \cap B)}{p(A)} = \frac{0.2}{0.4} = 0.5$



=======
---
title: 'dapR1: More Probability Activities - 2'
author: "Department of Psychology<br>University of Edinburgh"
date: "AY 2020-2021"
output:
  html_document:
    theme: flatly
---


# Question 1

The probability of it raining is .20, and the probability of drawing a heart from a deck of cards is .25. With this information can you calculate the probability of $p(R \cap W)$? 

# Question 2

If I tell you that $p(A \cup B) = .14$ can you tell me what $p(B \cup A)$ is? 

# Question 3

If $p(A)$ is .4 and $p(A \cap B)$ is .2, what is $p(B|A)$? 

<br>
<br>

---  

*Scroll down for answers*  
  
---

<div style="margin-bottom:750px;">

</div>

# Answers

1. Yes, because the events are independent (whether it is raining has no bearing on whether you draw a heart from a deck of cards), so all you have to do multiply them. $p(R \cap W) = p(R) \cdot p(W)$ 

2. Yes, because $p(A \cup B) = p(B \cup A)$ (and is commutative), so the answer is just .14  

3. $p(B|A) = \frac{p(A \cap B)}{p(A)} = \frac{0.2}{0.4} = 0.5$



>>>>>>> master
