---
title: "Lecture slide template"
subtitle: "How to reveal.js"
author: "Dr Milan Val&aacute;&scaron;ek"
---

## Timeline {data-background-size="contain" data-background-transition="fade" data-background="timeline.png"}

## dapR 1 {data-transition="slide" data-background-size="cover" data-background-transition="slide" data-background="tile01.png"}
 
 - The graphics are all background pictures
 - They don't scale well but look good on a big screen
 - Pictures need to be saved according to relative path in `data-background=`
 
## dapR 2 {data-transition="slide" data-background-size="cover" data-background-transition="slide" data-background="tile02.png"}

 - lah
 - di
 - dah
 
## dapR 3 {data-transition="slide" data-background-size="cover" data-background-transition="slide" data-background="tile03.png"}

## Mini Dissertation {data-transition="slide" data-background-size="cover" data-background-transition="slide" data-background="tile04.png"}

## The real thing {data-transition="slide" data-background-size="cover" data-background-transition="slide" data-background="tile05.png"}

## Life {data-transition="slide" data-background-size="cover" data-background-transition="slide" data-background="tile06.png"}

## That's all!
